-- Autogenerated file. Do not Edit! Change in c_contants.c instead. 

with Interfaces.C;

package C_Constants is

  type OS_Type is (Mac_X64, Lnx_X64, Lnx_A32);

  OS : constant OS_Type := Lnx_X64;

  O_RDONLY    : constant Interfaces.C.Int := 0; -- open for reading only
  O_WRONLY    : constant Interfaces.C.Int := 1; -- open for writing only
  O_RDWR      : constant Interfaces.C.Int := 2; -- open for reading and writing
  O_CREAT     : constant Interfaces.C.Int := 64; -- no file? create it
  O_EXCL      : constant Interfaces.C.Int := 128; -- lock file (see below)
  O_NOCTTY    : constant Interfaces.C.Int := 256; -- if tty, don't acquire it
  O_TRUNC     : constant Interfaces.C.Int := 512; -- file exists? truncate it
  O_APPEND    : constant Interfaces.C.Int := 1024; -- file exists? move to end
  O_NONBLOCK  : constant Interfaces.C.Int := 2048; -- if pipe, don't wait for data
  O_SYNC      : constant Interfaces.C.Int := 1052672; -- don't cache writes
  O_ASYNC     : constant Interfaces.C.Int := 8192; -- async. IO via SIGIO
  O_DIRECT    : constant Interfaces.C.Int := 16384; -- direct disk access
  O_LARGEFILE : constant Interfaces.C.Int := 0; -- not implemented in Linux (yet)
  O_DIRECTORY : constant Interfaces.C.Int := 65536; -- error if file isn't a dir
  O_NOFOLLOW  : constant Interfaces.C.Int := 131072; -- if sym link, open link itself
  F_RDLCK  : constant Interfaces.C.Int := 0; -- read lock
  F_WRLCK  : constant Interfaces.C.Int := 1; -- write lock
  F_UNLCK  : constant Interfaces.C.Int := 2; -- unlock (remove a lock)
  F_EXLCK  : constant Interfaces.C.Int := 4; -- exclusive lock
  F_SHLCK  : constant Interfaces.C.Int := 8; -- shared lock
  F_DUPFD  : constant Interfaces.C.Int := 0; --
  F_GETFD  : constant Interfaces.C.Int := 1; --
  F_SETFD  : constant Interfaces.C.Int := 2; --
  F_GETFL  : constant Interfaces.C.Int := 3; --
  F_SETFL  : constant Interfaces.C.Int := 4; --
  F_GETLK  : constant Interfaces.C.Int := 5; --
  F_SETLK  : constant Interfaces.C.Int := 6; --
  F_SETLKW : constant Interfaces.C.Int := 7; --
  F_SETOWN : constant Interfaces.C.Int := 8; --
  F_GETOWN : constant Interfaces.C.Int := 9; --
  F_SETSIG : constant Interfaces.C.Int := 10; --
  F_GETSIG : constant Interfaces.C.Int := 11; --
  SEEK_SET : constant Interfaces.C.Int := 0; -- absolute position
  SEEK_CUR : constant Interfaces.C.Int := 1; -- offset from current position
  SEEK_END : constant Interfaces.C.Int := 2; -- offset from end of file

  -- for lockf
  F_ULOCK : constant Interfaces.C.Int := 0; --  /usr/include/fcntl.h:188
  F_LOCK : constant Interfaces.C.Int := 1;  --  /usr/include/fcntl.h:189
  F_TLOCK : constant Interfaces.C.Int := 2; --  /usr/include/fcntl.h
  F_TEST : constant Interfaces.C.Int := 3;  --  /usr/include/fcntl.h
end C_Constants;
