<?xml version="1.0" encoding="iso-8859-1"?>
<xsl:stylesheet
    version="1.0"
    xmlns="http://docbook.org/ns/docbook" 
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="xml"  encoding='iso8859-1'/>

  <!-- Main -->
  <xsl:template match="/">
    <chapter xml:id='database_description' xmlns='http://docbook.org/ns/docbook' version='5.0' > <!-- document root -->
      <title>
        Database Table Description
      </title>
      <xsl:apply-templates/>
    </chapter>
  </xsl:template>

  <!-- The table -->
  <xsl:template match="Tables">
    <para>  <!-- found node Tables, print something and continue -->
       This chapter was autogenerated to document the
       structure of database tables used in project bet bot.
    </para>
    <xsl:apply-templates/>
  </xsl:template>

  <!-- The tables -->
  <xsl:template match="Table">
  <!-- Inside a table node, start a new section-->
    <xsl:variable name="Table_Name" select="Name"/>
    <section id="{$Table_Name}">
      <title>
        <xsl:value-of select="$Table_Name"/>
      </title>
      <xsl:apply-templates/>
    </section>
  </xsl:template>

  <xsl:template match="Name"/>         <!-- surpress output again-->
  <xsl:template match="Description"/>  <!-- surpress output again -->

  <!-- Keys -->
  <xsl:template match="Keys">
  <!-- If there are any keys, process them, else say they are missing-->
    <xsl:choose>
      <xsl:when test="count(Key) > 0">
        <table>
          <title>Index in <xsl:value-of select="../Name"/> </title>
          <tgroup cols="4">
            <thead>
              <row>
                <entry> Name </entry>
                <entry> Primary? </entry>
                <entry> Unique? </entry>
                <entry> Definition </entry>
              </row>
            </thead>
            <tbody>
              <xsl:apply-templates/>
            </tbody>
          </tgroup>
        </table>
      </xsl:when>
      <xsl:otherwise>
        <para>
          There are no indicies.
        </para>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <xsl:template match="Key">
  <!-- Fill the table -->
    <row>
      <entry>
        <xsl:value-of select="Name"/>
      </entry>
      <entry>
        <xsl:value-of select="IsPrimary"/>
      </entry>
      <entry>
        <xsl:value-of select="IsUnique"/>
      </entry>
      <entry>
        <xsl:value-of select="Definition"/>
      </entry>
    </row>
  </xsl:template>

  <!-- Relations -->
  <xsl:template match="Relations">
    <xsl:choose>
      <xsl:when test="count(Relation) > 0">
        <table>
          <title>Relations for <xsl:value-of select="../Name"/> </title>
          <tgroup cols="5">
            <thead>
              <row>
                <entry> Description </entry>
                <entry> Constraints </entry>
                <entry> # of keys </entry>
                <entry> Index </entry>
                <entry> Foreign keys </entry>
              </row>
            </thead>
            <tbody>
              <xsl:apply-templates/>
            </tbody>
          </tgroup>
        </table>
      </xsl:when>
      <xsl:otherwise>
        <para>
          There are no relations.
        </para>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <xsl:template match="Relation">
    <row>
      <entry>
        <xsl:value-of select="Relatedtable"/>
      </entry>
      <entry>
        <xsl:value-of select="Delconstr"/>
      </entry>
      <entry>
        <xsl:value-of select="Keyno"/>
      </entry>
      <entry>
        <xsl:value-of select="Index"/>
      </entry>
      <entry>
        <xsl:value-of select="Foreignkeyfields"/>
      </entry>
    </row>
  </xsl:template>

  <!-- Fields -->
  <xsl:template match="Fields">
    <xsl:choose>
      <xsl:when test="count(Fielddesc) > 0">
        <table>
          <title>Fields in <xsl:value-of select="../Name"/></title>
          <tgroup cols="5">
            <thead>
              <row>
                <entry> Fieldname </entry>
                <entry> Type </entry>
                <entry> Not null? </entry>
                <entry> Has default? </entry>
                <entry> Field number </entry>
              </row>
            </thead>
            <tbody>
              <xsl:apply-templates/>
            </tbody>
          </tgroup>
        </table>
      </xsl:when>
      <xsl:otherwise>
        <para>
          There are no fields.
        </para>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <xsl:template match="Fielddesc">
    <row>
      <entry>
        <xsl:value-of select="Name"/>
      </entry>
      <entry>
        <xsl:value-of select="Type"/>
      </entry>
      <entry>
        <xsl:value-of select="NotNull"/>
      </entry>
      <entry>
        <xsl:value-of select="HasDef"/>
      </entry>
      <entry>
        <xsl:value-of select="FieldNum"/>
      </entry>
    </row>
  </xsl:template>
</xsl:stylesheet>
   