select 
  E.EVENTNAME,
  M_SCORE.STARTTS    SCORE_STARTTS,
  M_SCORE.MARKETID   SCORE_MARKETID,
  M_MATCH.MARKETID   MATCH_MARKETID,
  R_SCORE.RUNNERNAME SCORE_RUNNERNAME,
  R_SCORE.STATUS     R_SCORE_STATUS,
  P_SCORE.BACKPRICE  P_SCORE_BACKPRICE,
  P_SCORE.LAYPRICE   P_SCORE_LAYPRICE,
  R_HOME.RUNNERNAME  R_HOME_RUNNERNAME,
  R_HOME.STATUS      R_HOME_STATUS,
  P_HOME.BACKPRICE   P_HOME_BACKPRICE,
  P_HOME.LAYPRICE    P_HOME_LAYPRICE,
  R_DRAW.RUNNERNAME  R_DRAW_RUNNERNAME,
  R_DRAW.STATUS      R_DRAW_STATUS,
  P_DRAW.BACKPRICE   P_DRAW_BACKPRICE,
  P_DRAW.LAYPRICE    P_DRAW_LAYPRICE,
  R_AWAY.RUNNERNAME  R_AWAY_RUNNERNAME,
  R_AWAY.STATUS      R_AWAY_STATUS,
  P_AWAY.BACKPRICE   P_AWAY_BACKPRICE,
  P_AWAY.LAYPRICE    P_AWAY_LAYPRICE  
from 
  AEVENTS  E, 
  AMARKETS M_SCORE, 
  AMARKETS M_MATCH, 
  ARUNNERS R_SCORE, 
  APRICES  P_SCORE, 
  ARUNNERS R_HOME, 
  APRICES  P_HOME,  
  ARUNNERS R_DRAW, 
  APRICES  P_DRAW,  
  ARUNNERS R_AWAY, 
  APRICES  P_AWAY
where E.EVENTID           = M_SCORE.EVENTID
and   E.EVENTID           = M_MATCH.EVENTID
and   P_SCORE.MARKETID    = M_SCORE.MARKETID 
and   P_SCORE.MARKETID    = R_SCORE.MARKETID 
and   P_SCORE.SELECTIONID = R_SCORE.SELECTIONID 

and   P_HOME.MARKETID     = M_MATCH.MARKETID 
and   P_HOME.MARKETID     = R_HOME.MARKETID 
and   P_HOME.SELECTIONID  = R_HOME.SELECTIONID 
and   R_HOME.RUNNERNAME = substring(E.EVENTNAME for position(' v ' in E.EVENTNAME)-1 )
       
and   P_DRAW.MARKETID     = M_MATCH.MARKETID 
and   P_DRAW.MARKETID     = R_DRAW.MARKETID 
and   P_DRAW.SELECTIONID  = R_DRAW.SELECTIONID 
and   R_DRAW.RUNNERNAME   in ('The Draw','Oavgjort') 

and   P_AWAY.MARKETID     = M_MATCH.MARKETID 
and   P_AWAY.MARKETID     = R_AWAY.MARKETID 
and   P_AWAY.SELECTIONID  = R_AWAY.SELECTIONID 
and   R_AWAY.RUNNERNAME = substring(E.EVENTNAME from position(' v ' in E.EVENTNAME)+3 )

and   E.EVENTTYPEID       = 1 
and   M_SCORE.MARKETTYPE  = 'CORRECT_SCORE'   
and   M_MATCH.MARKETTYPE  = 'MATCH_ODDS'
and   ((R_SCORE.RUNNERNAME = 'Any Unquoted') or (R_SCORE.RUNNERNAME like '%vriga'))
order by 
  M_SCORE.STARTTS,
  E.EVENTID

  
--lock M_SCORE on markets like 'CORRECT_SCORE'  
--lock M_MATCH on markets like 'MATCH_ODDS' 
 
--lock P_SCORE on 'CORRECT_SCORE' prices 
--lock R_SCORE on 'CORRECT_SCORE' runners,  

--lock P_HOME on 'MATCH_ODDS' prices for home team
--lock R_HOME on 'MATCH_ODDS' runners for home team  

--lock P_AWAY on 'MATCH_ODDS' prices for away team
--lock R_AWAY on 'MATCH_ODDS' runners for away team  

--lock P_DRAW on 'MATCH_ODDS' prices for the draw
--lock R_DRAW on 'MATCH_ODDS' runners for draw  


--lock P_SCORE 

  
  
--and P.LAYPRICE < 20
--and P.LAYPRICE > 0
--and P.BACKPRICE > 2
--and R_SCORE.STATUS ='WINNER'
--and   E.COUNTRYCODE = 'GB' 
--and   M_SCORE.MARKETTYPE = 'HALF_TIME_SCORE'   
