

-- Autogenerated by /usr2/betbot/script/bash/create_revision_info.bash 
package Bot_Svn_Info is 
  Revision : constant String := "674066641625cd8474864d4a1bf3c86b27f3677c"
  ; -- intentionally on this line!
end Bot_Svn_Info;

