-----------------------------------------------------
-- This file is AUTOGENERATED by                     
-- repo                                              
--                                                   
----CHANGES HERE WILL BE LOST NEXT GENERATE!!!!----- 
-----------DO NOT EDIT THIS FILE!!!!---------------- 
-----------------------------------------------------



with Ada.Containers.Doubly_Linked_Lists;
with Ada.Containers.Hashed_Maps;
with Ada.Containers.Ordered_Maps;
with Ada.Strings;
with Ada.Strings.Hash;
with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;
with Gnatcoll.Json; use Gnatcoll.Json;
with Types, Calendar2, Sql;
with Table_Utils;  --All tables inherit from here

pragma Elaborate_All(Calendar2);



package Table_Aevents is
  use Types, Calendar2;
  --
  --  Table name as string 
  --

  Table_Aevents_Name     : constant String := "AEVENTS";
  Table_Aevents_Set_Name : constant String := "AEVENTS_SET";
  Table_Aevents_Row_Name : constant String := "AEVENTS_ROW";

  --
  -- Column names as strings
  --

  Eventid_Name : constant String := "EVENTID";
  Eventname_Name : constant String := "EVENTNAME";
  Countrycode_Name : constant String := "COUNTRYCODE";
  Timezone_Name : constant String := "TIMEZONE";
  Opents_Name : constant String := "OPENTS";
  Eventtypeid_Name : constant String := "EVENTTYPEID";
  Ixxlupd_Name : constant String := "IXXLUPD";
  Ixxluts_Name : constant String := "IXXLUTS";
  --
  -- Column names as enumerator literals
  --

  type Column_Type is (
    Eventid,
    Eventname,
    Countrycode,
    Timezone,
    Opents,
    Eventtypeid,
    Ixxlupd,
    Ixxluts);
  --
  -- The type definition
  --

  type Data_Type is new Table_Utils.Root_Table_Type with record
    Eventid : String(1 .. 11) := (others => ' ') ; -- Primary Key
    Eventname : String(1 .. 50) := (others => ' ') ; 
    Countrycode : String(1 .. 2) := (others => ' ') ; -- non unique index 2
    Timezone : String(1 .. 50) := (others => ' ') ; 
    Opents : Time_Type := Time_Type_First ; -- non unique index 3
    Eventtypeid : Integer_4 := 0 ; -- non unique index 4
    Ixxlupd : String(1 .. 15) := (others => ' ') ; 
    Ixxluts : Time_Type := Time_Type_First ; -- non unique index 5
  end record;


  -- Procedures for all DBMS

  -- Procedures for DBMS SQL
  -- Primary key
  function Get(Stm : in Sql.Statement_Type) return Table_Aevents.Data_Type;
  --------------------------------------------
  -- Primary key
  procedure Read(Data       : in out Table_Aevents.Data_Type;
                 End_Of_Set : in out Boolean);
  --------------------------------------------
  -- Primary key
  function Is_Existing(
                       Eventid : String) 
                           return Boolean;
  --------------------------------------------
  -- Primary key
  function Get(
                       Eventid : String)
                           return Table_Aevents.Data_Type;
  --------------------------------------------
  -- Primary key
  procedure Delete(Data : in Table_Aevents.Data_Type);
  --------------------------------------------
  -- Primary key
  procedure Update(Data : in out Table_Aevents.Data_Type; Keep_Timestamp : in Boolean := False);
  --------------------------------------------
  -- Primary key
  procedure Insert(Data : in out Table_Aevents.Data_Type; Keep_Timestamp : in Boolean := False);
  --------------------------------------------
  -- Primary key
  procedure Delete_Withcheck(Data : in Table_Aevents.Data_Type);
  --------------------------------------------
  -- Primary key
  procedure Update_Withcheck(Data : in out Table_Aevents.Data_Type; Keep_Timestamp : in Boolean := False);
  --------------------------------------------
   -- stop Print_Def_Functions_Spec.Primary_Procs_Spec


  -- non unique index
  procedure Read_One_Countrycode(
                           Data       : in out Table_Aevents.Data_Type;
                           Order      : in     Boolean := False;
                           End_Of_Set : in out Boolean);
  --------------------------------------------

  -- non unique index
  function Count_Countrycode(Data : Table_Aevents.Data_Type) return Integer_4;
  --------------------------------------------

  -- non unique index
  procedure Delete_Countrycode(Data  : in     Table_Aevents.Data_Type);
  --------------------------------------------

  -- non unique index
  function Is_Existing_I2(Countrycode : in String) return Boolean;
  --------------------------------------------




  -- non unique index
  procedure Read_One_Opents(
                           Data       : in out Table_Aevents.Data_Type;
                           Order      : in     Boolean := False;
                           End_Of_Set : in out Boolean);
  --------------------------------------------

  -- non unique index
  function Count_Opents(Data : Table_Aevents.Data_Type) return Integer_4;
  --------------------------------------------

  -- non unique index
  procedure Delete_Opents(Data  : in     Table_Aevents.Data_Type);
  --------------------------------------------

  -- non unique index
  function Is_Existing_I3(Opents : in Time_Type) return Boolean;
  --------------------------------------------




  -- non unique index
  procedure Read_One_Eventtypeid(
                           Data       : in out Table_Aevents.Data_Type;
                           Order      : in     Boolean := False;
                           End_Of_Set : in out Boolean);
  --------------------------------------------

  -- non unique index
  function Count_Eventtypeid(Data : Table_Aevents.Data_Type) return Integer_4;
  --------------------------------------------

  -- non unique index
  procedure Delete_Eventtypeid(Data  : in     Table_Aevents.Data_Type);
  --------------------------------------------

  -- non unique index
  function Is_Existing_I4(Eventtypeid : in Integer_4) return Boolean;
  --------------------------------------------




  -- non unique index
  procedure Read_One_Ixxluts(
                           Data       : in out Table_Aevents.Data_Type;
                           Order      : in     Boolean := False;
                           End_Of_Set : in out Boolean);
  --------------------------------------------

  -- non unique index
  function Count_Ixxluts(Data : Table_Aevents.Data_Type) return Integer_4;
  --------------------------------------------

  -- non unique index
  procedure Delete_Ixxluts(Data  : in     Table_Aevents.Data_Type);
  --------------------------------------------

  -- non unique index
  function Is_Existing_I5(Ixxluts : in Time_Type) return Boolean;
  --------------------------------------------






  -- Procedures for all DBMS, primitives

  function To_String(Data : in Table_Aevents.Data_Type) return String;

  function To_JSON(Data : in Table_Aevents.Data_Type) return JSON_Value;

  function From_JSON(JSON_Data : in JSON_Value) return Table_Aevents.Data_Type;

  function To_Xml(Data      : in Table_Aevents.Data_Type;
                  Ret_Start : in Boolean;
                  Ret_Data  : in Boolean;
                  Ret_End   : in Boolean) return String;


  package Aevents_List_Pack2 is new Ada.Containers.Doubly_Linked_Lists(Table_Aevents.Data_Type);

  subtype Key_Type is String(1..15);

  package Aevents_Map_Pack_String is new Ada.Containers.Hashed_Maps(
      Key_Type,
      Unbounded_String,
      Ada.Strings.Hash,
      "=",
      "=");

  package Aevents_Map_Pack_Column_Type is new Ada.Containers.Ordered_Maps(
      Column_Type,
      Unbounded_String,
      "<",
      "=");




  function To_Map (Data : Table_Aevents.Data_Type'class) return Table_Aevents.Aevents_Map_Pack_String.Map;


  function To_Map (Data : Table_Aevents.Data_Type'class) return Table_Aevents.Aevents_Map_Pack_Column_Type.Map;

  --------------------------------------------

  --------------------------------------------

  procedure Read_List(Stm  : in     Sql.Statement_Type;
                      List : in out Aevents_List_Pack2.List;
                      Max  : in     Integer_4 := Integer_4'Last);

  --------------------------------------------


  procedure Read_All(List  : in out Aevents_List_Pack2.List;
                     Order : in     Boolean := False;
                     Max   : in     Integer_4 := Integer_4'Last);
  --------------------------------------------




  procedure Read_Countrycode(
                           Data  : in out Table_Aevents.Data_Type'class;
                           List  : in out Aevents_List_Pack2.List;
                           Order : in     Boolean := False;
                           Max   : in     Integer_4 := Integer_4'Last);







  procedure Read_Opents(
                           Data  : in out Table_Aevents.Data_Type'class;
                           List  : in out Aevents_List_Pack2.List;
                           Order : in     Boolean := False;
                           Max   : in     Integer_4 := Integer_4'Last);







  procedure Read_Eventtypeid(
                           Data  : in out Table_Aevents.Data_Type'class;
                           List  : in out Aevents_List_Pack2.List;
                           Order : in     Boolean := False;
                           Max   : in     Integer_4 := Integer_4'Last);







  procedure Read_Ixxluts(
                           Data  : in out Table_Aevents.Data_Type'class;
                           List  : in out Aevents_List_Pack2.List;
                           Order : in     Boolean := False;
                           Max   : in     Integer_4 := Integer_4'Last);






  -- Procedures for all DBMS, others 

  procedure From_Xml(Xml_Filename : in Unbounded_String;
                     A_List       : in out Aevents_List_Pack2.List);


  Empty_Data : Table_Aevents.Data_Type;
end Table_Aevents ;
