
-----------------------------------------------------
-- This file is AUTOGENERATED by                     
-- repo                                              
--                                                   
----CHANGES HERE WILL BE LOST NEXT GENERATE!!!!----- 
-----------DO NOT EDIT THIS FILE!!!!---------------- 
-----------------------------------------------------




pragma Warnings(Off);
with Process_Io, Utils;
with Ada.Strings.Fixed; use Ada.Strings.Fixed;
with Sax.Readers;              use Sax.Readers;
with Input_Sources.File;       use Input_Sources.File;
with Unicode.CES;
with Unicode.Encodings;
with Sax.Attributes;



package body Table_Arunners is

  Stm_Select,
  Stm_Delete,
  Stm_Update,
  Stm_Insert,
  Stm_Select_All,
  Stm_Select_All_O  : Sql.Statement_Type;


  Stm_Delete_With_Check,
  Stm_Update_With_Check  : Sql.Statement_Type;


  -- Primary keys, when several fields
  Stm_Select_I1_Marketid,
  Stm_Select_I1_Marketid_O,
  Stm_Delete_I1_Marketid : Sql.Statement_Type; 

  -- Primary keys, when several fields
  Stm_Select_I1_Marketid_Selectionid,
  Stm_Select_I1_Marketid_Selectionid_O,
  Stm_Delete_I1_Marketid_Selectionid : Sql.Statement_Type; 

  -- non unique index all fields
  Stm_Delete_Marketid_Selectionid: Sql.Statement_Type;

  -- non unique index 
  Stm_Select_Count_I2_Runnernamestripped,
  Stm_Select_I2_Runnernamestripped,
  Stm_Delete_I2_Runnernamestripped,
  Stm_Select_I2_Runnernamestripped_O : Sql.Statement_Type;

  -- non unique index 
  Stm_Select_Count_I3_Marketid,
  Stm_Select_I3_Marketid,
  Stm_Delete_I3_Marketid,
  Stm_Select_I3_Marketid_O : Sql.Statement_Type;

  -- non unique index 
  Stm_Select_Count_I3_Marketid_Status,
  Stm_Select_I3_Marketid_Status,
  Stm_Delete_I3_Marketid_Status,
  Stm_Select_I3_Marketid_Status_O : Sql.Statement_Type;

  -- non unique index all fields
  Stm_Delete_Marketid_Status: Sql.Statement_Type;

  -- non unique index 
  Stm_Select_Count_I4_Status,
  Stm_Select_I4_Status,
  Stm_Delete_I4_Status,
  Stm_Select_I4_Status_O : Sql.Statement_Type;

  -- non unique index 
  Stm_Select_Count_I5_Ixxluts,
  Stm_Select_I5_Ixxluts,
  Stm_Delete_I5_Ixxluts,
  Stm_Select_I5_Ixxluts_O : Sql.Statement_Type;



  -- Procedures for all DBMS

  -- Procedures for DBMS SQL
  -- Primary key

  function Get(Stm : in Sql.Statement_Type) return Table_Arunners.Data_Type is
    Data : Table_Arunners.Data_Type;
  begin
    Stm.Get("MARKETID", Data.Marketid);
    Stm.Get("SELECTIONID", Data.Selectionid);
    Stm.Get("SORTPRIO", Data.Sortprio);
    Stm.Get("STATUS", Data.Status);
    Stm.Get("HANDICAP", Data.Handicap);
    Stm.Get("RUNNERNAME", Data.Runnername);
    if not Stm.Is_Null("RUNNERNAMESTRIPPED") then
      Stm.Get("RUNNERNAMESTRIPPED", Data.Runnernamestripped);
    else
      Data.Runnernamestripped :=  (others => ' ');
    end if;
    if not Stm.Is_Null("RUNNERNAMENUM") then
      Stm.Get("RUNNERNAMENUM", Data.Runnernamenum);
    else
      Data.Runnernamenum :=  (others => ' ');
    end if;
    Stm.Get("IXXLUPD", Data.Ixxlupd);
    Stm.Get_Timestamp("IXXLUTS", Data.Ixxluts);

    return Data;
  end Get;
---------------------------------------------


  function Get(
                  Marketid : String;
                  Selectionid : Integer_4) return Table_Arunners.Data_Type is
    Data       : Table_Arunners.Data_Type;
    End_Of_Set : Boolean := True;
  begin
    Data.Marketid := Marketid;
    Data.Selectionid := Selectionid;
    Data.Read(End_Of_Set);
    return Data;
  end Get;



  procedure Read_All(List  : in out Arunners_List_Pack2.List;
                     Order : in     Boolean := False;
                     Max   : in     Integer_4 := Integer_4'Last) is
    use Sql;
    Start_Trans   : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction   : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;
    if Order then
      Stm_Select_All_O.Prepare("select * from ARUNNERS order by " &
                  "MARKETID, " &
                  "SELECTIONID");
      Read_List(Stm_Select_All_O, List, Max);
    else
      Stm_Select_All.Prepare("select * from ARUNNERS");
      Read_List(Stm_Select_All, List, Max);
    end if;
    if Start_Trans then Transaction.Commit; end if;
  end Read_All;


  procedure Read_List(Stm   : in     Sql.Statement_Type;
                      List  : in out Arunners_List_Pack2.List;
                      Max   : in     Integer_4 := Integer_4'Last) is
    use Sql;
    Start_Trans  : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction  : Sql.Transaction_Type;
    Count        : Integer_4 := 0;
    Data         : Table_Arunners.Data_Type;
    Eos          : Boolean := False;
  begin
    if Start_Trans then Transaction.Start; end if;
    Stm.Open_Cursor;
    loop
      Stm.Fetch(Eos);
      exit when Eos or Count > Max;
      Data := Get(Stm);
      List.Append(Data);
      Count := Count +1;
    end loop;
    Stm.Close_Cursor;
    if Start_Trans then Transaction.Commit; end if;
  end Read_List;


  function Is_Existing(
                  Marketid : String;
                  Selectionid : Integer_4) return Boolean is
    Data       : Table_Arunners.Data_Type;
    End_Of_Set : Boolean := True;
  begin
    Data.Marketid := Marketid;
    Data.Selectionid := Selectionid;
    Read(Data, End_Of_Set);
    return not End_Of_Set;
  end Is_Existing;


  procedure Read(Data       : in out Table_Arunners.Data_Type;
                 End_Of_Set : in out Boolean) is
    use Sql;
    Start_Trans   : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction   : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;
    Stm_Select.Prepare("select * from ARUNNERS " &
                "where MARKETID =:MARKETID " &
                "and SELECTIONID =:SELECTIONID " &
            "");
    Stm_Select.Set("MARKETID", Data.Marketid);
    Stm_Select.Set("SELECTIONID", Data.Selectionid);
    Stm_Select.Open_Cursor;
    Stm_Select.Fetch(End_Of_Set);
    if not End_Of_Set then
      Data := Get(Stm_Select);
    end if;
    Stm_Select.Close_Cursor;
    if Start_Trans then Transaction.Commit; end if;
  end Read;

  procedure Delete(Data : in Table_Arunners.Data_Type) is
  begin
    Stm_Delete.Prepare("delete from ARUNNERS " &
                "where MARKETID =:MARKETID " &
                "and SELECTIONID =:SELECTIONID " &
            "");
    Stm_Delete.Set("MARKETID", Data.Marketid);
    Stm_Delete.Set("SELECTIONID", Data.Selectionid);
    Stm_Delete.Execute;
  end Delete;

  procedure Update(Data : in out Table_Arunners.Data_Type ; Keep_Timestamp : in Boolean := False) is
    Now     : Calendar2.Time_Type := Calendar2.Clock;
    Process : Process_Io.Process_Type     := Process_Io.This_Process;
  begin
    Stm_Update.Prepare("update ARUNNERS set  " &
            "SORTPRIO=:SORTPRIO, " &
            "STATUS=:STATUS, " &
            "HANDICAP=:HANDICAP, " &
            "RUNNERNAME=:RUNNERNAME, " &
            "RUNNERNAMESTRIPPED=:RUNNERNAMESTRIPPED, " &
            "RUNNERNAMENUM=:RUNNERNAMENUM, " &
            "IXXLUPD=:IXXLUPD, " &
            "IXXLUTS=:IXXLUTS " &
            "where MARKETID=:MARKETID " &
            "and SELECTIONID=:SELECTIONID " &
            "");

    if not Keep_Timestamp then
      Data.Ixxluts := Now;
    end if;
      Stm_Update.Set("SORTPRIO", Data.Sortprio);
      Stm_Update.Set("STATUS", Data.Status);
      Stm_Update.Set("HANDICAP", Data.Handicap);
      Stm_Update.Set("RUNNERNAME", Data.Runnername);
    if Data.Runnernamestripped = (Data.runnernamestripped'range => ' ') then
      Stm_Update.Set_Null("RUNNERNAMESTRIPPED");
    else
      Stm_Update.Set("RUNNERNAMESTRIPPED", Data.Runnernamestripped);
    end if;
    if Data.Runnernamenum = (Data.runnernamenum'range => ' ') then
      Stm_Update.Set_Null("RUNNERNAMENUM");
    else
      Stm_Update.Set("RUNNERNAMENUM", Data.Runnernamenum);
    end if;
    if not Keep_Timestamp then
      null; --for tables without Ixxlupd
      Data.Ixxlupd := Process.Name(1..15);
    end if;
      Stm_Update.Set("IXXLUPD", Data.Ixxlupd);
      Stm_Update.Set_Timestamp("IXXLUTS", Data.Ixxluts);
    Stm_Update.Set("MARKETID", Data.Marketid);
    Stm_Update.Set("SELECTIONID", Data.Selectionid);
    Stm_Update.Execute;
  end Update;

  procedure Insert(Data : in out Table_Arunners.Data_Type; Keep_Timestamp : in Boolean := False) is
    Now     : Calendar2.Time_Type := Calendar2.Clock;
    Process : Process_Io.Process_Type     := Process_Io.This_Process;
  begin
    if not Keep_Timestamp then
      Data.Ixxluts := Now;
    end if;
    Stm_Insert.Prepare("insert into ARUNNERS values (" &
         ":MARKETID," &
         ":SELECTIONID," &
         ":SORTPRIO," &
         ":STATUS," &
         ":HANDICAP," &
         ":RUNNERNAME," &
         ":RUNNERNAMESTRIPPED," &
         ":RUNNERNAMENUM," &
         ":IXXLUPD," &
         ":IXXLUTS)");

    if not Keep_Timestamp then
      Data.Ixxluts := Now;
    end if;
      Stm_Insert.Set("MARKETID", Data.Marketid);
      Stm_Insert.Set("SELECTIONID", Data.Selectionid);
      Stm_Insert.Set("SORTPRIO", Data.Sortprio);
      Stm_Insert.Set("STATUS", Data.Status);
      Stm_Insert.Set("HANDICAP", Data.Handicap);
      Stm_Insert.Set("RUNNERNAME", Data.Runnername);
  -- call  not boolean
    if Data.Runnernamestripped = (Data.runnernamestripped'range => ' ') then
      Stm_Insert.Set_Null("RUNNERNAMESTRIPPED");
    else
      Stm_Insert.Set("RUNNERNAMESTRIPPED", Data.Runnernamestripped);
    end if;
  -- call  not boolean
    if Data.Runnernamenum = (Data.runnernamenum'range => ' ') then
      Stm_Insert.Set_Null("RUNNERNAMENUM");
    else
      Stm_Insert.Set("RUNNERNAMENUM", Data.Runnernamenum);
    end if;
    if not Keep_Timestamp then
      null; --for tables without Ixxlupd
      Data.Ixxlupd := Process.Name(1..15);
    end if;
      Stm_Insert.Set("IXXLUPD", Data.Ixxlupd);
      Stm_Insert.Set_Timestamp("IXXLUTS", Data.Ixxluts);
    Stm_Insert.Execute;
  end Insert;
--------------------------------------------
  procedure Delete_Withcheck(Data : in Table_Arunners.Data_Type) is
  begin
    Stm_Delete_With_Check.Prepare("delete from ARUNNERS " &
                "where MARKETID =:MARKETID " &
                "and SELECTIONID =:SELECTIONID " &
            "and IXXLUPD = :IXXLUPD " &
            "and IXXLUTS = :IXXLUTS " &
            "");
    Stm_Delete_With_Check.Set("MARKETID", Data.Marketid);
    Stm_Delete_With_Check.Set("SELECTIONID", Data.Selectionid);
    Stm_Delete_With_Check.Set("IXXLUPD", Data.Ixxlupd);
    Stm_Delete_With_Check.Set_Timestamp("IXXLUTS", Data.Ixxluts);
    Stm_Delete_With_Check.Execute;
  end Delete_Withcheck;
--------------------------------------------
  procedure Update_Withcheck(Data : in out Table_Arunners.Data_Type; Keep_Timestamp : in Boolean := False) is
    Now     : Calendar2.Time_Type := Calendar2.Clock;
    Process : Process_Io.Process_Type     := Process_Io.This_Process;
  begin
    Stm_Update_With_Check.Prepare("update ARUNNERS set  " &
            "SORTPRIO=:SORTPRIO, " &
            "STATUS=:STATUS, " &
            "HANDICAP=:HANDICAP, " &
            "RUNNERNAME=:RUNNERNAME, " &
            "RUNNERNAMESTRIPPED=:RUNNERNAMESTRIPPED, " &
            "RUNNERNAMENUM=:RUNNERNAMENUM, " &
            "IXXLUPD=:IXXLUPD, " &
            "IXXLUTS=:IXXLUTS " &
            "where MARKETID=:MARKETID " &
            "and SELECTIONID=:SELECTIONID " &
    "and IXXLUPD = :OLD_IXXLUPD " &
    "and IXXLUTS = :OLD_IXXLUTS " &
            "");
    Stm_Update_With_Check.Set("MARKETID", Data.Marketid);
    Stm_Update_With_Check.Set("SELECTIONID", Data.Selectionid);
    Stm_Update_With_Check.Set("OLD_IXXLUPD", Data.Ixxlupd );
    Stm_Update_With_Check.Set_Timestamp("OLD_IXXLUTS", Data.Ixxluts );

    if not Keep_Timestamp then
      Data.Ixxluts := Now;
    end if;
      Stm_Update_With_Check.Set("SORTPRIO", Data.Sortprio);
      Stm_Update_With_Check.Set("STATUS", Data.Status);
      Stm_Update_With_Check.Set("HANDICAP", Data.Handicap);
      Stm_Update_With_Check.Set("RUNNERNAME", Data.Runnername);
    if Data.Runnernamestripped = (Data.runnernamestripped'range => ' ') then
      Stm_Update_With_Check.Set_Null("RUNNERNAMESTRIPPED");
    else
      Stm_Update_With_Check.Set("RUNNERNAMESTRIPPED", Data.Runnernamestripped);
    end if;
    if Data.Runnernamenum = (Data.runnernamenum'range => ' ') then
      Stm_Update_With_Check.Set_Null("RUNNERNAMENUM");
    else
      Stm_Update_With_Check.Set("RUNNERNAMENUM", Data.Runnernamenum);
    end if;
    if not Keep_Timestamp then
      null; --for tables without Ixxlupd
      Data.Ixxlupd := Process.Name(1..15);
    end if;
      Stm_Update_With_Check.Set("IXXLUPD", Data.Ixxlupd);
      Stm_Update_With_Check.Set_Timestamp("IXXLUTS", Data.Ixxluts);
    Stm_Update_With_Check.Execute;
  end Update_Withcheck;
--------------------------------------------

  -- primary key index several fields
  procedure Delete_Marketid_Selectionid(Data  : in Table_Arunners.Data_Type) is
  begin
    Stm_Delete_Marketid_Selectionid.Prepare("delete from ARUNNERS " &
                "where MARKETID =:MARKETID " &
                "and SELECTIONID =:SELECTIONID " &
            "");
    Stm_Delete_Marketid_Selectionid.Set("MARKETID", Data.Marketid);
    Stm_Delete_Marketid_Selectionid.Set("SELECTIONID", Data.Selectionid);
    Stm_Delete_Marketid_Selectionid.Execute;
  end Delete_Marketid_Selectionid;
  --------------------------------------------


  -- part of primary key index
  procedure Delete_I1_Marketid(Data  : in     Table_Arunners.Data_Type) is
  begin
    Stm_Delete_I1_Marketid.Prepare("delete from ARUNNERS " &
                "where MARKETID =:MARKETID " &
            "");
    Stm_Delete_I1_Marketid.Set("MARKETID", Data.Marketid);
    Stm_Delete_I1_Marketid.Execute;
  end Delete_I1_Marketid;

  -- part of primary key index
  function Is_Existing_I1(
      Marketid : in String) return Boolean is
    Data       : Table_Arunners.Data_Type;
    Is_Exist   : Boolean := False;
    List       : Arunners_List_Pack2.List;
  begin
    Data.Marketid := Marketid;
    Read_I1_Marketid(Data, List, False, 1);
    Is_Exist := not List.Is_Empty;
    List.Clear;
    return Is_Exist;
  end Is_Existing_I1;

  -- part of primary key index
  procedure Delete_I1_Marketid_Selectionid(Data  : in     Table_Arunners.Data_Type) is
  begin
    Stm_Delete_I1_Marketid_Selectionid.Prepare("delete from ARUNNERS " &
                "where MARKETID =:MARKETID " &
                "and SELECTIONID =:SELECTIONID " &
            "");
    Stm_Delete_I1_Marketid_Selectionid.Set("MARKETID", Data.Marketid);
    Stm_Delete_I1_Marketid_Selectionid.Set("SELECTIONID", Data.Selectionid);
    Stm_Delete_I1_Marketid_Selectionid.Execute;
  end Delete_I1_Marketid_Selectionid;

  -- part of primary key index
  function Is_Existing_I1(
      Marketid : in String;
      Selectionid : in Integer_4) return Boolean is
    Data       : Table_Arunners.Data_Type;
    Is_Exist   : Boolean := False;
    List       : Arunners_List_Pack2.List;
  begin
    Data.Marketid := Marketid;
    Data.Selectionid := Selectionid;
    Read_I1_Marketid_Selectionid(Data, List, False, 1);
    Is_Exist := not List.Is_Empty;
    List.Clear;
    return Is_Exist;
  end Is_Existing_I1;


  -- non unique index
  procedure Read_One_Runnernamestripped(
                           Data       : in out Table_Arunners.Data_Type;
                           Order      : in     Boolean := False;
                           End_Of_Set : in out Boolean) is
    List : Arunners_List_Pack2.List;
  begin
    Data.Read_Runnernamestripped(List, Order, 1);
    if List.Is_Empty then
      End_Of_Set := True;
    else
      End_Of_Set := False;
      Data := List.First_Element;
    end if;
    List.Clear;
  end Read_One_Runnernamestripped;
  --------------------------------------------

  -- non unique index
  function Count_Runnernamestripped(Data : Table_Arunners.Data_Type) return Integer_4 is
    use Sql;
    Count       : Integer_4 := 0;
    End_Of_Set  : Boolean := False;
    Start_Trans : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;

    Stm_Select_Count_I2_Runnernamestripped.Prepare("select count('a') from ARUNNERS " &
                "where RUNNERNAMESTRIPPED =:RUNNERNAMESTRIPPED " &
            "");
    Stm_Select_Count_I2_Runnernamestripped.Set("RUNNERNAMESTRIPPED", Data.Runnernamestripped);

    Stm_Select_Count_I2_Runnernamestripped.Open_Cursor;
    Stm_Select_Count_I2_Runnernamestripped.Fetch(End_Of_Set);
    if not End_Of_Set then
      Stm_Select_Count_I2_Runnernamestripped.Get(1, Count);
    end if;
    Stm_Select_Count_I2_Runnernamestripped.Close_Cursor;
    if Start_Trans then Transaction.Commit; end if;
    return Count;
  end Count_Runnernamestripped;
  --------------------------------------------

  -- non unique index
  procedure Delete_Runnernamestripped(Data  : in     Table_Arunners.Data_Type) is
  begin

    Stm_Delete_I2_Runnernamestripped.Prepare("delete from ARUNNERS " &
                "where RUNNERNAMESTRIPPED =:RUNNERNAMESTRIPPED " &
            "");
    Stm_Delete_I2_Runnernamestripped.Set("RUNNERNAMESTRIPPED", Data.Runnernamestripped);

    Stm_Delete_I2_Runnernamestripped.Execute;
  end Delete_Runnernamestripped;

  --------------------------------------------

  -- non unique index
  function Is_Existing_I2(Runnernamestripped : in String) return Boolean is
    Data       : Table_Arunners.Data_Type;
    Exists     : Boolean := False;
    List       : Arunners_List_Pack2.List;
  begin
    Data.Runnernamestripped := Runnernamestripped;
    Read_Runnernamestripped(Data, List, False, 1);
    Exists := not List.Is_Empty;
    List.Clear;
    return Exists;
  end Is_Existing_I2;
  --------------------------------------------




  -- non unique index
  procedure Delete_Marketid_Status(Data  : in     Table_Arunners.Data_Type) is
  begin
    Stm_Delete_Marketid_Status.Prepare("delete from ARUNNERS " &
                "where MARKETID =:MARKETID " &
                "and STATUS =:STATUS " &
            "");
    Stm_Delete_Marketid_Status.Set("MARKETID", Data.Marketid);
    Stm_Delete_Marketid_Status.Set("STATUS", Data.Status);
    Stm_Delete_Marketid_Status.Execute;
  end Delete_Marketid_Status;

  --------------------------------------------


  procedure Read_One_Marketid_Status(
                           Data       : in out Table_Arunners.Data_Type;
                           Order      : in     Boolean := False;
                           End_Of_Set : in out Boolean) is
    List : Arunners_List_Pack2.List;
  begin
    Data.Read_Marketid_Status(List, Order, 1);
    if List.Is_Empty then
      End_Of_Set := True;
    else
      End_Of_Set := False;
      Data := List.First_Element;
    end if;
    List.Clear;
  end Read_One_Marketid_Status;


  -- non unique index
  procedure Delete_I3_Marketid(Data  : in     Table_Arunners.Data_Type) is
  begin
    Stm_Delete_I3_Marketid.Prepare("delete from ARUNNERS " &
                "where MARKETID =:MARKETID " &
            "");
    Stm_Delete_I3_Marketid.Set("MARKETID", Data.Marketid);
    Stm_Delete_I3_Marketid.Execute;
  end Delete_I3_Marketid;
  --------------------------------------------

  -- non unique index
  function Is_Existing_I3(
      Marketid : in String;
      Status : in String) return Boolean is
    Data       : Table_Arunners.Data_Type;
    Is_Exist   : Boolean := False;
    List       : Arunners_List_Pack2.List;
  begin
    Data.Marketid := Marketid;
    Data.Status := Status;
    Read_I3_Marketid_Status(Data, List, False, 1);
    Is_Exist := not List.Is_Empty;
    List.Clear;
    return Is_Exist;
  end Is_Existing_I3;
  --------------------------------------------


  -- non unique index
  procedure Delete_I3_Marketid_Status(Data  : in     Table_Arunners.Data_Type) is
  begin
    Stm_Delete_I3_Marketid_Status.Prepare("delete from ARUNNERS " &
                "where MARKETID =:MARKETID " &
                "and STATUS =:STATUS " &
            "");
    Stm_Delete_I3_Marketid_Status.Set("MARKETID", Data.Marketid);
    Stm_Delete_I3_Marketid_Status.Set("STATUS", Data.Status);
    Stm_Delete_I3_Marketid_Status.Execute;
  end Delete_I3_Marketid_Status;
  --------------------------------------------

  -- non unique index
  function Is_Existing_I3(
      Marketid : in String) return Boolean is
    Data       : Table_Arunners.Data_Type;
    Is_Exist   : Boolean := False;
    List       : Arunners_List_Pack2.List;
  begin
    Data.Marketid := Marketid;
    Read_I3_Marketid(Data, List, False, 1);
    Is_Exist := not List.Is_Empty;
    List.Clear;
    return Is_Exist;
  end Is_Existing_I3;
  --------------------------------------------



  -- non unique index
  procedure Read_One_Status(
                           Data       : in out Table_Arunners.Data_Type;
                           Order      : in     Boolean := False;
                           End_Of_Set : in out Boolean) is
    List : Arunners_List_Pack2.List;
  begin
    Data.Read_Status(List, Order, 1);
    if List.Is_Empty then
      End_Of_Set := True;
    else
      End_Of_Set := False;
      Data := List.First_Element;
    end if;
    List.Clear;
  end Read_One_Status;
  --------------------------------------------

  -- non unique index
  function Count_Status(Data : Table_Arunners.Data_Type) return Integer_4 is
    use Sql;
    Count       : Integer_4 := 0;
    End_Of_Set  : Boolean := False;
    Start_Trans : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;

    Stm_Select_Count_I4_Status.Prepare("select count('a') from ARUNNERS " &
                "where STATUS =:STATUS " &
            "");
    Stm_Select_Count_I4_Status.Set("STATUS", Data.Status);

    Stm_Select_Count_I4_Status.Open_Cursor;
    Stm_Select_Count_I4_Status.Fetch(End_Of_Set);
    if not End_Of_Set then
      Stm_Select_Count_I4_Status.Get(1, Count);
    end if;
    Stm_Select_Count_I4_Status.Close_Cursor;
    if Start_Trans then Transaction.Commit; end if;
    return Count;
  end Count_Status;
  --------------------------------------------

  -- non unique index
  procedure Delete_Status(Data  : in     Table_Arunners.Data_Type) is
  begin

    Stm_Delete_I4_Status.Prepare("delete from ARUNNERS " &
                "where STATUS =:STATUS " &
            "");
    Stm_Delete_I4_Status.Set("STATUS", Data.Status);

    Stm_Delete_I4_Status.Execute;
  end Delete_Status;

  --------------------------------------------

  -- non unique index
  function Is_Existing_I4(Status : in String) return Boolean is
    Data       : Table_Arunners.Data_Type;
    Exists     : Boolean := False;
    List       : Arunners_List_Pack2.List;
  begin
    Data.Status := Status;
    Read_Status(Data, List, False, 1);
    Exists := not List.Is_Empty;
    List.Clear;
    return Exists;
  end Is_Existing_I4;
  --------------------------------------------




  -- non unique index
  procedure Read_One_Ixxluts(
                           Data       : in out Table_Arunners.Data_Type;
                           Order      : in     Boolean := False;
                           End_Of_Set : in out Boolean) is
    List : Arunners_List_Pack2.List;
  begin
    Data.Read_Ixxluts(List, Order, 1);
    if List.Is_Empty then
      End_Of_Set := True;
    else
      End_Of_Set := False;
      Data := List.First_Element;
    end if;
    List.Clear;
  end Read_One_Ixxluts;
  --------------------------------------------

  -- non unique index
  function Count_Ixxluts(Data : Table_Arunners.Data_Type) return Integer_4 is
    use Sql;
    Count       : Integer_4 := 0;
    End_Of_Set  : Boolean := False;
    Start_Trans : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;

    Stm_Select_Count_I5_Ixxluts.Prepare("select count('a') from ARUNNERS " &
                "where IXXLUTS =:IXXLUTS " &
            "");
    Stm_Select_Count_I5_Ixxluts.Set_Timestamp("IXXLUTS", Data.Ixxluts);

    Stm_Select_Count_I5_Ixxluts.Open_Cursor;
    Stm_Select_Count_I5_Ixxluts.Fetch(End_Of_Set);
    if not End_Of_Set then
      Stm_Select_Count_I5_Ixxluts.Get(1, Count);
    end if;
    Stm_Select_Count_I5_Ixxluts.Close_Cursor;
    if Start_Trans then Transaction.Commit; end if;
    return Count;
  end Count_Ixxluts;
  --------------------------------------------

  -- non unique index
  procedure Delete_Ixxluts(Data  : in     Table_Arunners.Data_Type) is
  begin

    Stm_Delete_I5_Ixxluts.Prepare("delete from ARUNNERS " &
                "where IXXLUTS =:IXXLUTS " &
            "");
    Stm_Delete_I5_Ixxluts.Set_Timestamp("IXXLUTS", Data.Ixxluts);

    Stm_Delete_I5_Ixxluts.Execute;
  end Delete_Ixxluts;

  --------------------------------------------

  -- non unique index
  function Is_Existing_I5(Ixxluts : in Time_Type) return Boolean is
    Data       : Table_Arunners.Data_Type;
    Exists     : Boolean := False;
    List       : Arunners_List_Pack2.List;
  begin
    Data.Ixxluts := Ixxluts;
    Read_Ixxluts(Data, List, False, 1);
    Exists := not List.Is_Empty;
    List.Clear;
    return Exists;
  end Is_Existing_I5;
  --------------------------------------------





  -- Procedures for all DBMS


  function To_String(Data : in Table_Arunners.Data_Type) return String is
  begin
    return
          "Marketid = " & Utils.Trim(Data.Marketid) & " " &
          "Selectionid = " & Utils.Trim(Data.Selectionid'Img) & " " &
          "Sortprio = " & Utils.Trim(Data.Sortprio'Img) & " " &
          "Status = " & Utils.Trim(Data.Status) & " " &
          "Handicap = " & Utils.F8_Image(Data.Handicap) & " " &
          "Runnername = " & Utils.Trim(Data.Runnername) & " " &
          "Runnernamestripped = " & Utils.Trim(Data.Runnernamestripped) & " " &
          "Runnernamenum = " & Utils.Trim(Data.Runnernamenum) & " " &
          "Ixxlupd = " & Utils.Trim(Data.Ixxlupd) & " " &
          "Ixxluts = " & Calendar2.String_Date_And_Time(Data.Ixxluts, Milliseconds => True ) & " " &
          "";
  end To_String;

  function To_JSON(Data : in Table_Arunners.Data_Type) return JSON_Value is
    Json_Data : JSON_Value := Create_Object;
  begin
    Json_Data.Set_Field(Field_Name => "marketid", Field => Utils.Trim(Data.Marketid));
    Json_Data.Set_Field(Field_Name => "selectionid", Field => Long_Integer(Data.Selectionid));
    Json_Data.Set_Field(Field_Name => "sortprio", Field => Long_Integer(Data.Sortprio));
    Json_Data.Set_Field(Field_Name => "status", Field => Utils.Trim(Data.Status));
    Json_Data.Set_Field(Field_Name => "handicap", Field => Float(Data.Handicap));
    Json_Data.Set_Field(Field_Name => "runnername", Field => Utils.Trim(Data.Runnername));
    Json_Data.Set_Field(Field_Name => "runnernamestripped", Field => Utils.Trim(Data.Runnernamestripped));
    Json_Data.Set_Field(Field_Name => "runnernamenum", Field => Utils.Trim(Data.Runnernamenum));
    Json_Data.Set_Field(Field_Name => "ixxlupd", Field => Utils.Trim(Data.Ixxlupd));
    Json_Data.Set_Field(Field_Name => "ixxluts", Field => Data.Ixxluts.To_String);
    return Json_Data;
  end To_JSON;

  function From_JSON(JSON_Data : in JSON_Value) return Table_Arunners.Data_Type is
    use Ada.Strings;
    Data : Table_Arunners.Data_Type;
  begin
    if JSON_Data.Has_Field("marketid") then
      Move( Source => JSON_Data.Get("marketid"), Target => Data.Marketid , Drop => Right);
    end if;

    if JSON_Data.Has_Field("selectionid") then
      declare
        Tmp : Long_Integer := 0;
      begin
        Tmp := JSON_Data.Get("selectionid");
        Data.Selectionid := Integer_4(Tmp);
      end;
    end if;

    if JSON_Data.Has_Field("sortprio") then
      declare
        Tmp : Long_Integer := 0;
      begin
        Tmp := JSON_Data.Get("sortprio");
        Data.Sortprio := Integer_4(Tmp);
      end;
    end if;

    if JSON_Data.Has_Field("status") then
      Move( Source => JSON_Data.Get("status"), Target => Data.Status , Drop => Right);
    end if;

    if JSON_Data.Has_Field("handicap") then
      declare
        Tmp : Float := 0.0;
      begin
        Tmp := JSON_Data.Get("handicap");
        Data.Handicap := Fixed_Type(Tmp);
      end;
    end if;

    if JSON_Data.Has_Field("runnername") then
      Move( Source => JSON_Data.Get("runnername"), Target => Data.Runnername , Drop => Right);
    end if;

    if JSON_Data.Has_Field("runnernamestripped") then
      Move( Source => JSON_Data.Get("runnernamestripped"), Target => Data.Runnernamestripped , Drop => Right);
    end if;

    if JSON_Data.Has_Field("runnernamenum") then
      Move( Source => JSON_Data.Get("runnernamenum"), Target => Data.Runnernamenum , Drop => Right);
    end if;

    if JSON_Data.Has_Field("ixxlupd") then
      Move( Source => JSON_Data.Get("ixxlupd"), Target => Data.Ixxlupd , Drop => Right);
    end if;

    if JSON_Data.Has_Field("ixxluts") then
      declare
        Tmp : String := JSON_Data.Get("ixxluts");
      begin  -- "marketStartTime":"2013-06-22T17:39:00.000Z"
        Data.Ixxluts := Calendar2.To_Time_Type(Tmp(1..10), Tmp(12..23));
      end;
    end if;

    return Data;
  end From_JSON;

  function To_Xml(Data      : in Table_Arunners.Data_Type;
                  Ret_Start : in Boolean;
                  Ret_Data  : in Boolean;
                  Ret_End   : in Boolean) return String is
    Ls      : constant String := "";
    S_Start : constant String := "<ARUNNERS_ROW>" & Ls;
    S_End   : constant String := "</ARUNNERS_ROW>" & Ls;
    S1 : constant String :=
          "<MARKETID>" & Utils.Trim(Data.Marketid) & "</MARKETID>" & Ls;
    S2 : constant String :=
          "<SELECTIONID>" & Utils.Trim(Data.Selectionid'Img) & "</SELECTIONID>" & Ls;
    S3 : constant String :=
          "<SORTPRIO>" & Utils.Trim(Data.Sortprio'Img) & "</SORTPRIO>" & Ls;
    S4 : constant String :=
          "<STATUS>" & Utils.Trim(Data.Status) & "</STATUS>" & Ls;
    S5 : constant String :=
          "<HANDICAP>" & Utils.F8_Image(Data.Handicap) & "</HANDICAP>" & Ls;
    S6 : constant String :=
          "<RUNNERNAME>" & Utils.Trim(Data.Runnername) & "</RUNNERNAME>" & Ls;
    S7 : constant String :=
          "<RUNNERNAMESTRIPPED>" & Utils.Trim(Data.Runnernamestripped) & "</RUNNERNAMESTRIPPED>" & Ls;
    S8 : constant String :=
          "<RUNNERNAMENUM>" & Utils.Trim(Data.Runnernamenum) & "</RUNNERNAMENUM>" & Ls;
    S9 : constant String :=
          "<IXXLUPD>" & Utils.Trim(Data.Ixxlupd) & "</IXXLUPD>" & Ls;
    S10 : constant String :=
          "<IXXLUTS>" & Calendar2.String_Date_And_Time(Data.Ixxluts, Milliseconds => True) & "</IXXLUTS>" & Ls;
    --------------------------------
    function Get_String(S : in String; Ret : in Boolean) return String is
    begin
      if Ret then return S; else return ""; end if;
    end Get_String;
    --------------------------------
  begin
    return Get_String(S_Start, Ret_Start) & 
           Get_String(
                       S1 &  S2 &  S3 &  S4 &  S5 &  S6 &  S7 &  S8 &  S9 &  S10 , Ret_Data) &
           Get_String(S_End, Ret_End) & Ascii.LF;
  end To_Xml;
    --------------------------------

  --------------------------------------------
  type Arunners_Reader is new Sax.Readers.Reader with record
    Current_Tag    : Unbounded_String := Null_Unbounded_String;
    Accumulated    : Unbounded_String := Null_Unbounded_String;
    OK             : Boolean := True;
    Found_Set      : Boolean := True;
    Arunners_List     : Table_Arunners.Arunners_List_Pack2.List;
    Arunners_Data     : Table_Arunners.Data_Type := Empty_Data;
  end record;

  overriding procedure Start_Element(Handler       : in out Arunners_Reader;
                                     Namespace_URI : Unicode.CES.Byte_Sequence := "";
                                     Local_Name    : Unicode.CES.Byte_Sequence := "";
                                     Qname         : Unicode.CES.Byte_Sequence := "";
                                     Atts          : Sax.Attributes.Attributes'Class);

  overriding procedure End_Element(Handler         : in out Arunners_Reader;
                                   Namespace_URI   : Unicode.CES.Byte_Sequence := "";
                                   Local_Name      : Unicode.CES.Byte_Sequence := "";
                                   Qname           : Unicode.CES.Byte_Sequence := "");

  overriding procedure Characters(Handler          : in out Arunners_Reader;
                                  Ch               : Unicode.CES.Byte_Sequence := "");

  --------------------------------------------
  overriding procedure Start_Element(Handler       : in out Arunners_Reader;
                          Namespace_URI : Unicode.CES.Byte_Sequence := "";
                          Local_Name    : Unicode.CES.Byte_Sequence := "";
                          Qname         : Unicode.CES.Byte_Sequence := "";
                          Atts          : Sax.Attributes.Attributes'Class) is
    pragma Warnings(Off,Namespace_URI);
    pragma Warnings(Off,Qname);
    pragma Warnings(Off,Atts);
    The_Tag : constant String := Local_Name;
  begin
    Handler.Current_Tag := To_Unbounded_String(The_Tag);
    Handler.Accumulated := Null_Unbounded_String;
    if The_Tag = Table_Arunners_Set_Name then
      Handler.Found_Set := True;
    end if;
  exception
    when Ada.Strings.Length_Error => Handler.OK := False;
    when Constraint_Error         => Handler.OK := False;
  end Start_Element;
  --------------------------------------------

  --------------------------------------------
  overriding procedure End_Element(Handler       : in out Arunners_Reader;
                        Namespace_URI : Unicode.CES.Byte_Sequence := "";
                        Local_Name    : Unicode.CES.Byte_Sequence := "";
                        Qname         : Unicode.CES.Byte_Sequence := "") is
    pragma Warnings(Off,Namespace_URI);
    pragma Warnings(Off,Qname);
    The_Tag : constant String := Local_Name;
  begin
    if The_Tag = Table_Arunners_Set_Name then
      Handler.Found_Set := False;
    elsif The_Tag = Table_Arunners_Row_Name then
      if Handler.Found_Set then
        Handler.Arunners_List.Append(Handler.Arunners_Data);
        Handler.Arunners_Data := Empty_Data;
      end if;
    end if;
  exception
    when Ada.Strings.Length_Error => Handler.OK := False;
  end End_Element;
  --------------------------------------------

  --------------------------------------------
  overriding procedure Characters(Handler          : in out Arunners_Reader;
                       Ch               : Unicode.CES.Byte_Sequence := "") is
    function To_Iso_Latin_15(Str : Unicode.CES.Byte_Sequence) return String is
      use Unicode.Encodings;
    begin
      return  Convert(Str, Get_By_Name("utf-8"), Get_By_Name("iso-8859-15"));
    end To_Iso_Latin_15;
    The_Tag   : constant String := To_String(Handler.Current_Tag);
    The_Value : constant String := To_Iso_Latin_15(Ch);
    procedure Fix_String (Value    : String;
                          Variable : in out String) is
    begin
      Append(Handler.Accumulated, Value);
      Ada.Strings.Fixed.Move(To_String(Handler.Accumulated), Variable);
    end Fix_String;
  begin
    if Handler.Found_Set then
      if The_Tag = Marketid_Name then
       Fix_String(The_Value, Handler.Arunners_Data.Marketid);
      elsif The_Tag = Selectionid_Name then
       Handler.Arunners_Data.Selectionid := Integer_4'value(The_Value);
      elsif The_Tag = Sortprio_Name then
       Handler.Arunners_Data.Sortprio := Integer_4'value(The_Value);
      elsif The_Tag = Status_Name then
       Fix_String(The_Value, Handler.Arunners_Data.Status);
      elsif The_Tag = Handicap_Name then
       Handler.Arunners_Data.Handicap := Fixed_Type'value(The_Value);
      elsif The_Tag = Runnername_Name then
       Fix_String(The_Value, Handler.Arunners_Data.Runnername);
      elsif The_Tag = Runnernamestripped_Name then
       Fix_String(The_Value, Handler.Arunners_Data.Runnernamestripped);
      elsif The_Tag = Runnernamenum_Name then
       Fix_String(The_Value, Handler.Arunners_Data.Runnernamenum);
      elsif The_Tag = Ixxlupd_Name then
       Fix_String(The_Value, Handler.Arunners_Data.Ixxlupd);
      elsif The_Tag = Ixxluts_Name then
       Handler.Arunners_Data.Ixxluts := Calendar2.To_Time_Type(The_Value(1..11), The_Value(13..24));
      end if;
    end if;
  exception
    when Ada.Strings.Length_Error => Handler.OK := False;
  end Characters;

  --------------------------------------------


  function To_Map (Data : Table_Arunners.Data_Type'class) return Table_Arunners.Arunners_Map_Pack_String.Map is
    Tmp_Map :  Table_Arunners.Arunners_Map_Pack_String.Map;
    Key : Key_Type := (others => ' ');
    Tmp_U_B_String : Unbounded_String := Null_Unbounded_String;
    Tmp_String     : String(1..1);
    pragma Warnings(Off, Tmp_String); -- used only if we have Character fields (ie String(1..1)
  begin
    Move("MARKETID", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Marketid);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("SELECTIONID", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Selectionid'Img);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("SORTPRIO", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Sortprio'Img);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("STATUS", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Status);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("HANDICAP", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Handicap'Img);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("RUNNERNAME", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Runnername);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("RUNNERNAMESTRIPPED", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Runnernamestripped);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("RUNNERNAMENUM", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Runnernamenum);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("IXXLUPD", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Ixxlupd);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("IXXLUTS", Key);
    Tmp_U_B_String := To_Unbounded_String(String_Date_And_Time(Data.Ixxluts));
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    return Tmp_Map;
  end To_Map;
 ---------------------------


  function To_Map (Data : Table_Arunners.Data_Type'class) return Table_Arunners.Arunners_Map_Pack_Column_Type.Map is
    Tmp_Map :  Table_Arunners.Arunners_Map_Pack_Column_Type.Map;
    Key : Column_Type;
    Tmp_U_B_String : Unbounded_String := Null_Unbounded_String;
    Tmp_String     : String(1..1);
    pragma Warnings(Off, Tmp_String); -- used only if we have Character fields (ie String(1..1)
  begin
    Key := Marketid;
    Tmp_U_B_String := To_Unbounded_String(Data.Marketid);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Selectionid;
    Tmp_U_B_String := To_Unbounded_String(Data.Selectionid'Img);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Sortprio;
    Tmp_U_B_String := To_Unbounded_String(Data.Sortprio'Img);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Status;
    Tmp_U_B_String := To_Unbounded_String(Data.Status);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Handicap;
    Tmp_U_B_String := To_Unbounded_String(Data.Handicap'Img);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Runnername;
    Tmp_U_B_String := To_Unbounded_String(Data.Runnername);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Runnernamestripped;
    Tmp_U_B_String := To_Unbounded_String(Data.Runnernamestripped);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Runnernamenum;
    Tmp_U_B_String := To_Unbounded_String(Data.Runnernamenum);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Ixxlupd;
    Tmp_U_B_String := To_Unbounded_String(Data.Ixxlupd);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Ixxluts;
    Tmp_U_B_String := To_Unbounded_String(String_Date_And_Time(Data.Ixxluts));
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    return Tmp_Map;
  end To_Map;
 ---------------------------
-------------------------------------------


  procedure Read_I1_Marketid(
                           Data  : in     Table_Arunners.Data_Type'class;
                           List  : in out Arunners_List_Pack2.List;
                           Order : in     Boolean := False;
                           Max   : in     Integer_4 := Integer_4'Last) is
    use Sql;
    Start_Trans : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;
    if Order then
    Stm_Select_I1_Marketid_O.Prepare("select * from ARUNNERS " &
                "where MARKETID =:MARKETID " &
            "order by " & 
            "MARKETID, " & 
            "SELECTIONID");
    Stm_Select_I1_Marketid_O.Set("MARKETID", Data.Marketid);
      Read_List(Stm_Select_I1_Marketid_O , List, Max);
    else
    Stm_Select_I1_Marketid.Prepare("select * from ARUNNERS " &
                "where MARKETID =:MARKETID " &
            "");
    Stm_Select_I1_Marketid.Set("MARKETID", Data.Marketid);
      Read_List(Stm_Select_I1_Marketid, List, Max);
    end if;
    if Start_Trans then Transaction.Commit; end if;
  end Read_I1_Marketid;
-------------------------------------------

-------------------------------------------


  procedure Read_I1_Marketid_Selectionid(
                           Data  : in     Table_Arunners.Data_Type'class;
                           List  : in out Arunners_List_Pack2.List;
                           Order : in     Boolean := False;
                           Max   : in     Integer_4 := Integer_4'Last) is
    use Sql;
    Start_Trans : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;
    if Order then
    Stm_Select_I1_Marketid_Selectionid_O.Prepare("select * from ARUNNERS " &
                "where MARKETID =:MARKETID " &
                "and SELECTIONID =:SELECTIONID " &
            "order by " & 
            "MARKETID, " & 
            "SELECTIONID");
    Stm_Select_I1_Marketid_Selectionid_O.Set("MARKETID", Data.Marketid);
    Stm_Select_I1_Marketid_Selectionid_O.Set("SELECTIONID", Data.Selectionid);
      Read_List(Stm_Select_I1_Marketid_Selectionid_O , List, Max);
    else
    Stm_Select_I1_Marketid_Selectionid.Prepare("select * from ARUNNERS " &
                "where MARKETID =:MARKETID " &
                "and SELECTIONID =:SELECTIONID " &
            "");
    Stm_Select_I1_Marketid_Selectionid.Set("MARKETID", Data.Marketid);
    Stm_Select_I1_Marketid_Selectionid.Set("SELECTIONID", Data.Selectionid);
      Read_List(Stm_Select_I1_Marketid_Selectionid, List, Max);
    end if;
    if Start_Trans then Transaction.Commit; end if;
  end Read_I1_Marketid_Selectionid;
-------------------------------------------



  procedure Read_Runnernamestripped(
                           Data  : in out Table_Arunners.Data_Type'class;
                           List  : in out Arunners_List_Pack2.List;
                           Order : in     Boolean := False;
                           Max   : in     Integer_4 := Integer_4'Last) is
    use Sql;
    Start_Trans : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;
    if Order then
    Stm_Select_I2_Runnernamestripped_O.Prepare("select * from ARUNNERS " &
                "where RUNNERNAMESTRIPPED =:RUNNERNAMESTRIPPED " &
            "order by " & 
            "MARKETID, " & 
            "SELECTIONID");
    Stm_Select_I2_Runnernamestripped_O.Set("RUNNERNAMESTRIPPED", Data.Runnernamestripped);
      Read_List(Stm_Select_I2_Runnernamestripped_O, List, Max);
    else
    Stm_Select_I2_Runnernamestripped.Prepare("select * from ARUNNERS " &
                "where RUNNERNAMESTRIPPED =:RUNNERNAMESTRIPPED " &
            "");
    Stm_Select_I2_Runnernamestripped.Set("RUNNERNAMESTRIPPED", Data.Runnernamestripped);
      Read_List(Stm_Select_I2_Runnernamestripped, List, Max);
    end if;
    if Start_Trans then Transaction.Commit; end if;      
  end Read_Runnernamestripped;
-----------------------------------------------



  procedure Read_Marketid_Status(
                           Data  : in out Table_Arunners.Data_Type'class;
                           List  : in out Arunners_List_Pack2.List;
                           Order : in     Boolean := False;
                           Max   : in     Integer_4 := Integer_4'Last) is
    use Sql;
    Start_Trans : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;
    if Order then
    Stm_Select_I3_Marketid_Status_O.Prepare("select * from ARUNNERS " &
                "where MARKETID =:MARKETID " &
                "and STATUS =:STATUS " &
            "order by " & 
            "MARKETID, " & 
            "SELECTIONID");
    Stm_Select_I3_Marketid_Status_O.Set("MARKETID", Data.Marketid);
    Stm_Select_I3_Marketid_Status_O.Set("STATUS", Data.Status);
      Read_List(Stm_Select_I3_Marketid_Status_O, List, Max);
    else
    Stm_Select_I3_Marketid_Status.Prepare("select * from ARUNNERS " &
                "where MARKETID =:MARKETID " &
                "and STATUS =:STATUS " &
            "");
    Stm_Select_I3_Marketid_Status.Set("MARKETID", Data.Marketid);
    Stm_Select_I3_Marketid_Status.Set("STATUS", Data.Status);
      Read_List(Stm_Select_I3_Marketid_Status, List, Max);
    end if;
    if Start_Trans then Transaction.Commit; end if;      
  end Read_Marketid_Status;
-----------------------------------------------

  procedure Read_I3_Marketid(
                           Data  : in     Table_Arunners.Data_Type'class;
                           List  : in out Arunners_List_Pack2.List;
                           Order : in     Boolean := False;
                           Max   : in     Integer_4 := Integer_4'Last) is
    use Sql;
    Start_Trans : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;
    if Order then
    Stm_Select_I3_Marketid_O.Prepare("select * from ARUNNERS " &
                "where MARKETID =:MARKETID " &
            "order by " & 
            "MARKETID, " & 
            "SELECTIONID");
    Stm_Select_I3_Marketid_O.Set("MARKETID", Data.Marketid);
      Read_List(Stm_Select_I3_Marketid_O, List, Max);
    else
    Stm_Select_I3_Marketid.Prepare("select * from ARUNNERS " &
                "where MARKETID =:MARKETID " &
            "");
    Stm_Select_I3_Marketid.Set("MARKETID", Data.Marketid);
      Read_List(Stm_Select_I3_Marketid, List, Max);
    end if;
    if Start_Trans then Transaction.Commit; end if;      
  end Read_I3_Marketid;


  procedure Read_I3_Marketid_Status(
                           Data  : in     Table_Arunners.Data_Type'class;
                           List  : in out Arunners_List_Pack2.List;
                           Order : in     Boolean := False;
                           Max   : in     Integer_4 := Integer_4'Last) is
    use Sql;
    Start_Trans : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;
    if Order then
    Stm_Select_I3_Marketid_Status_O.Prepare("select * from ARUNNERS " &
                "where MARKETID =:MARKETID " &
                "and STATUS =:STATUS " &
            "order by " & 
            "MARKETID, " & 
            "SELECTIONID");
    Stm_Select_I3_Marketid_Status_O.Set("MARKETID", Data.Marketid);
    Stm_Select_I3_Marketid_Status_O.Set("STATUS", Data.Status);
      Read_List(Stm_Select_I3_Marketid_Status_O, List, Max);
    else
    Stm_Select_I3_Marketid_Status.Prepare("select * from ARUNNERS " &
                "where MARKETID =:MARKETID " &
                "and STATUS =:STATUS " &
            "");
    Stm_Select_I3_Marketid_Status.Set("MARKETID", Data.Marketid);
    Stm_Select_I3_Marketid_Status.Set("STATUS", Data.Status);
      Read_List(Stm_Select_I3_Marketid_Status, List, Max);
    end if;
    if Start_Trans then Transaction.Commit; end if;      
  end Read_I3_Marketid_Status;




  procedure Read_Status(
                           Data  : in out Table_Arunners.Data_Type'class;
                           List  : in out Arunners_List_Pack2.List;
                           Order : in     Boolean := False;
                           Max   : in     Integer_4 := Integer_4'Last) is
    use Sql;
    Start_Trans : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;
    if Order then
    Stm_Select_I4_Status_O.Prepare("select * from ARUNNERS " &
                "where STATUS =:STATUS " &
            "order by " & 
            "MARKETID, " & 
            "SELECTIONID");
    Stm_Select_I4_Status_O.Set("STATUS", Data.Status);
      Read_List(Stm_Select_I4_Status_O, List, Max);
    else
    Stm_Select_I4_Status.Prepare("select * from ARUNNERS " &
                "where STATUS =:STATUS " &
            "");
    Stm_Select_I4_Status.Set("STATUS", Data.Status);
      Read_List(Stm_Select_I4_Status, List, Max);
    end if;
    if Start_Trans then Transaction.Commit; end if;      
  end Read_Status;
-----------------------------------------------



  procedure Read_Ixxluts(
                           Data  : in out Table_Arunners.Data_Type'class;
                           List  : in out Arunners_List_Pack2.List;
                           Order : in     Boolean := False;
                           Max   : in     Integer_4 := Integer_4'Last) is
    use Sql;
    Start_Trans : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;
    if Order then
    Stm_Select_I5_Ixxluts_O.Prepare("select * from ARUNNERS " &
                "where IXXLUTS =:IXXLUTS " &
            "order by " & 
            "MARKETID, " & 
            "SELECTIONID");
    Stm_Select_I5_Ixxluts_O.Set_Timestamp("IXXLUTS", Data.Ixxluts);
      Read_List(Stm_Select_I5_Ixxluts_O, List, Max);
    else
    Stm_Select_I5_Ixxluts.Prepare("select * from ARUNNERS " &
                "where IXXLUTS =:IXXLUTS " &
            "");
    Stm_Select_I5_Ixxluts.Set_Timestamp("IXXLUTS", Data.Ixxluts);
      Read_List(Stm_Select_I5_Ixxluts, List, Max);
    end if;
    if Start_Trans then Transaction.Commit; end if;      
  end Read_Ixxluts;
-----------------------------------------------



  procedure From_Xml(Xml_Filename : in Unbounded_String;
                     A_List       : in out Arunners_List_Pack2.List) is
    My_Reader   : Arunners_Reader;
    Input       : File_Input;
  begin
    My_Reader.Arunners_List := A_List;
    My_Reader.Current_Tag := Null_Unbounded_String;
    Open(To_String(Xml_Filename), Input);
    My_Reader.Set_Feature(Validation_Feature,False);
    My_Reader.Parse(Input);
    Input.Close;
    if not My_Reader.OK then
       My_Reader.Arunners_List.Clear;
    end if;
    A_List := My_Reader.Arunners_List;
  end From_Xml;

end Table_Arunners;
