
-----------------------------------------------------
-- This file is AUTOGENERATED by                     
-- repo                                              
--                                                   
----CHANGES HERE WILL BE LOST NEXT GENERATE!!!!----- 
-----------DO NOT EDIT THIS FILE!!!!---------------- 
-----------------------------------------------------




pragma Warnings(Off);
with Process_Io, Utils;
with Ada.Strings.Fixed; use Ada.Strings.Fixed;
with Sax.Readers;              use Sax.Readers;
with Input_Sources.File;       use Input_Sources.File;
with Unicode.CES;
with Unicode.Encodings;
with Sax.Attributes;



package body Table_Arewards is

  Stm_Select,
  Stm_Delete,
  Stm_Update,
  Stm_Insert,
  Stm_Select_All,
  Stm_Select_All_O  : Sql.Statement_Type;


  Stm_Delete_With_Check,
  Stm_Update_With_Check  : Sql.Statement_Type;


  -- Primary keys, when several fields
  Stm_Select_I1_Marketid,
  Stm_Select_I1_Marketid_O,
  Stm_Delete_I1_Marketid : Sql.Statement_Type; 

  -- Primary keys, when several fields
  Stm_Select_I1_Marketid_Selectionid,
  Stm_Select_I1_Marketid_Selectionid_O,
  Stm_Delete_I1_Marketid_Selectionid : Sql.Statement_Type; 

  -- Primary keys, when several fields
  Stm_Select_I1_Marketid_Selectionid_Pricets,
  Stm_Select_I1_Marketid_Selectionid_Pricets_O,
  Stm_Delete_I1_Marketid_Selectionid_Pricets : Sql.Statement_Type; 

  -- Primary keys, when several fields
  Stm_Select_I1_Marketid_Selectionid_Pricets_Side,
  Stm_Select_I1_Marketid_Selectionid_Pricets_Side_O,
  Stm_Delete_I1_Marketid_Selectionid_Pricets_Side : Sql.Statement_Type; 

  -- non unique index all fields
  Stm_Delete_Marketid_Selectionid_Pricets_Side: Sql.Statement_Type;



  -- Procedures for all DBMS

  -- Procedures for DBMS SQL
  -- Primary key

  function Get(Stm : in Sql.Statement_Type) return Table_Arewards.Data_Type is
    Data : Table_Arewards.Data_Type;
  begin
    Stm.Get("MARKETID", Data.Marketid);
    Stm.Get("SELECTIONID", Data.Selectionid);
    Stm.Get_Timestamp("PRICETS", Data.Pricets);
    Stm.Get("SIDE", Data.Side);
    Stm.Get("PROFIT", Data.Profit);
    Stm.Get("IXXLUPD", Data.Ixxlupd);
    Stm.Get_Timestamp("IXXLUTS", Data.Ixxluts);

    return Data;
  end Get;
---------------------------------------------


  function Get(
                  Marketid : String;
                  Selectionid : Integer_4;
                  Pricets : Time_Type;
                  Side : String) return Table_Arewards.Data_Type is
    Data       : Table_Arewards.Data_Type;
    End_Of_Set : Boolean := True;
  begin
    Data.Marketid := Marketid;
    Data.Selectionid := Selectionid;
    Data.Pricets := Pricets;
    Data.Side := Side;
    Data.Read(End_Of_Set);
    return Data;
  end Get;



  procedure Read_All(List  : in out Arewards_List_Pack2.List;
                     Order : in     Boolean := False;
                     Max   : in     Integer_4 := Integer_4'Last) is
    use Sql;
    Start_Trans   : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction   : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;
    if Order then
      Stm_Select_All_O.Prepare("select * from AREWARDS order by " &
                  "MARKETID, " &
                  "SELECTIONID, " &
                  "PRICETS, " &
                  "SIDE");
      Read_List(Stm_Select_All_O, List, Max);
    else
      Stm_Select_All.Prepare("select * from AREWARDS");
      Read_List(Stm_Select_All, List, Max);
    end if;
    if Start_Trans then Transaction.Commit; end if;
  end Read_All;


  procedure Read_List(Stm   : in     Sql.Statement_Type;
                      List  : in out Arewards_List_Pack2.List;
                      Max   : in     Integer_4 := Integer_4'Last) is
    use Sql;
    Start_Trans  : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction  : Sql.Transaction_Type;
    Count        : Integer_4 := 0;
    Data         : Table_Arewards.Data_Type;
    Eos          : Boolean := False;
  begin
    if Start_Trans then Transaction.Start; end if;
    Stm.Open_Cursor;
    loop
      Stm.Fetch(Eos);
      exit when Eos or Count > Max;
      Data := Get(Stm);
      List.Append(Data);
      Count := Count +1;
    end loop;
    Stm.Close_Cursor;
    if Start_Trans then Transaction.Commit; end if;
  end Read_List;


  function Is_Existing(
                  Marketid : String;
                  Selectionid : Integer_4;
                  Pricets : Time_Type;
                  Side : String) return Boolean is
    Data       : Table_Arewards.Data_Type;
    End_Of_Set : Boolean := True;
  begin
    Data.Marketid := Marketid;
    Data.Selectionid := Selectionid;
    Data.Pricets := Pricets;
    Data.Side := Side;
    Read(Data, End_Of_Set);
    return not End_Of_Set;
  end Is_Existing;


  procedure Read(Data       : in out Table_Arewards.Data_Type;
                 End_Of_Set : in out Boolean) is
    use Sql;
    Start_Trans   : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction   : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;
    Stm_Select.Prepare("select * from AREWARDS " &
                "where MARKETID =:MARKETID " &
                "and SELECTIONID =:SELECTIONID " &
                "and PRICETS =:PRICETS " &
                "and SIDE =:SIDE " &
            "");
    Stm_Select.Set("MARKETID", Data.Marketid);
    Stm_Select.Set("SELECTIONID", Data.Selectionid);
    Stm_Select.Set_Timestamp("PRICETS", Data.Pricets);
    Stm_Select.Set("SIDE", Data.Side);
    Stm_Select.Open_Cursor;
    Stm_Select.Fetch(End_Of_Set);
    if not End_Of_Set then
      Data := Get(Stm_Select);
    end if;
    Stm_Select.Close_Cursor;
    if Start_Trans then Transaction.Commit; end if;
  end Read;

  procedure Delete(Data : in Table_Arewards.Data_Type) is
  begin
    Stm_Delete.Prepare("delete from AREWARDS " &
                "where MARKETID =:MARKETID " &
                "and SELECTIONID =:SELECTIONID " &
                "and PRICETS =:PRICETS " &
                "and SIDE =:SIDE " &
            "");
    Stm_Delete.Set("MARKETID", Data.Marketid);
    Stm_Delete.Set("SELECTIONID", Data.Selectionid);
    Stm_Delete.Set_Timestamp("PRICETS", Data.Pricets);
    Stm_Delete.Set("SIDE", Data.Side);
    Stm_Delete.Execute;
  end Delete;

  procedure Update(Data : in out Table_Arewards.Data_Type ; Keep_Timestamp : in Boolean := False) is
    Now     : Calendar2.Time_Type := Calendar2.Clock;
    Process : Process_Io.Process_Type     := Process_Io.This_Process;
  begin
    Stm_Update.Prepare("update AREWARDS set  " &
            "PROFIT=:PROFIT, " &
            "IXXLUPD=:IXXLUPD, " &
            "IXXLUTS=:IXXLUTS " &
            "where MARKETID=:MARKETID " &
            "and SELECTIONID=:SELECTIONID " &
            "and PRICETS=:PRICETS " &
            "and SIDE=:SIDE " &
            "");

    if not Keep_Timestamp then
      Data.Ixxluts := Now;
    end if;
      Stm_Update.Set("PROFIT", Data.Profit);
    if not Keep_Timestamp then
      null; --for tables without Ixxlupd
      Data.Ixxlupd := Process.Name(1..15);
    end if;
      Stm_Update.Set("IXXLUPD", Data.Ixxlupd);
      Stm_Update.Set_Timestamp("IXXLUTS", Data.Ixxluts);
    Stm_Update.Set("MARKETID", Data.Marketid);
    Stm_Update.Set("SELECTIONID", Data.Selectionid);
    Stm_Update.Set_Timestamp("PRICETS", Data.Pricets);
    Stm_Update.Set("SIDE", Data.Side);
    Stm_Update.Execute;
  end Update;

  procedure Insert(Data : in out Table_Arewards.Data_Type; Keep_Timestamp : in Boolean := False) is
    Now     : Calendar2.Time_Type := Calendar2.Clock;
    Process : Process_Io.Process_Type     := Process_Io.This_Process;
  begin
    if not Keep_Timestamp then
      Data.Ixxluts := Now;
    end if;
    Stm_Insert.Prepare("insert into AREWARDS values (" &
         ":MARKETID," &
         ":SELECTIONID," &
         ":PRICETS," &
         ":SIDE," &
         ":PROFIT," &
         ":IXXLUPD," &
         ":IXXLUTS)");

    if not Keep_Timestamp then
      Data.Ixxluts := Now;
    end if;
      Stm_Insert.Set("MARKETID", Data.Marketid);
      Stm_Insert.Set("SELECTIONID", Data.Selectionid);
      Stm_Insert.Set_Timestamp("PRICETS", Data.Pricets);
      Stm_Insert.Set("SIDE", Data.Side);
      Stm_Insert.Set("PROFIT", Data.Profit);
    if not Keep_Timestamp then
      null; --for tables without Ixxlupd
      Data.Ixxlupd := Process.Name(1..15);
    end if;
      Stm_Insert.Set("IXXLUPD", Data.Ixxlupd);
      Stm_Insert.Set_Timestamp("IXXLUTS", Data.Ixxluts);
    Stm_Insert.Execute;
  end Insert;
--------------------------------------------
  procedure Delete_Withcheck(Data : in Table_Arewards.Data_Type) is
  begin
    Stm_Delete_With_Check.Prepare("delete from AREWARDS " &
                "where MARKETID =:MARKETID " &
                "and SELECTIONID =:SELECTIONID " &
                "and PRICETS =:PRICETS " &
                "and SIDE =:SIDE " &
            "and IXXLUPD = :IXXLUPD " &
            "and IXXLUTS = :IXXLUTS " &
            "");
    Stm_Delete_With_Check.Set("MARKETID", Data.Marketid);
    Stm_Delete_With_Check.Set("SELECTIONID", Data.Selectionid);
    Stm_Delete_With_Check.Set_Timestamp("PRICETS", Data.Pricets);
    Stm_Delete_With_Check.Set("SIDE", Data.Side);
    Stm_Delete_With_Check.Set("IXXLUPD", Data.Ixxlupd);
    Stm_Delete_With_Check.Set_Timestamp("IXXLUTS", Data.Ixxluts);
    Stm_Delete_With_Check.Execute;
  end Delete_Withcheck;
--------------------------------------------
  procedure Update_Withcheck(Data : in out Table_Arewards.Data_Type; Keep_Timestamp : in Boolean := False) is
    Now     : Calendar2.Time_Type := Calendar2.Clock;
    Process : Process_Io.Process_Type     := Process_Io.This_Process;
  begin
    Stm_Update_With_Check.Prepare("update AREWARDS set  " &
            "PROFIT=:PROFIT, " &
            "IXXLUPD=:IXXLUPD, " &
            "IXXLUTS=:IXXLUTS " &
            "where MARKETID=:MARKETID " &
            "and SELECTIONID=:SELECTIONID " &
            "and PRICETS=:PRICETS " &
            "and SIDE=:SIDE " &
    "and IXXLUPD = :OLD_IXXLUPD " &
    "and IXXLUTS = :OLD_IXXLUTS " &
            "");
    Stm_Update_With_Check.Set("MARKETID", Data.Marketid);
    Stm_Update_With_Check.Set("SELECTIONID", Data.Selectionid);
    Stm_Update_With_Check.Set_Timestamp("PRICETS", Data.Pricets);
    Stm_Update_With_Check.Set("SIDE", Data.Side);
    Stm_Update_With_Check.Set("OLD_IXXLUPD", Data.Ixxlupd );
    Stm_Update_With_Check.Set_Timestamp("OLD_IXXLUTS", Data.Ixxluts );

    if not Keep_Timestamp then
      Data.Ixxluts := Now;
    end if;
      Stm_Update_With_Check.Set("PROFIT", Data.Profit);
    if not Keep_Timestamp then
      null; --for tables without Ixxlupd
      Data.Ixxlupd := Process.Name(1..15);
    end if;
      Stm_Update_With_Check.Set("IXXLUPD", Data.Ixxlupd);
      Stm_Update_With_Check.Set_Timestamp("IXXLUTS", Data.Ixxluts);
    Stm_Update_With_Check.Execute;
  end Update_Withcheck;
--------------------------------------------

  -- primary key index several fields
  procedure Delete_Marketid_Selectionid_Pricets_Side(Data  : in Table_Arewards.Data_Type) is
  begin
    Stm_Delete_Marketid_Selectionid_Pricets_Side.Prepare("delete from AREWARDS " &
                "where MARKETID =:MARKETID " &
                "and SELECTIONID =:SELECTIONID " &
                "and PRICETS =:PRICETS " &
                "and SIDE =:SIDE " &
            "");
    Stm_Delete_Marketid_Selectionid_Pricets_Side.Set("MARKETID", Data.Marketid);
    Stm_Delete_Marketid_Selectionid_Pricets_Side.Set("SELECTIONID", Data.Selectionid);
    Stm_Delete_Marketid_Selectionid_Pricets_Side.Set_Timestamp("PRICETS", Data.Pricets);
    Stm_Delete_Marketid_Selectionid_Pricets_Side.Set("SIDE", Data.Side);
    Stm_Delete_Marketid_Selectionid_Pricets_Side.Execute;
  end Delete_Marketid_Selectionid_Pricets_Side;
  --------------------------------------------


  -- part of primary key index
  procedure Delete_I1_Marketid(Data  : in     Table_Arewards.Data_Type) is
  begin
    Stm_Delete_I1_Marketid.Prepare("delete from AREWARDS " &
                "where MARKETID =:MARKETID " &
            "");
    Stm_Delete_I1_Marketid.Set("MARKETID", Data.Marketid);
    Stm_Delete_I1_Marketid.Execute;
  end Delete_I1_Marketid;

  -- part of primary key index
  function Is_Existing_I1(
      Marketid : in String) return Boolean is
    Data       : Table_Arewards.Data_Type;
    Is_Exist   : Boolean := False;
    List       : Arewards_List_Pack2.List;
  begin
    Data.Marketid := Marketid;
    Read_I1_Marketid(Data, List, False, 1);
    Is_Exist := not List.Is_Empty;
    List.Clear;
    return Is_Exist;
  end Is_Existing_I1;

  -- part of primary key index
  procedure Delete_I1_Marketid_Selectionid(Data  : in     Table_Arewards.Data_Type) is
  begin
    Stm_Delete_I1_Marketid_Selectionid.Prepare("delete from AREWARDS " &
                "where MARKETID =:MARKETID " &
                "and SELECTIONID =:SELECTIONID " &
            "");
    Stm_Delete_I1_Marketid_Selectionid.Set("MARKETID", Data.Marketid);
    Stm_Delete_I1_Marketid_Selectionid.Set("SELECTIONID", Data.Selectionid);
    Stm_Delete_I1_Marketid_Selectionid.Execute;
  end Delete_I1_Marketid_Selectionid;

  -- part of primary key index
  function Is_Existing_I1(
      Marketid : in String;
      Selectionid : in Integer_4) return Boolean is
    Data       : Table_Arewards.Data_Type;
    Is_Exist   : Boolean := False;
    List       : Arewards_List_Pack2.List;
  begin
    Data.Marketid := Marketid;
    Data.Selectionid := Selectionid;
    Read_I1_Marketid_Selectionid(Data, List, False, 1);
    Is_Exist := not List.Is_Empty;
    List.Clear;
    return Is_Exist;
  end Is_Existing_I1;

  -- part of primary key index
  procedure Delete_I1_Marketid_Selectionid_Pricets(Data  : in     Table_Arewards.Data_Type) is
  begin
    Stm_Delete_I1_Marketid_Selectionid_Pricets.Prepare("delete from AREWARDS " &
                "where MARKETID =:MARKETID " &
                "and SELECTIONID =:SELECTIONID " &
                "and PRICETS =:PRICETS " &
            "");
    Stm_Delete_I1_Marketid_Selectionid_Pricets.Set("MARKETID", Data.Marketid);
    Stm_Delete_I1_Marketid_Selectionid_Pricets.Set("SELECTIONID", Data.Selectionid);
    Stm_Delete_I1_Marketid_Selectionid_Pricets.Set_Timestamp("PRICETS", Data.Pricets);
    Stm_Delete_I1_Marketid_Selectionid_Pricets.Execute;
  end Delete_I1_Marketid_Selectionid_Pricets;

  -- part of primary key index
  function Is_Existing_I1(
      Marketid : in String;
      Selectionid : in Integer_4;
      Pricets : in Time_Type) return Boolean is
    Data       : Table_Arewards.Data_Type;
    Is_Exist   : Boolean := False;
    List       : Arewards_List_Pack2.List;
  begin
    Data.Marketid := Marketid;
    Data.Selectionid := Selectionid;
    Data.Pricets := Pricets;
    Read_I1_Marketid_Selectionid_Pricets(Data, List, False, 1);
    Is_Exist := not List.Is_Empty;
    List.Clear;
    return Is_Exist;
  end Is_Existing_I1;

  -- part of primary key index
  procedure Delete_I1_Marketid_Selectionid_Pricets_Side(Data  : in     Table_Arewards.Data_Type) is
  begin
    Stm_Delete_I1_Marketid_Selectionid_Pricets_Side.Prepare("delete from AREWARDS " &
                "where MARKETID =:MARKETID " &
                "and SELECTIONID =:SELECTIONID " &
                "and PRICETS =:PRICETS " &
                "and SIDE =:SIDE " &
            "");
    Stm_Delete_I1_Marketid_Selectionid_Pricets_Side.Set("MARKETID", Data.Marketid);
    Stm_Delete_I1_Marketid_Selectionid_Pricets_Side.Set("SELECTIONID", Data.Selectionid);
    Stm_Delete_I1_Marketid_Selectionid_Pricets_Side.Set_Timestamp("PRICETS", Data.Pricets);
    Stm_Delete_I1_Marketid_Selectionid_Pricets_Side.Set("SIDE", Data.Side);
    Stm_Delete_I1_Marketid_Selectionid_Pricets_Side.Execute;
  end Delete_I1_Marketid_Selectionid_Pricets_Side;

  -- part of primary key index
  function Is_Existing_I1(
      Marketid : in String;
      Selectionid : in Integer_4;
      Pricets : in Time_Type;
      Side : in String) return Boolean is
    Data       : Table_Arewards.Data_Type;
    Is_Exist   : Boolean := False;
    List       : Arewards_List_Pack2.List;
  begin
    Data.Marketid := Marketid;
    Data.Selectionid := Selectionid;
    Data.Pricets := Pricets;
    Data.Side := Side;
    Read_I1_Marketid_Selectionid_Pricets_Side(Data, List, False, 1);
    Is_Exist := not List.Is_Empty;
    List.Clear;
    return Is_Exist;
  end Is_Existing_I1;



  -- Procedures for all DBMS


  function To_String(Data : in Table_Arewards.Data_Type) return String is
  begin
    return
          "Marketid = " & Utils.Trim(Data.Marketid) & " " &
          "Selectionid = " & Utils.Trim(Data.Selectionid'Img) & " " &
          "Pricets = " & Calendar2.String_Date_And_Time(Data.Pricets, Milliseconds => True ) & " " &
          "Side = " & Utils.Trim(Data.Side) & " " &
          "Profit = " & Utils.F8_Image(Data.Profit) & " " &
          "Ixxlupd = " & Utils.Trim(Data.Ixxlupd) & " " &
          "Ixxluts = " & Calendar2.String_Date_And_Time(Data.Ixxluts, Milliseconds => True ) & " " &
          "";
  end To_String;

  function To_JSON(Data : in Table_Arewards.Data_Type) return JSON_Value is
    Json_Data : JSON_Value := Create_Object;
  begin
    Json_Data.Set_Field(Field_Name => "marketid", Field => Utils.Trim(Data.Marketid));
    Json_Data.Set_Field(Field_Name => "selectionid", Field => Long_Integer(Data.Selectionid));
    Json_Data.Set_Field(Field_Name => "pricets", Field => Data.Pricets.To_String);
    Json_Data.Set_Field(Field_Name => "side", Field => Utils.Trim(Data.Side));
    Json_Data.Set_Field(Field_Name => "profit", Field => Float(Data.Profit));
    Json_Data.Set_Field(Field_Name => "ixxlupd", Field => Utils.Trim(Data.Ixxlupd));
    Json_Data.Set_Field(Field_Name => "ixxluts", Field => Data.Ixxluts.To_String);
    return Json_Data;
  end To_JSON;

  function From_JSON(JSON_Data : in JSON_Value) return Table_Arewards.Data_Type is
    use Ada.Strings;
    Data : Table_Arewards.Data_Type;
  begin
    if JSON_Data.Has_Field("marketid") then
      Move( Source => JSON_Data.Get("marketid"), Target => Data.Marketid , Drop => Right);
    end if;

    if JSON_Data.Has_Field("selectionid") then
      declare
        Tmp : Long_Integer := 0;
      begin
        Tmp := JSON_Data.Get("selectionid");
        Data.Selectionid := Integer_4(Tmp);
      end;
    end if;

    if JSON_Data.Has_Field("pricets") then
      declare
        Tmp : String := JSON_Data.Get("pricets");
      begin  -- "marketStartTime":"2013-06-22T17:39:00.000Z"
        Data.Pricets := Calendar2.To_Time_Type(Tmp(1..10), Tmp(12..23));
      end;
    end if;

    if JSON_Data.Has_Field("side") then
      Move( Source => JSON_Data.Get("side"), Target => Data.Side , Drop => Right);
    end if;

    if JSON_Data.Has_Field("profit") then
      declare
        Tmp : Float := 0.0;
      begin
        Tmp := JSON_Data.Get("profit");
        Data.Profit := Float(Tmp);
      end;
    end if;

    if JSON_Data.Has_Field("ixxlupd") then
      Move( Source => JSON_Data.Get("ixxlupd"), Target => Data.Ixxlupd , Drop => Right);
    end if;

    if JSON_Data.Has_Field("ixxluts") then
      declare
        Tmp : String := JSON_Data.Get("ixxluts");
      begin  -- "marketStartTime":"2013-06-22T17:39:00.000Z"
        Data.Ixxluts := Calendar2.To_Time_Type(Tmp(1..10), Tmp(12..23));
      end;
    end if;

    return Data;
  end From_JSON;

  function To_Xml(Data      : in Table_Arewards.Data_Type;
                  Ret_Start : in Boolean;
                  Ret_Data  : in Boolean;
                  Ret_End   : in Boolean) return String is
    Ls      : constant String := "";
    S_Start : constant String := "<AREWARDS_ROW>" & Ls;
    S_End   : constant String := "</AREWARDS_ROW>" & Ls;
    S1 : constant String :=
          "<MARKETID>" & Utils.Trim(Data.Marketid) & "</MARKETID>" & Ls;
    S2 : constant String :=
          "<SELECTIONID>" & Utils.Trim(Data.Selectionid'Img) & "</SELECTIONID>" & Ls;
    S3 : constant String :=
          "<PRICETS>" & Calendar2.String_Date_And_Time(Data.Pricets, Milliseconds => True) & "</PRICETS>" & Ls;
    S4 : constant String :=
          "<SIDE>" & Utils.Trim(Data.Side) & "</SIDE>" & Ls;
    S5 : constant String :=
          "<PROFIT>" & Utils.F8_Image(Data.Profit) & "</PROFIT>" & Ls;
    S6 : constant String :=
          "<IXXLUPD>" & Utils.Trim(Data.Ixxlupd) & "</IXXLUPD>" & Ls;
    S7 : constant String :=
          "<IXXLUTS>" & Calendar2.String_Date_And_Time(Data.Ixxluts, Milliseconds => True) & "</IXXLUTS>" & Ls;
    --------------------------------
    function Get_String(S : in String; Ret : in Boolean) return String is
    begin
      if Ret then return S; else return ""; end if;
    end Get_String;
    --------------------------------
  begin
    return Get_String(S_Start, Ret_Start) & 
           Get_String(
                       S1 &  S2 &  S3 &  S4 &  S5 &  S6 &  S7 , Ret_Data) &
           Get_String(S_End, Ret_End) & Ascii.LF;
  end To_Xml;
    --------------------------------

  --------------------------------------------
  type Arewards_Reader is new Sax.Readers.Reader with record
    Current_Tag    : Unbounded_String := Null_Unbounded_String;
    Accumulated    : Unbounded_String := Null_Unbounded_String;
    OK             : Boolean := True;
    Found_Set      : Boolean := True;
    Arewards_List     : Table_Arewards.Arewards_List_Pack2.List;
    Arewards_Data     : Table_Arewards.Data_Type := Empty_Data;
  end record;

  overriding procedure Start_Element(Handler       : in out Arewards_Reader;
                                     Namespace_URI : Unicode.CES.Byte_Sequence := "";
                                     Local_Name    : Unicode.CES.Byte_Sequence := "";
                                     Qname         : Unicode.CES.Byte_Sequence := "";
                                     Atts          : Sax.Attributes.Attributes'Class);

  overriding procedure End_Element(Handler         : in out Arewards_Reader;
                                   Namespace_URI   : Unicode.CES.Byte_Sequence := "";
                                   Local_Name      : Unicode.CES.Byte_Sequence := "";
                                   Qname           : Unicode.CES.Byte_Sequence := "");

  overriding procedure Characters(Handler          : in out Arewards_Reader;
                                  Ch               : Unicode.CES.Byte_Sequence := "");

  --------------------------------------------
  overriding procedure Start_Element(Handler       : in out Arewards_Reader;
                          Namespace_URI : Unicode.CES.Byte_Sequence := "";
                          Local_Name    : Unicode.CES.Byte_Sequence := "";
                          Qname         : Unicode.CES.Byte_Sequence := "";
                          Atts          : Sax.Attributes.Attributes'Class) is
    pragma Warnings(Off,Namespace_URI);
    pragma Warnings(Off,Qname);
    pragma Warnings(Off,Atts);
    The_Tag : constant String := Local_Name;
  begin
    Handler.Current_Tag := To_Unbounded_String(The_Tag);
    Handler.Accumulated := Null_Unbounded_String;
    if The_Tag = Table_Arewards_Set_Name then
      Handler.Found_Set := True;
    end if;
  exception
    when Ada.Strings.Length_Error => Handler.OK := False;
    when Constraint_Error         => Handler.OK := False;
  end Start_Element;
  --------------------------------------------

  --------------------------------------------
  overriding procedure End_Element(Handler       : in out Arewards_Reader;
                        Namespace_URI : Unicode.CES.Byte_Sequence := "";
                        Local_Name    : Unicode.CES.Byte_Sequence := "";
                        Qname         : Unicode.CES.Byte_Sequence := "") is
    pragma Warnings(Off,Namespace_URI);
    pragma Warnings(Off,Qname);
    The_Tag : constant String := Local_Name;
  begin
    if The_Tag = Table_Arewards_Set_Name then
      Handler.Found_Set := False;
    elsif The_Tag = Table_Arewards_Row_Name then
      if Handler.Found_Set then
        Handler.Arewards_List.Append(Handler.Arewards_Data);
        Handler.Arewards_Data := Empty_Data;
      end if;
    end if;
  exception
    when Ada.Strings.Length_Error => Handler.OK := False;
  end End_Element;
  --------------------------------------------

  --------------------------------------------
  overriding procedure Characters(Handler          : in out Arewards_Reader;
                       Ch               : Unicode.CES.Byte_Sequence := "") is
    function To_Iso_Latin_15(Str : Unicode.CES.Byte_Sequence) return String is
      use Unicode.Encodings;
    begin
      return  Convert(Str, Get_By_Name("utf-8"), Get_By_Name("iso-8859-15"));
    end To_Iso_Latin_15;
    The_Tag   : constant String := To_String(Handler.Current_Tag);
    The_Value : constant String := To_Iso_Latin_15(Ch);
    procedure Fix_String (Value    : String;
                          Variable : in out String) is
    begin
      Append(Handler.Accumulated, Value);
      Ada.Strings.Fixed.Move(To_String(Handler.Accumulated), Variable);
    end Fix_String;
  begin
    if Handler.Found_Set then
      if The_Tag = Marketid_Name then
       Fix_String(The_Value, Handler.Arewards_Data.Marketid);
      elsif The_Tag = Selectionid_Name then
       Handler.Arewards_Data.Selectionid := Integer_4'value(The_Value);
      elsif The_Tag = Pricets_Name then
       Handler.Arewards_Data.Pricets := Calendar2.To_Time_Type(The_Value(1..11), The_Value(13..24));
      elsif The_Tag = Side_Name then
       Fix_String(The_Value, Handler.Arewards_Data.Side);
      elsif The_Tag = Profit_Name then
       Handler.Arewards_Data.Profit := Float'value(The_Value);
      elsif The_Tag = Ixxlupd_Name then
       Fix_String(The_Value, Handler.Arewards_Data.Ixxlupd);
      elsif The_Tag = Ixxluts_Name then
       Handler.Arewards_Data.Ixxluts := Calendar2.To_Time_Type(The_Value(1..11), The_Value(13..24));
      end if;
    end if;
  exception
    when Ada.Strings.Length_Error => Handler.OK := False;
  end Characters;

  --------------------------------------------


  function To_Map (Data : Table_Arewards.Data_Type'class) return Table_Arewards.Arewards_Map_Pack_String.Map is
    Tmp_Map :  Table_Arewards.Arewards_Map_Pack_String.Map;
    Key : Key_Type := (others => ' ');
    Tmp_U_B_String : Unbounded_String := Null_Unbounded_String;
    Tmp_String     : String(1..1);
    pragma Warnings(Off, Tmp_String); -- used only if we have Character fields (ie String(1..1)
  begin
    Move("MARKETID", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Marketid);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("SELECTIONID", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Selectionid'Img);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("PRICETS", Key);
    Tmp_U_B_String := To_Unbounded_String(String_Date_And_Time(Data.Pricets));
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("SIDE", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Side);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("PROFIT", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Profit'Img);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("IXXLUPD", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Ixxlupd);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("IXXLUTS", Key);
    Tmp_U_B_String := To_Unbounded_String(String_Date_And_Time(Data.Ixxluts));
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    return Tmp_Map;
  end To_Map;
 ---------------------------


  function To_Map (Data : Table_Arewards.Data_Type'class) return Table_Arewards.Arewards_Map_Pack_Column_Type.Map is
    Tmp_Map :  Table_Arewards.Arewards_Map_Pack_Column_Type.Map;
    Key : Column_Type;
    Tmp_U_B_String : Unbounded_String := Null_Unbounded_String;
    Tmp_String     : String(1..1);
    pragma Warnings(Off, Tmp_String); -- used only if we have Character fields (ie String(1..1)
  begin
    Key := Marketid;
    Tmp_U_B_String := To_Unbounded_String(Data.Marketid);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Selectionid;
    Tmp_U_B_String := To_Unbounded_String(Data.Selectionid'Img);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Pricets;
    Tmp_U_B_String := To_Unbounded_String(String_Date_And_Time(Data.Pricets));
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Side;
    Tmp_U_B_String := To_Unbounded_String(Data.Side);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Profit;
    Tmp_U_B_String := To_Unbounded_String(Data.Profit'Img);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Ixxlupd;
    Tmp_U_B_String := To_Unbounded_String(Data.Ixxlupd);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Ixxluts;
    Tmp_U_B_String := To_Unbounded_String(String_Date_And_Time(Data.Ixxluts));
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    return Tmp_Map;
  end To_Map;
 ---------------------------
-------------------------------------------


  procedure Read_I1_Marketid(
                           Data  : in     Table_Arewards.Data_Type'class;
                           List  : in out Arewards_List_Pack2.List;
                           Order : in     Boolean := False;
                           Max   : in     Integer_4 := Integer_4'Last) is
    use Sql;
    Start_Trans : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;
    if Order then
    Stm_Select_I1_Marketid_O.Prepare("select * from AREWARDS " &
                "where MARKETID =:MARKETID " &
            "order by " & 
            "MARKETID, " & 
            "SELECTIONID, " & 
            "PRICETS, " & 
            "SIDE");
    Stm_Select_I1_Marketid_O.Set("MARKETID", Data.Marketid);
      Read_List(Stm_Select_I1_Marketid_O , List, Max);
    else
    Stm_Select_I1_Marketid.Prepare("select * from AREWARDS " &
                "where MARKETID =:MARKETID " &
            "");
    Stm_Select_I1_Marketid.Set("MARKETID", Data.Marketid);
      Read_List(Stm_Select_I1_Marketid, List, Max);
    end if;
    if Start_Trans then Transaction.Commit; end if;
  end Read_I1_Marketid;
-------------------------------------------

-------------------------------------------


  procedure Read_I1_Marketid_Selectionid(
                           Data  : in     Table_Arewards.Data_Type'class;
                           List  : in out Arewards_List_Pack2.List;
                           Order : in     Boolean := False;
                           Max   : in     Integer_4 := Integer_4'Last) is
    use Sql;
    Start_Trans : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;
    if Order then
    Stm_Select_I1_Marketid_Selectionid_O.Prepare("select * from AREWARDS " &
                "where MARKETID =:MARKETID " &
                "and SELECTIONID =:SELECTIONID " &
            "order by " & 
            "MARKETID, " & 
            "SELECTIONID, " & 
            "PRICETS, " & 
            "SIDE");
    Stm_Select_I1_Marketid_Selectionid_O.Set("MARKETID", Data.Marketid);
    Stm_Select_I1_Marketid_Selectionid_O.Set("SELECTIONID", Data.Selectionid);
      Read_List(Stm_Select_I1_Marketid_Selectionid_O , List, Max);
    else
    Stm_Select_I1_Marketid_Selectionid.Prepare("select * from AREWARDS " &
                "where MARKETID =:MARKETID " &
                "and SELECTIONID =:SELECTIONID " &
            "");
    Stm_Select_I1_Marketid_Selectionid.Set("MARKETID", Data.Marketid);
    Stm_Select_I1_Marketid_Selectionid.Set("SELECTIONID", Data.Selectionid);
      Read_List(Stm_Select_I1_Marketid_Selectionid, List, Max);
    end if;
    if Start_Trans then Transaction.Commit; end if;
  end Read_I1_Marketid_Selectionid;
-------------------------------------------

-------------------------------------------


  procedure Read_I1_Marketid_Selectionid_Pricets(
                           Data  : in     Table_Arewards.Data_Type'class;
                           List  : in out Arewards_List_Pack2.List;
                           Order : in     Boolean := False;
                           Max   : in     Integer_4 := Integer_4'Last) is
    use Sql;
    Start_Trans : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;
    if Order then
    Stm_Select_I1_Marketid_Selectionid_Pricets_O.Prepare("select * from AREWARDS " &
                "where MARKETID =:MARKETID " &
                "and SELECTIONID =:SELECTIONID " &
                "and PRICETS =:PRICETS " &
            "order by " & 
            "MARKETID, " & 
            "SELECTIONID, " & 
            "PRICETS, " & 
            "SIDE");
    Stm_Select_I1_Marketid_Selectionid_Pricets_O.Set("MARKETID", Data.Marketid);
    Stm_Select_I1_Marketid_Selectionid_Pricets_O.Set("SELECTIONID", Data.Selectionid);
    Stm_Select_I1_Marketid_Selectionid_Pricets_O.Set_Timestamp("PRICETS", Data.Pricets);
      Read_List(Stm_Select_I1_Marketid_Selectionid_Pricets_O , List, Max);
    else
    Stm_Select_I1_Marketid_Selectionid_Pricets.Prepare("select * from AREWARDS " &
                "where MARKETID =:MARKETID " &
                "and SELECTIONID =:SELECTIONID " &
                "and PRICETS =:PRICETS " &
            "");
    Stm_Select_I1_Marketid_Selectionid_Pricets.Set("MARKETID", Data.Marketid);
    Stm_Select_I1_Marketid_Selectionid_Pricets.Set("SELECTIONID", Data.Selectionid);
    Stm_Select_I1_Marketid_Selectionid_Pricets.Set_Timestamp("PRICETS", Data.Pricets);
      Read_List(Stm_Select_I1_Marketid_Selectionid_Pricets, List, Max);
    end if;
    if Start_Trans then Transaction.Commit; end if;
  end Read_I1_Marketid_Selectionid_Pricets;
-------------------------------------------

-------------------------------------------


  procedure Read_I1_Marketid_Selectionid_Pricets_Side(
                           Data  : in     Table_Arewards.Data_Type'class;
                           List  : in out Arewards_List_Pack2.List;
                           Order : in     Boolean := False;
                           Max   : in     Integer_4 := Integer_4'Last) is
    use Sql;
    Start_Trans : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;
    if Order then
    Stm_Select_I1_Marketid_Selectionid_Pricets_Side_O.Prepare("select * from AREWARDS " &
                "where MARKETID =:MARKETID " &
                "and SELECTIONID =:SELECTIONID " &
                "and PRICETS =:PRICETS " &
                "and SIDE =:SIDE " &
            "order by " & 
            "MARKETID, " & 
            "SELECTIONID, " & 
            "PRICETS, " & 
            "SIDE");
    Stm_Select_I1_Marketid_Selectionid_Pricets_Side_O.Set("MARKETID", Data.Marketid);
    Stm_Select_I1_Marketid_Selectionid_Pricets_Side_O.Set("SELECTIONID", Data.Selectionid);
    Stm_Select_I1_Marketid_Selectionid_Pricets_Side_O.Set_Timestamp("PRICETS", Data.Pricets);
    Stm_Select_I1_Marketid_Selectionid_Pricets_Side_O.Set("SIDE", Data.Side);
      Read_List(Stm_Select_I1_Marketid_Selectionid_Pricets_Side_O , List, Max);
    else
    Stm_Select_I1_Marketid_Selectionid_Pricets_Side.Prepare("select * from AREWARDS " &
                "where MARKETID =:MARKETID " &
                "and SELECTIONID =:SELECTIONID " &
                "and PRICETS =:PRICETS " &
                "and SIDE =:SIDE " &
            "");
    Stm_Select_I1_Marketid_Selectionid_Pricets_Side.Set("MARKETID", Data.Marketid);
    Stm_Select_I1_Marketid_Selectionid_Pricets_Side.Set("SELECTIONID", Data.Selectionid);
    Stm_Select_I1_Marketid_Selectionid_Pricets_Side.Set_Timestamp("PRICETS", Data.Pricets);
    Stm_Select_I1_Marketid_Selectionid_Pricets_Side.Set("SIDE", Data.Side);
      Read_List(Stm_Select_I1_Marketid_Selectionid_Pricets_Side, List, Max);
    end if;
    if Start_Trans then Transaction.Commit; end if;
  end Read_I1_Marketid_Selectionid_Pricets_Side;
-------------------------------------------



  procedure From_Xml(Xml_Filename : in Unbounded_String;
                     A_List       : in out Arewards_List_Pack2.List) is
    My_Reader   : Arewards_Reader;
    Input       : File_Input;
  begin
    My_Reader.Arewards_List := A_List;
    My_Reader.Current_Tag := Null_Unbounded_String;
    Open(To_String(Xml_Filename), Input);
    My_Reader.Set_Feature(Validation_Feature,False);
    My_Reader.Parse(Input);
    Input.Close;
    if not My_Reader.OK then
       My_Reader.Arewards_List.Clear;
    end if;
    A_List := My_Reader.Arewards_List;
  end From_Xml;

end Table_Arewards;
