-----------------------------------------------------
-- This file is AUTOGENERATED by                     
-- repo                                              
--                                                   
----CHANGES HERE WILL BE LOST NEXT GENERATE!!!!----- 
-----------DO NOT EDIT THIS FILE!!!!---------------- 
-----------------------------------------------------



with Ada.Containers.Doubly_Linked_Lists;
with Ada.Containers.Hashed_Maps;
with Ada.Containers.Ordered_Maps;
with Ada.Strings;
with Ada.Strings.Hash;
with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;
with Gnatcoll.Json; use Gnatcoll.Json;
with Types, Calendar2, Sql;
with Table_Utils;  --All tables inherit from here

pragma Elaborate_All(Calendar2);



package Table_Amarkets is
  use Types, Calendar2;
  --
  --  Table name as string 
  --

  Table_Amarkets_Name     : constant String := "AMARKETS";
  Table_Amarkets_Set_Name : constant String := "AMARKETS_SET";
  Table_Amarkets_Row_Name : constant String := "AMARKETS_ROW";

  --
  -- Column names as strings
  --

  Marketid_Name : constant String := "MARKETID";
  Marketname_Name : constant String := "MARKETNAME";
  Startts_Name : constant String := "STARTTS";
  Eventid_Name : constant String := "EVENTID";
  Markettype_Name : constant String := "MARKETTYPE";
  Status_Name : constant String := "STATUS";
  Betdelay_Name : constant String := "BETDELAY";
  Numwinners_Name : constant String := "NUMWINNERS";
  Numrunners_Name : constant String := "NUMRUNNERS";
  Numactiverunners_Name : constant String := "NUMACTIVERUNNERS";
  Totalmatched_Name : constant String := "TOTALMATCHED";
  Totalavailable_Name : constant String := "TOTALAVAILABLE";
  Ixxlupd_Name : constant String := "IXXLUPD";
  Ixxluts_Name : constant String := "IXXLUTS";
  --
  -- Column names as enumerator literals
  --

  type Column_Type is (
    Marketid,
    Marketname,
    Startts,
    Eventid,
    Markettype,
    Status,
    Betdelay,
    Numwinners,
    Numrunners,
    Numactiverunners,
    Totalmatched,
    Totalavailable,
    Ixxlupd,
    Ixxluts);
  --
  -- The type definition
  --

  type Data_Type is new Table_Utils.Root_Table_Type with record
    Marketid : String(1 .. 11) := (others => ' ') ; -- Primary Key
    Marketname : String(1 .. 50) := (others => ' ') ; 
    Startts : Time_Type := Time_Type_First ; 
    Eventid : String(1 .. 11) := (others => ' ') ; -- non unique index 2
    Markettype : String(1 .. 25) := (others => ' ') ; -- non unique index 3
    Status : String(1 .. 50) := (others => ' ') ; -- non unique index 4
    Betdelay : Integer_4 := 0 ; 
    Numwinners : Integer_4 := 0 ; -- non unique index 5
    Numrunners : Integer_4 := 0 ; 
    Numactiverunners : Integer_4 := 0 ; 
    Totalmatched : Fixed_Type := 0.0 ; 
    Totalavailable : Fixed_Type := 0.0 ; 
    Ixxlupd : String(1 .. 15) := (others => ' ') ; 
    Ixxluts : Time_Type := Time_Type_First ; -- non unique index 6
  end record;


  -- Procedures for all DBMS

  -- Procedures for DBMS SQL
  -- Primary key
  function Get(Stm : in Sql.Statement_Type) return Table_Amarkets.Data_Type;
  --------------------------------------------
  -- Primary key
  procedure Read(Data       : in out Table_Amarkets.Data_Type;
                 End_Of_Set : in out Boolean);
  --------------------------------------------
  -- Primary key
  function Is_Existing(
                       Marketid : String) 
                           return Boolean;
  --------------------------------------------
  -- Primary key
  function Get(
                       Marketid : String)
                           return Table_Amarkets.Data_Type;
  --------------------------------------------
  -- Primary key
  procedure Delete(Data : in Table_Amarkets.Data_Type);
  --------------------------------------------
  -- Primary key
  procedure Update(Data : in out Table_Amarkets.Data_Type; Keep_Timestamp : in Boolean := False);
  --------------------------------------------
  -- Primary key
  procedure Insert(Data : in out Table_Amarkets.Data_Type; Keep_Timestamp : in Boolean := False);
  --------------------------------------------
  -- Primary key
  procedure Delete_Withcheck(Data : in Table_Amarkets.Data_Type);
  --------------------------------------------
  -- Primary key
  procedure Update_Withcheck(Data : in out Table_Amarkets.Data_Type; Keep_Timestamp : in Boolean := False);
  --------------------------------------------
   -- stop Print_Def_Functions_Spec.Primary_Procs_Spec


  -- non unique index
  procedure Read_One_Eventid(
                           Data       : in out Table_Amarkets.Data_Type;
                           Order      : in     Boolean := False;
                           End_Of_Set : in out Boolean);
  --------------------------------------------

  -- non unique index
  function Count_Eventid(Data : Table_Amarkets.Data_Type) return Integer_4;
  --------------------------------------------

  -- non unique index
  procedure Delete_Eventid(Data  : in     Table_Amarkets.Data_Type);
  --------------------------------------------

  -- non unique index
  function Is_Existing_I2(Eventid : in String) return Boolean;
  --------------------------------------------




  -- non unique index
  procedure Read_One_Markettype(
                           Data       : in out Table_Amarkets.Data_Type;
                           Order      : in     Boolean := False;
                           End_Of_Set : in out Boolean);
  --------------------------------------------

  -- non unique index
  function Count_Markettype(Data : Table_Amarkets.Data_Type) return Integer_4;
  --------------------------------------------

  -- non unique index
  procedure Delete_Markettype(Data  : in     Table_Amarkets.Data_Type);
  --------------------------------------------

  -- non unique index
  function Is_Existing_I3(Markettype : in String) return Boolean;
  --------------------------------------------




  -- non unique index
  procedure Read_One_Status(
                           Data       : in out Table_Amarkets.Data_Type;
                           Order      : in     Boolean := False;
                           End_Of_Set : in out Boolean);
  --------------------------------------------

  -- non unique index
  function Count_Status(Data : Table_Amarkets.Data_Type) return Integer_4;
  --------------------------------------------

  -- non unique index
  procedure Delete_Status(Data  : in     Table_Amarkets.Data_Type);
  --------------------------------------------

  -- non unique index
  function Is_Existing_I4(Status : in String) return Boolean;
  --------------------------------------------




  -- non unique index
  procedure Read_One_Numwinners(
                           Data       : in out Table_Amarkets.Data_Type;
                           Order      : in     Boolean := False;
                           End_Of_Set : in out Boolean);
  --------------------------------------------

  -- non unique index
  function Count_Numwinners(Data : Table_Amarkets.Data_Type) return Integer_4;
  --------------------------------------------

  -- non unique index
  procedure Delete_Numwinners(Data  : in     Table_Amarkets.Data_Type);
  --------------------------------------------

  -- non unique index
  function Is_Existing_I5(Numwinners : in Integer_4) return Boolean;
  --------------------------------------------




  -- non unique index
  procedure Read_One_Ixxluts(
                           Data       : in out Table_Amarkets.Data_Type;
                           Order      : in     Boolean := False;
                           End_Of_Set : in out Boolean);
  --------------------------------------------

  -- non unique index
  function Count_Ixxluts(Data : Table_Amarkets.Data_Type) return Integer_4;
  --------------------------------------------

  -- non unique index
  procedure Delete_Ixxluts(Data  : in     Table_Amarkets.Data_Type);
  --------------------------------------------

  -- non unique index
  function Is_Existing_I6(Ixxluts : in Time_Type) return Boolean;
  --------------------------------------------






  -- Procedures for all DBMS, primitives

  function To_String(Data : in Table_Amarkets.Data_Type) return String;

  function To_JSON(Data : in Table_Amarkets.Data_Type) return JSON_Value;

  function From_JSON(JSON_Data : in JSON_Value) return Table_Amarkets.Data_Type;

  function To_Xml(Data      : in Table_Amarkets.Data_Type;
                  Ret_Start : in Boolean;
                  Ret_Data  : in Boolean;
                  Ret_End   : in Boolean) return String;


  package Amarkets_List_Pack2 is new Ada.Containers.Doubly_Linked_Lists(Table_Amarkets.Data_Type);

  subtype Key_Type is String(1..15);

  package Amarkets_Map_Pack_String is new Ada.Containers.Hashed_Maps(
      Key_Type,
      Unbounded_String,
      Ada.Strings.Hash,
      "=",
      "=");

  package Amarkets_Map_Pack_Column_Type is new Ada.Containers.Ordered_Maps(
      Column_Type,
      Unbounded_String,
      "<",
      "=");




  function To_Map (Data : Table_Amarkets.Data_Type'class) return Table_Amarkets.Amarkets_Map_Pack_String.Map;


  function To_Map (Data : Table_Amarkets.Data_Type'class) return Table_Amarkets.Amarkets_Map_Pack_Column_Type.Map;

  --------------------------------------------

  --------------------------------------------

  procedure Read_List(Stm  : in     Sql.Statement_Type;
                      List : in out Amarkets_List_Pack2.List;
                      Max  : in     Integer_4 := Integer_4'Last);

  --------------------------------------------


  procedure Read_All(List  : in out Amarkets_List_Pack2.List;
                     Order : in     Boolean := False;
                     Max   : in     Integer_4 := Integer_4'Last);
  --------------------------------------------




  procedure Read_Eventid(
                           Data  : in out Table_Amarkets.Data_Type'class;
                           List  : in out Amarkets_List_Pack2.List;
                           Order : in     Boolean := False;
                           Max   : in     Integer_4 := Integer_4'Last);







  procedure Read_Markettype(
                           Data  : in out Table_Amarkets.Data_Type'class;
                           List  : in out Amarkets_List_Pack2.List;
                           Order : in     Boolean := False;
                           Max   : in     Integer_4 := Integer_4'Last);







  procedure Read_Status(
                           Data  : in out Table_Amarkets.Data_Type'class;
                           List  : in out Amarkets_List_Pack2.List;
                           Order : in     Boolean := False;
                           Max   : in     Integer_4 := Integer_4'Last);







  procedure Read_Numwinners(
                           Data  : in out Table_Amarkets.Data_Type'class;
                           List  : in out Amarkets_List_Pack2.List;
                           Order : in     Boolean := False;
                           Max   : in     Integer_4 := Integer_4'Last);







  procedure Read_Ixxluts(
                           Data  : in out Table_Amarkets.Data_Type'class;
                           List  : in out Amarkets_List_Pack2.List;
                           Order : in     Boolean := False;
                           Max   : in     Integer_4 := Integer_4'Last);






  -- Procedures for all DBMS, others 

  procedure From_Xml(Xml_Filename : in Unbounded_String;
                     A_List       : in out Amarkets_List_Pack2.List);


  Empty_Data : Table_Amarkets.Data_Type;
end Table_Amarkets ;
