
-----------------------------------------------------
-- This file is AUTOGENERATED by                     
-- repo                                              
--                                                   
----CHANGES HERE WILL BE LOST NEXT GENERATE!!!!----- 
-----------DO NOT EDIT THIS FILE!!!!---------------- 
-----------------------------------------------------




pragma Warnings(Off);
with Process_Io, Utils;
with Ada.Strings.Fixed; use Ada.Strings.Fixed;
with Sax.Readers;              use Sax.Readers;
with Input_Sources.File;       use Input_Sources.File;
with Unicode.CES;
with Unicode.Encodings;
with Sax.Attributes;



package body Table_Fsensors is

  Stm_Select,
  Stm_Delete,
  Stm_Update,
  Stm_Insert,
  Stm_Select_All,
  Stm_Select_All_O  : Sql.Statement_Type;


  Stm_Delete_With_Check,
  Stm_Update_With_Check  : Sql.Statement_Type;


  -- Primary keys, when several fields
  Stm_Select_I1_Macaddress,
  Stm_Select_I1_Macaddress_O,
  Stm_Delete_I1_Macaddress : Sql.Statement_Type; 



  -- Procedures for all DBMS

  -- Procedures for DBMS SQL
  -- Primary key

  function Get(Stm : in Sql.Statement_Type) return Table_Fsensors.Data_Type is
    Data : Table_Fsensors.Data_Type;
  begin
    Stm.Get("MACADDRESS", Data.Macaddress);
    Stm.Get("POTNAME", Data.Potname);
    Stm.Get("THRESHOLD", Data.Threshold);
    Stm.Get_Timestamp("LASTNOTIFY", Data.Lastnotify);
    Stm.Get("IXXLUPD", Data.Ixxlupd);
    Stm.Get_Timestamp("IXXLUTS", Data.Ixxluts);

    return Data;
  end Get;
---------------------------------------------


  function Get(
                  Macaddress : String) return Table_Fsensors.Data_Type is
    Data       : Table_Fsensors.Data_Type;
    End_Of_Set : Boolean := True;
  begin
    Data.Macaddress := Macaddress;
    Data.Read(End_Of_Set);
    return Data;
  end Get;



  procedure Read_All(List  : in out Fsensors_List_Pack2.List;
                     Order : in     Boolean := False;
                     Max   : in     Integer_4 := Integer_4'Last) is
    use Sql;
    Start_Trans   : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction   : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;
    if Order then
      Stm_Select_All_O.Prepare("select * from FSENSORS order by " &
                  "MACADDRESS");
      Read_List(Stm_Select_All_O, List, Max);
    else
      Stm_Select_All.Prepare("select * from FSENSORS");
      Read_List(Stm_Select_All, List, Max);
    end if;
    if Start_Trans then Transaction.Commit; end if;
  end Read_All;


  procedure Read_List(Stm   : in     Sql.Statement_Type;
                      List  : in out Fsensors_List_Pack2.List;
                      Max   : in     Integer_4 := Integer_4'Last) is
    use Sql;
    Start_Trans  : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction  : Sql.Transaction_Type;
    Count        : Integer_4 := 0;
    Data         : Table_Fsensors.Data_Type;
    Eos          : Boolean := False;
  begin
    if Start_Trans then Transaction.Start; end if;
    Stm.Open_Cursor;
    loop
      Stm.Fetch(Eos);
      exit when Eos or Count > Max;
      Data := Get(Stm);
      List.Append(Data);
      Count := Count +1;
    end loop;
    Stm.Close_Cursor;
    if Start_Trans then Transaction.Commit; end if;
  end Read_List;


  function Is_Existing(
                  Macaddress : String) return Boolean is
    Data       : Table_Fsensors.Data_Type;
    End_Of_Set : Boolean := True;
  begin
    Data.Macaddress := Macaddress;
    Read(Data, End_Of_Set);
    return not End_Of_Set;
  end Is_Existing;


  procedure Read(Data       : in out Table_Fsensors.Data_Type;
                 End_Of_Set : in out Boolean) is
    use Sql;
    Start_Trans   : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction   : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;
    Stm_Select.Prepare("select * from FSENSORS " &
                "where MACADDRESS =:MACADDRESS " &
            "");
    Stm_Select.Set("MACADDRESS", Data.Macaddress);
    Stm_Select.Open_Cursor;
    Stm_Select.Fetch(End_Of_Set);
    if not End_Of_Set then
      Data := Get(Stm_Select);
    end if;
    Stm_Select.Close_Cursor;
    if Start_Trans then Transaction.Commit; end if;
  end Read;

  procedure Delete(Data : in Table_Fsensors.Data_Type) is
  begin
    Stm_Delete.Prepare("delete from FSENSORS " &
                "where MACADDRESS =:MACADDRESS " &
            "");
    Stm_Delete.Set("MACADDRESS", Data.Macaddress);
    Stm_Delete.Execute;
  end Delete;

  procedure Update(Data : in out Table_Fsensors.Data_Type ; Keep_Timestamp : in Boolean := False) is
    Now     : Calendar2.Time_Type := Calendar2.Clock;
    Process : Process_Io.Process_Type     := Process_Io.This_Process;
  begin
    Stm_Update.Prepare("update FSENSORS set  " &
            "POTNAME=:POTNAME, " &
            "THRESHOLD=:THRESHOLD, " &
            "LASTNOTIFY=:LASTNOTIFY, " &
            "IXXLUPD=:IXXLUPD, " &
            "IXXLUTS=:IXXLUTS " &
            "where MACADDRESS=:MACADDRESS " &
            "");

    if not Keep_Timestamp then
      Data.Ixxluts := Now;
    end if;
      Stm_Update.Set("POTNAME", Data.Potname);
      Stm_Update.Set("THRESHOLD", Data.Threshold);
      Stm_Update.Set_Timestamp("LASTNOTIFY", Data.Lastnotify);
    if not Keep_Timestamp then
      null; --for tables without Ixxlupd
      Data.Ixxlupd := Process.Name(1..15);
    end if;
      Stm_Update.Set("IXXLUPD", Data.Ixxlupd);
      Stm_Update.Set_Timestamp("IXXLUTS", Data.Ixxluts);
    Stm_Update.Set("MACADDRESS", Data.Macaddress);
    Stm_Update.Execute;
  end Update;

  procedure Insert(Data : in out Table_Fsensors.Data_Type; Keep_Timestamp : in Boolean := False) is
    Now     : Calendar2.Time_Type := Calendar2.Clock;
    Process : Process_Io.Process_Type     := Process_Io.This_Process;
  begin
    if not Keep_Timestamp then
      Data.Ixxluts := Now;
    end if;
    Stm_Insert.Prepare("insert into FSENSORS values (" &
         ":MACADDRESS," &
         ":POTNAME," &
         ":THRESHOLD," &
         ":LASTNOTIFY," &
         ":IXXLUPD," &
         ":IXXLUTS)");

    if not Keep_Timestamp then
      Data.Ixxluts := Now;
    end if;
      Stm_Insert.Set("MACADDRESS", Data.Macaddress);
      Stm_Insert.Set("POTNAME", Data.Potname);
      Stm_Insert.Set("THRESHOLD", Data.Threshold);
      Stm_Insert.Set_Timestamp("LASTNOTIFY", Data.Lastnotify);
    if not Keep_Timestamp then
      null; --for tables without Ixxlupd
      Data.Ixxlupd := Process.Name(1..15);
    end if;
      Stm_Insert.Set("IXXLUPD", Data.Ixxlupd);
      Stm_Insert.Set_Timestamp("IXXLUTS", Data.Ixxluts);
    Stm_Insert.Execute;
  end Insert;
--------------------------------------------
  procedure Delete_Withcheck(Data : in Table_Fsensors.Data_Type) is
  begin
    Stm_Delete_With_Check.Prepare("delete from FSENSORS " &
                "where MACADDRESS =:MACADDRESS " &
            "and IXXLUPD = :IXXLUPD " &
            "and IXXLUTS = :IXXLUTS " &
            "");
    Stm_Delete_With_Check.Set("MACADDRESS", Data.Macaddress);
    Stm_Delete_With_Check.Set("IXXLUPD", Data.Ixxlupd);
    Stm_Delete_With_Check.Set_Timestamp("IXXLUTS", Data.Ixxluts);
    Stm_Delete_With_Check.Execute;
  end Delete_Withcheck;
--------------------------------------------
  procedure Update_Withcheck(Data : in out Table_Fsensors.Data_Type; Keep_Timestamp : in Boolean := False) is
    Now     : Calendar2.Time_Type := Calendar2.Clock;
    Process : Process_Io.Process_Type     := Process_Io.This_Process;
  begin
    Stm_Update_With_Check.Prepare("update FSENSORS set  " &
            "POTNAME=:POTNAME, " &
            "THRESHOLD=:THRESHOLD, " &
            "LASTNOTIFY=:LASTNOTIFY, " &
            "IXXLUPD=:IXXLUPD, " &
            "IXXLUTS=:IXXLUTS " &
            "where MACADDRESS=:MACADDRESS " &
    "and IXXLUPD = :OLD_IXXLUPD " &
    "and IXXLUTS = :OLD_IXXLUTS " &
            "");
    Stm_Update_With_Check.Set("MACADDRESS", Data.Macaddress);
    Stm_Update_With_Check.Set("OLD_IXXLUPD", Data.Ixxlupd );
    Stm_Update_With_Check.Set_Timestamp("OLD_IXXLUTS", Data.Ixxluts );

    if not Keep_Timestamp then
      Data.Ixxluts := Now;
    end if;
      Stm_Update_With_Check.Set("POTNAME", Data.Potname);
      Stm_Update_With_Check.Set("THRESHOLD", Data.Threshold);
      Stm_Update_With_Check.Set_Timestamp("LASTNOTIFY", Data.Lastnotify);
    if not Keep_Timestamp then
      null; --for tables without Ixxlupd
      Data.Ixxlupd := Process.Name(1..15);
    end if;
      Stm_Update_With_Check.Set("IXXLUPD", Data.Ixxlupd);
      Stm_Update_With_Check.Set_Timestamp("IXXLUTS", Data.Ixxluts);
    Stm_Update_With_Check.Execute;
  end Update_Withcheck;
--------------------------------------------
   -- stop Print_Def_Functions_Body.Primary_Procs_Body



  -- Procedures for all DBMS


  function To_String(Data : in Table_Fsensors.Data_Type) return String is
  begin
    return
          "Macaddress = " & Utils.Trim(Data.Macaddress) & " " &
          "Potname = " & Utils.Trim(Data.Potname) & " " &
          "Threshold = " & Utils.Trim(Data.Threshold'Img) & " " &
          "Lastnotify = " & Calendar2.String_Date_And_Time(Data.Lastnotify, Milliseconds => True ) & " " &
          "Ixxlupd = " & Utils.Trim(Data.Ixxlupd) & " " &
          "Ixxluts = " & Calendar2.String_Date_And_Time(Data.Ixxluts, Milliseconds => True ) & " " &
          "";
  end To_String;

  function To_JSON(Data : in Table_Fsensors.Data_Type) return JSON_Value is
    Json_Data : JSON_Value := Create_Object;
  begin
    Json_Data.Set_Field(Field_Name => "macaddress", Field => Utils.Trim(Data.Macaddress));
    Json_Data.Set_Field(Field_Name => "potname", Field => Utils.Trim(Data.Potname));
    Json_Data.Set_Field(Field_Name => "threshold", Field => Long_Integer(Data.Threshold));
    Json_Data.Set_Field(Field_Name => "lastnotify", Field => Data.Lastnotify.To_String);
    Json_Data.Set_Field(Field_Name => "ixxlupd", Field => Utils.Trim(Data.Ixxlupd));
    Json_Data.Set_Field(Field_Name => "ixxluts", Field => Data.Ixxluts.To_String);
    return Json_Data;
  end To_JSON;

  function From_JSON(JSON_Data : in JSON_Value) return Table_Fsensors.Data_Type is
    use Ada.Strings;
    Data : Table_Fsensors.Data_Type;
  begin
    if JSON_Data.Has_Field("macaddress") then
      Move( Source => JSON_Data.Get("macaddress"), Target => Data.Macaddress , Drop => Right);
    end if;

    if JSON_Data.Has_Field("potname") then
      Move( Source => JSON_Data.Get("potname"), Target => Data.Potname , Drop => Right);
    end if;

    if JSON_Data.Has_Field("threshold") then
      declare
        Tmp : Long_Integer := 0;
      begin
        Tmp := JSON_Data.Get("threshold");
        Data.Threshold := Integer_4(Tmp);
      end;
    end if;

    if JSON_Data.Has_Field("lastnotify") then
      declare
        Tmp : String := JSON_Data.Get("lastnotify");
      begin  -- "marketStartTime":"2013-06-22T17:39:00.000Z"
        Data.Lastnotify := Calendar2.To_Time_Type(Tmp(1..10), Tmp(12..23));
      end;
    end if;

    if JSON_Data.Has_Field("ixxlupd") then
      Move( Source => JSON_Data.Get("ixxlupd"), Target => Data.Ixxlupd , Drop => Right);
    end if;

    if JSON_Data.Has_Field("ixxluts") then
      declare
        Tmp : String := JSON_Data.Get("ixxluts");
      begin  -- "marketStartTime":"2013-06-22T17:39:00.000Z"
        Data.Ixxluts := Calendar2.To_Time_Type(Tmp(1..10), Tmp(12..23));
      end;
    end if;

    return Data;
  end From_JSON;

  function To_Xml(Data      : in Table_Fsensors.Data_Type;
                  Ret_Start : in Boolean;
                  Ret_Data  : in Boolean;
                  Ret_End   : in Boolean) return String is
    Ls      : constant String := "";
    S_Start : constant String := "<FSENSORS_ROW>" & Ls;
    S_End   : constant String := "</FSENSORS_ROW>" & Ls;
    S1 : constant String :=
          "<MACADDRESS>" & Utils.Trim(Data.Macaddress) & "</MACADDRESS>" & Ls;
    S2 : constant String :=
          "<POTNAME>" & Utils.Trim(Data.Potname) & "</POTNAME>" & Ls;
    S3 : constant String :=
          "<THRESHOLD>" & Utils.Trim(Data.Threshold'Img) & "</THRESHOLD>" & Ls;
    S4 : constant String :=
          "<LASTNOTIFY>" & Calendar2.String_Date_And_Time(Data.Lastnotify, Milliseconds => True) & "</LASTNOTIFY>" & Ls;
    S5 : constant String :=
          "<IXXLUPD>" & Utils.Trim(Data.Ixxlupd) & "</IXXLUPD>" & Ls;
    S6 : constant String :=
          "<IXXLUTS>" & Calendar2.String_Date_And_Time(Data.Ixxluts, Milliseconds => True) & "</IXXLUTS>" & Ls;
    --------------------------------
    function Get_String(S : in String; Ret : in Boolean) return String is
    begin
      if Ret then return S; else return ""; end if;
    end Get_String;
    --------------------------------
  begin
    return Get_String(S_Start, Ret_Start) & 
           Get_String(
                       S1 &  S2 &  S3 &  S4 &  S5 &  S6 , Ret_Data) &
           Get_String(S_End, Ret_End) & Ascii.LF;
  end To_Xml;
    --------------------------------

  --------------------------------------------
  type Fsensors_Reader is new Sax.Readers.Reader with record
    Current_Tag    : Unbounded_String := Null_Unbounded_String;
    Accumulated    : Unbounded_String := Null_Unbounded_String;
    OK             : Boolean := True;
    Found_Set      : Boolean := True;
    Fsensors_List     : Table_Fsensors.Fsensors_List_Pack2.List;
    Fsensors_Data     : Table_Fsensors.Data_Type := Empty_Data;
  end record;

  overriding procedure Start_Element(Handler       : in out Fsensors_Reader;
                                     Namespace_URI : Unicode.CES.Byte_Sequence := "";
                                     Local_Name    : Unicode.CES.Byte_Sequence := "";
                                     Qname         : Unicode.CES.Byte_Sequence := "";
                                     Atts          : Sax.Attributes.Attributes'Class);

  overriding procedure End_Element(Handler         : in out Fsensors_Reader;
                                   Namespace_URI   : Unicode.CES.Byte_Sequence := "";
                                   Local_Name      : Unicode.CES.Byte_Sequence := "";
                                   Qname           : Unicode.CES.Byte_Sequence := "");

  overriding procedure Characters(Handler          : in out Fsensors_Reader;
                                  Ch               : Unicode.CES.Byte_Sequence := "");

  --------------------------------------------
  overriding procedure Start_Element(Handler       : in out Fsensors_Reader;
                          Namespace_URI : Unicode.CES.Byte_Sequence := "";
                          Local_Name    : Unicode.CES.Byte_Sequence := "";
                          Qname         : Unicode.CES.Byte_Sequence := "";
                          Atts          : Sax.Attributes.Attributes'Class) is
    pragma Warnings(Off,Namespace_URI);
    pragma Warnings(Off,Qname);
    pragma Warnings(Off,Atts);
    The_Tag : constant String := Local_Name;
  begin
    Handler.Current_Tag := To_Unbounded_String(The_Tag);
    Handler.Accumulated := Null_Unbounded_String;
    if The_Tag = Table_Fsensors_Set_Name then
      Handler.Found_Set := True;
    end if;
  exception
    when Ada.Strings.Length_Error => Handler.OK := False;
    when Constraint_Error         => Handler.OK := False;
  end Start_Element;
  --------------------------------------------

  --------------------------------------------
  overriding procedure End_Element(Handler       : in out Fsensors_Reader;
                        Namespace_URI : Unicode.CES.Byte_Sequence := "";
                        Local_Name    : Unicode.CES.Byte_Sequence := "";
                        Qname         : Unicode.CES.Byte_Sequence := "") is
    pragma Warnings(Off,Namespace_URI);
    pragma Warnings(Off,Qname);
    The_Tag : constant String := Local_Name;
  begin
    if The_Tag = Table_Fsensors_Set_Name then
      Handler.Found_Set := False;
    elsif The_Tag = Table_Fsensors_Row_Name then
      if Handler.Found_Set then
        Handler.Fsensors_List.Append(Handler.Fsensors_Data);
        Handler.Fsensors_Data := Empty_Data;
      end if;
    end if;
  exception
    when Ada.Strings.Length_Error => Handler.OK := False;
  end End_Element;
  --------------------------------------------

  --------------------------------------------
  overriding procedure Characters(Handler          : in out Fsensors_Reader;
                       Ch               : Unicode.CES.Byte_Sequence := "") is
    function To_Iso_Latin_15(Str : Unicode.CES.Byte_Sequence) return String is
      use Unicode.Encodings;
    begin
      return  Convert(Str, Get_By_Name("utf-8"), Get_By_Name("iso-8859-15"));
    end To_Iso_Latin_15;
    The_Tag   : constant String := To_String(Handler.Current_Tag);
    The_Value : constant String := To_Iso_Latin_15(Ch);
    procedure Fix_String (Value    : String;
                          Variable : in out String) is
    begin
      Append(Handler.Accumulated, Value);
      Ada.Strings.Fixed.Move(To_String(Handler.Accumulated), Variable);
    end Fix_String;
  begin
    if Handler.Found_Set then
      if The_Tag = Macaddress_Name then
       Fix_String(The_Value, Handler.Fsensors_Data.Macaddress);
      elsif The_Tag = Potname_Name then
       Fix_String(The_Value, Handler.Fsensors_Data.Potname);
      elsif The_Tag = Threshold_Name then
       Handler.Fsensors_Data.Threshold := Integer_4'value(The_Value);
      elsif The_Tag = Lastnotify_Name then
       Handler.Fsensors_Data.Lastnotify := Calendar2.To_Time_Type(The_Value(1..11), The_Value(13..24));
      elsif The_Tag = Ixxlupd_Name then
       Fix_String(The_Value, Handler.Fsensors_Data.Ixxlupd);
      elsif The_Tag = Ixxluts_Name then
       Handler.Fsensors_Data.Ixxluts := Calendar2.To_Time_Type(The_Value(1..11), The_Value(13..24));
      end if;
    end if;
  exception
    when Ada.Strings.Length_Error => Handler.OK := False;
  end Characters;

  --------------------------------------------


  function To_Map (Data : Table_Fsensors.Data_Type'class) return Table_Fsensors.Fsensors_Map_Pack_String.Map is
    Tmp_Map :  Table_Fsensors.Fsensors_Map_Pack_String.Map;
    Key : Key_Type := (others => ' ');
    Tmp_U_B_String : Unbounded_String := Null_Unbounded_String;
    Tmp_String     : String(1..1);
    pragma Warnings(Off, Tmp_String); -- used only if we have Character fields (ie String(1..1)
  begin
    Move("MACADDRESS", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Macaddress);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("POTNAME", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Potname);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("THRESHOLD", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Threshold'Img);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("LASTNOTIFY", Key);
    Tmp_U_B_String := To_Unbounded_String(String_Date_And_Time(Data.Lastnotify));
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("IXXLUPD", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Ixxlupd);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("IXXLUTS", Key);
    Tmp_U_B_String := To_Unbounded_String(String_Date_And_Time(Data.Ixxluts));
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    return Tmp_Map;
  end To_Map;
 ---------------------------


  function To_Map (Data : Table_Fsensors.Data_Type'class) return Table_Fsensors.Fsensors_Map_Pack_Column_Type.Map is
    Tmp_Map :  Table_Fsensors.Fsensors_Map_Pack_Column_Type.Map;
    Key : Column_Type;
    Tmp_U_B_String : Unbounded_String := Null_Unbounded_String;
    Tmp_String     : String(1..1);
    pragma Warnings(Off, Tmp_String); -- used only if we have Character fields (ie String(1..1)
  begin
    Key := Macaddress;
    Tmp_U_B_String := To_Unbounded_String(Data.Macaddress);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Potname;
    Tmp_U_B_String := To_Unbounded_String(Data.Potname);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Threshold;
    Tmp_U_B_String := To_Unbounded_String(Data.Threshold'Img);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Lastnotify;
    Tmp_U_B_String := To_Unbounded_String(String_Date_And_Time(Data.Lastnotify));
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Ixxlupd;
    Tmp_U_B_String := To_Unbounded_String(Data.Ixxlupd);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Ixxluts;
    Tmp_U_B_String := To_Unbounded_String(String_Date_And_Time(Data.Ixxluts));
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    return Tmp_Map;
  end To_Map;
 ---------------------------


  procedure From_Xml(Xml_Filename : in Unbounded_String;
                     A_List       : in out Fsensors_List_Pack2.List) is
    My_Reader   : Fsensors_Reader;
    Input       : File_Input;
  begin
    My_Reader.Fsensors_List := A_List;
    My_Reader.Current_Tag := Null_Unbounded_String;
    Open(To_String(Xml_Filename), Input);
    My_Reader.Set_Feature(Validation_Feature,False);
    My_Reader.Parse(Input);
    Input.Close;
    if not My_Reader.OK then
       My_Reader.Fsensors_List.Clear;
    end if;
    A_List := My_Reader.Fsensors_List;
  end From_Xml;

end Table_Fsensors;
