-----------------------------------------------------
-- This file is AUTOGENERATED by                     
-- repo                                              
--                                                   
----CHANGES HERE WILL BE LOST NEXT GENERATE!!!!----- 
-----------DO NOT EDIT THIS FILE!!!!---------------- 
-----------------------------------------------------



with Ada.Containers.Doubly_Linked_Lists;
with Ada.Containers.Hashed_Maps;
with Ada.Containers.Ordered_Maps;
with Ada.Strings;
with Ada.Strings.Hash;
with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;
with Gnatcoll.Json; use Gnatcoll.Json;
with Types, Calendar2, Sql;
with Table_Utils;  --All tables inherit from here

pragma Elaborate_All(Calendar2);



package Table_Freadings is
  use Types, Calendar2;
  --
  --  Table name as string 
  --

  Table_Freadings_Name     : constant String := "FREADINGS";
  Table_Freadings_Set_Name : constant String := "FREADINGS_SET";
  Table_Freadings_Row_Name : constant String := "FREADINGS_ROW";

  --
  -- Column names as strings
  --

  Macaddress_Name : constant String := "MACADDRESS";
  Created_Name : constant String := "CREATED";
  Reading_Name : constant String := "READING";
  Ixxlupd_Name : constant String := "IXXLUPD";
  Ixxluts_Name : constant String := "IXXLUTS";
  --
  -- Column names as enumerator literals
  --

  type Column_Type is (
    Macaddress,
    Created,
    Reading,
    Ixxlupd,
    Ixxluts);
  --
  -- The type definition
  --

  type Data_Type is new Table_Utils.Root_Table_Type with record
    Macaddress : String(1 .. 6) := (others => ' ') ; -- Primary Key
    Created : Time_Type := Time_Type_First ; -- Primary Key
    Reading : Integer_4 := 0 ; 
    Ixxlupd : String(1 .. 15) := (others => ' ') ; 
    Ixxluts : Time_Type := Time_Type_First ; 
  end record;


  -- Procedures for all DBMS

  -- Procedures for DBMS SQL
  -- Primary key
  function Get(Stm : in Sql.Statement_Type) return Table_Freadings.Data_Type;
  --------------------------------------------
  -- Primary key
  procedure Read(Data       : in out Table_Freadings.Data_Type;
                 End_Of_Set : in out Boolean);
  --------------------------------------------
  -- Primary key
  function Is_Existing(
                       Macaddress : String;
                       Created : Time_Type) 
                           return Boolean;
  --------------------------------------------
  -- Primary key
  function Get(
                       Macaddress : String;
                       Created : Time_Type)
                           return Table_Freadings.Data_Type;
  --------------------------------------------
  -- Primary key
  procedure Delete(Data : in Table_Freadings.Data_Type);
  --------------------------------------------
  -- Primary key
  procedure Update(Data : in out Table_Freadings.Data_Type; Keep_Timestamp : in Boolean := False);
  --------------------------------------------
  -- Primary key
  procedure Insert(Data : in out Table_Freadings.Data_Type; Keep_Timestamp : in Boolean := False);
  --------------------------------------------
  -- Primary key
  procedure Delete_Withcheck(Data : in Table_Freadings.Data_Type);
  --------------------------------------------
  -- Primary key
  procedure Update_Withcheck(Data : in out Table_Freadings.Data_Type; Keep_Timestamp : in Boolean := False);
  --------------------------------------------

  -- primary key index several fields
  procedure Delete_Macaddress_Created(Data  : in Table_Freadings.Data_Type);
  --------------------------------------------


  -- part of primary key index
  procedure Delete_I1_Macaddress(Data  : in     Table_Freadings.Data_Type);

  -- part of primary key index)
  function Is_Existing_I1(
      Macaddress : in String) return Boolean;

  -- part of primary key index
  procedure Delete_I1_Macaddress_Created(Data  : in     Table_Freadings.Data_Type);

  -- part of primary key index)
  function Is_Existing_I1(
      Macaddress : in String;
      Created : in Time_Type) return Boolean;




  -- Procedures for all DBMS, primitives

  function To_String(Data : in Table_Freadings.Data_Type) return String;

  function To_JSON(Data : in Table_Freadings.Data_Type) return JSON_Value;

  function From_JSON(JSON_Data : in JSON_Value) return Table_Freadings.Data_Type;

  function To_Xml(Data      : in Table_Freadings.Data_Type;
                  Ret_Start : in Boolean;
                  Ret_Data  : in Boolean;
                  Ret_End   : in Boolean) return String;


  package Freadings_List_Pack2 is new Ada.Containers.Doubly_Linked_Lists(Table_Freadings.Data_Type);

  subtype Key_Type is String(1..15);

  package Freadings_Map_Pack_String is new Ada.Containers.Hashed_Maps(
      Key_Type,
      Unbounded_String,
      Ada.Strings.Hash,
      "=",
      "=");

  package Freadings_Map_Pack_Column_Type is new Ada.Containers.Ordered_Maps(
      Column_Type,
      Unbounded_String,
      "<",
      "=");




  function To_Map (Data : Table_Freadings.Data_Type'class) return Table_Freadings.Freadings_Map_Pack_String.Map;


  function To_Map (Data : Table_Freadings.Data_Type'class) return Table_Freadings.Freadings_Map_Pack_Column_Type.Map;

  --------------------------------------------

  --------------------------------------------

  procedure Read_List(Stm  : in     Sql.Statement_Type;
                      List : in out Freadings_List_Pack2.List;
                      Max  : in     Integer_4 := Integer_4'Last);

  --------------------------------------------


  procedure Read_All(List  : in out Freadings_List_Pack2.List;
                     Order : in     Boolean := False;
                     Max   : in     Integer_4 := Integer_4'Last);
  --------------------------------------------


  procedure Read_I1_Macaddress(
                           Data  : in     Table_Freadings.Data_Type'class;
                           List  : in out Freadings_List_Pack2.List;
                           Order : in     Boolean := False;
                           Max   : in     Integer_4 := Integer_4'Last);



  procedure Read_I1_Macaddress_Created(
                           Data  : in     Table_Freadings.Data_Type'class;
                           List  : in out Freadings_List_Pack2.List;
                           Order : in     Boolean := False;
                           Max   : in     Integer_4 := Integer_4'Last);




  -- Procedures for all DBMS, others 

  procedure From_Xml(Xml_Filename : in Unbounded_String;
                     A_List       : in out Freadings_List_Pack2.List);


  Empty_Data : Table_Freadings.Data_Type;
end Table_Freadings ;
