
-----------------------------------------------------
-- This file is AUTOGENERATED by                     
-- repo                                              
--                                                   
----CHANGES HERE WILL BE LOST NEXT GENERATE!!!!----- 
-----------DO NOT EDIT THIS FILE!!!!---------------- 
-----------------------------------------------------




pragma Warnings(Off);
with Process_Io, Utils;
with Ada.Strings.Fixed; use Ada.Strings.Fixed;
with Sax.Readers;              use Sax.Readers;
with Input_Sources.File;       use Input_Sources.File;
with Unicode.CES;
with Unicode.Encodings;
with Sax.Attributes;



package body Table_Amarkets is

  Stm_Select,
  Stm_Delete,
  Stm_Update,
  Stm_Insert,
  Stm_Select_All,
  Stm_Select_All_O  : Sql.Statement_Type;


  Stm_Delete_With_Check,
  Stm_Update_With_Check  : Sql.Statement_Type;


  -- Primary keys, when several fields
  Stm_Select_I1_Marketid,
  Stm_Select_I1_Marketid_O,
  Stm_Delete_I1_Marketid : Sql.Statement_Type; 

  -- non unique index 
  Stm_Select_Count_I2_Eventid,
  Stm_Select_I2_Eventid,
  Stm_Delete_I2_Eventid,
  Stm_Select_I2_Eventid_O : Sql.Statement_Type;

  -- non unique index 
  Stm_Select_Count_I3_Markettype,
  Stm_Select_I3_Markettype,
  Stm_Delete_I3_Markettype,
  Stm_Select_I3_Markettype_O : Sql.Statement_Type;

  -- non unique index 
  Stm_Select_Count_I4_Status,
  Stm_Select_I4_Status,
  Stm_Delete_I4_Status,
  Stm_Select_I4_Status_O : Sql.Statement_Type;

  -- non unique index 
  Stm_Select_Count_I5_Numwinners,
  Stm_Select_I5_Numwinners,
  Stm_Delete_I5_Numwinners,
  Stm_Select_I5_Numwinners_O : Sql.Statement_Type;

  -- non unique index 
  Stm_Select_Count_I6_Ixxluts,
  Stm_Select_I6_Ixxluts,
  Stm_Delete_I6_Ixxluts,
  Stm_Select_I6_Ixxluts_O : Sql.Statement_Type;



  -- Procedures for all DBMS

  -- Procedures for DBMS SQL
  -- Primary key

  function Get(Stm : in Sql.Statement_Type) return Table_Amarkets.Data_Type is
    Data : Table_Amarkets.Data_Type;
  begin
    Stm.Get("MARKETID", Data.Marketid);
    Stm.Get("MARKETNAME", Data.Marketname);
    Stm.Get_Timestamp("STARTTS", Data.Startts);
    Stm.Get("EVENTID", Data.Eventid);
    Stm.Get("MARKETTYPE", Data.Markettype);
    Stm.Get("STATUS", Data.Status);
    Stm.Get("BETDELAY", Data.Betdelay);
    Stm.Get("NUMWINNERS", Data.Numwinners);
    Stm.Get("NUMRUNNERS", Data.Numrunners);
    Stm.Get("NUMACTIVERUNNERS", Data.Numactiverunners);
    Stm.Get("TOTALMATCHED", Data.Totalmatched);
    Stm.Get("TOTALAVAILABLE", Data.Totalavailable);
    Stm.Get("IXXLUPD", Data.Ixxlupd);
    Stm.Get_Timestamp("IXXLUTS", Data.Ixxluts);

    return Data;
  end Get;
---------------------------------------------


  function Get(
                  Marketid : String) return Table_Amarkets.Data_Type is
    Data       : Table_Amarkets.Data_Type;
    End_Of_Set : Boolean := True;
  begin
    Data.Marketid := Marketid;
    Data.Read(End_Of_Set);
    return Data;
  end Get;



  procedure Read_All(List  : in out Amarkets_List_Pack2.List;
                     Order : in     Boolean := False;
                     Max   : in     Integer_4 := Integer_4'Last) is
    use Sql;
    Start_Trans   : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction   : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;
    if Order then
      Stm_Select_All_O.Prepare("select * from AMARKETS order by " &
                  "MARKETID");
      Read_List(Stm_Select_All_O, List, Max);
    else
      Stm_Select_All.Prepare("select * from AMARKETS");
      Read_List(Stm_Select_All, List, Max);
    end if;
    if Start_Trans then Transaction.Commit; end if;
  end Read_All;


  procedure Read_List(Stm   : in     Sql.Statement_Type;
                      List  : in out Amarkets_List_Pack2.List;
                      Max   : in     Integer_4 := Integer_4'Last) is
    use Sql;
    Start_Trans  : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction  : Sql.Transaction_Type;
    Count        : Integer_4 := 0;
    Data         : Table_Amarkets.Data_Type;
    Eos          : Boolean := False;
  begin
    if Start_Trans then Transaction.Start; end if;
    Stm.Open_Cursor;
    loop
      Stm.Fetch(Eos);
      exit when Eos or Count > Max;
      Data := Get(Stm);
      List.Append(Data);
      Count := Count +1;
    end loop;
    Stm.Close_Cursor;
    if Start_Trans then Transaction.Commit; end if;
  end Read_List;


  function Is_Existing(
                  Marketid : String) return Boolean is
    Data       : Table_Amarkets.Data_Type;
    End_Of_Set : Boolean := True;
  begin
    Data.Marketid := Marketid;
    Read(Data, End_Of_Set);
    return not End_Of_Set;
  end Is_Existing;


  procedure Read(Data       : in out Table_Amarkets.Data_Type;
                 End_Of_Set : in out Boolean) is
    use Sql;
    Start_Trans   : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction   : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;
    Stm_Select.Prepare("select * from AMARKETS " &
                "where MARKETID =:MARKETID " &
            "");
    Stm_Select.Set("MARKETID", Data.Marketid);
    Stm_Select.Open_Cursor;
    Stm_Select.Fetch(End_Of_Set);
    if not End_Of_Set then
      Data := Get(Stm_Select);
    end if;
    Stm_Select.Close_Cursor;
    if Start_Trans then Transaction.Commit; end if;
  end Read;

  procedure Delete(Data : in Table_Amarkets.Data_Type) is
  begin
    Stm_Delete.Prepare("delete from AMARKETS " &
                "where MARKETID =:MARKETID " &
            "");
    Stm_Delete.Set("MARKETID", Data.Marketid);
    Stm_Delete.Execute;
  end Delete;

  procedure Update(Data : in out Table_Amarkets.Data_Type ; Keep_Timestamp : in Boolean := False) is
    Now     : Calendar2.Time_Type := Calendar2.Clock;
    Process : Process_Io.Process_Type     := Process_Io.This_Process;
  begin
    Stm_Update.Prepare("update AMARKETS set  " &
            "MARKETNAME=:MARKETNAME, " &
            "STARTTS=:STARTTS, " &
            "EVENTID=:EVENTID, " &
            "MARKETTYPE=:MARKETTYPE, " &
            "STATUS=:STATUS, " &
            "BETDELAY=:BETDELAY, " &
            "NUMWINNERS=:NUMWINNERS, " &
            "NUMRUNNERS=:NUMRUNNERS, " &
            "NUMACTIVERUNNERS=:NUMACTIVERUNNERS, " &
            "TOTALMATCHED=:TOTALMATCHED, " &
            "TOTALAVAILABLE=:TOTALAVAILABLE, " &
            "IXXLUPD=:IXXLUPD, " &
            "IXXLUTS=:IXXLUTS " &
            "where MARKETID=:MARKETID " &
            "");

    if not Keep_Timestamp then
      Data.Ixxluts := Now;
    end if;
      Stm_Update.Set("MARKETNAME", Data.Marketname);
      Stm_Update.Set_Timestamp("STARTTS", Data.Startts);
      Stm_Update.Set("EVENTID", Data.Eventid);
      Stm_Update.Set("MARKETTYPE", Data.Markettype);
      Stm_Update.Set("STATUS", Data.Status);
      Stm_Update.Set("BETDELAY", Data.Betdelay);
      Stm_Update.Set("NUMWINNERS", Data.Numwinners);
      Stm_Update.Set("NUMRUNNERS", Data.Numrunners);
      Stm_Update.Set("NUMACTIVERUNNERS", Data.Numactiverunners);
      Stm_Update.Set("TOTALMATCHED", Data.Totalmatched);
      Stm_Update.Set("TOTALAVAILABLE", Data.Totalavailable);
    if not Keep_Timestamp then
      null; --for tables without Ixxlupd
      Data.Ixxlupd := Process.Name(1..15);
    end if;
      Stm_Update.Set("IXXLUPD", Data.Ixxlupd);
      Stm_Update.Set_Timestamp("IXXLUTS", Data.Ixxluts);
    Stm_Update.Set("MARKETID", Data.Marketid);
    Stm_Update.Execute;
  end Update;

  procedure Insert(Data : in out Table_Amarkets.Data_Type; Keep_Timestamp : in Boolean := False) is
    Now     : Calendar2.Time_Type := Calendar2.Clock;
    Process : Process_Io.Process_Type     := Process_Io.This_Process;
  begin
    if not Keep_Timestamp then
      Data.Ixxluts := Now;
    end if;
    Stm_Insert.Prepare("insert into AMARKETS values (" &
         ":MARKETID," &
         ":MARKETNAME," &
         ":STARTTS," &
         ":EVENTID," &
         ":MARKETTYPE," &
         ":STATUS," &
         ":BETDELAY," &
         ":NUMWINNERS," &
         ":NUMRUNNERS," &
         ":NUMACTIVERUNNERS," &
         ":TOTALMATCHED," &
         ":TOTALAVAILABLE," &
         ":IXXLUPD," &
         ":IXXLUTS)");

    if not Keep_Timestamp then
      Data.Ixxluts := Now;
    end if;
      Stm_Insert.Set("MARKETID", Data.Marketid);
      Stm_Insert.Set("MARKETNAME", Data.Marketname);
      Stm_Insert.Set_Timestamp("STARTTS", Data.Startts);
      Stm_Insert.Set("EVENTID", Data.Eventid);
      Stm_Insert.Set("MARKETTYPE", Data.Markettype);
      Stm_Insert.Set("STATUS", Data.Status);
      Stm_Insert.Set("BETDELAY", Data.Betdelay);
      Stm_Insert.Set("NUMWINNERS", Data.Numwinners);
      Stm_Insert.Set("NUMRUNNERS", Data.Numrunners);
      Stm_Insert.Set("NUMACTIVERUNNERS", Data.Numactiverunners);
      Stm_Insert.Set("TOTALMATCHED", Data.Totalmatched);
      Stm_Insert.Set("TOTALAVAILABLE", Data.Totalavailable);
    if not Keep_Timestamp then
      null; --for tables without Ixxlupd
      Data.Ixxlupd := Process.Name(1..15);
    end if;
      Stm_Insert.Set("IXXLUPD", Data.Ixxlupd);
      Stm_Insert.Set_Timestamp("IXXLUTS", Data.Ixxluts);
    Stm_Insert.Execute;
  end Insert;
--------------------------------------------
  procedure Delete_Withcheck(Data : in Table_Amarkets.Data_Type) is
  begin
    Stm_Delete_With_Check.Prepare("delete from AMARKETS " &
                "where MARKETID =:MARKETID " &
            "and IXXLUPD = :IXXLUPD " &
            "and IXXLUTS = :IXXLUTS " &
            "");
    Stm_Delete_With_Check.Set("MARKETID", Data.Marketid);
    Stm_Delete_With_Check.Set("IXXLUPD", Data.Ixxlupd);
    Stm_Delete_With_Check.Set_Timestamp("IXXLUTS", Data.Ixxluts);
    Stm_Delete_With_Check.Execute;
  end Delete_Withcheck;
--------------------------------------------
  procedure Update_Withcheck(Data : in out Table_Amarkets.Data_Type; Keep_Timestamp : in Boolean := False) is
    Now     : Calendar2.Time_Type := Calendar2.Clock;
    Process : Process_Io.Process_Type     := Process_Io.This_Process;
  begin
    Stm_Update_With_Check.Prepare("update AMARKETS set  " &
            "MARKETNAME=:MARKETNAME, " &
            "STARTTS=:STARTTS, " &
            "EVENTID=:EVENTID, " &
            "MARKETTYPE=:MARKETTYPE, " &
            "STATUS=:STATUS, " &
            "BETDELAY=:BETDELAY, " &
            "NUMWINNERS=:NUMWINNERS, " &
            "NUMRUNNERS=:NUMRUNNERS, " &
            "NUMACTIVERUNNERS=:NUMACTIVERUNNERS, " &
            "TOTALMATCHED=:TOTALMATCHED, " &
            "TOTALAVAILABLE=:TOTALAVAILABLE, " &
            "IXXLUPD=:IXXLUPD, " &
            "IXXLUTS=:IXXLUTS " &
            "where MARKETID=:MARKETID " &
    "and IXXLUPD = :OLD_IXXLUPD " &
    "and IXXLUTS = :OLD_IXXLUTS " &
            "");
    Stm_Update_With_Check.Set("MARKETID", Data.Marketid);
    Stm_Update_With_Check.Set("OLD_IXXLUPD", Data.Ixxlupd );
    Stm_Update_With_Check.Set_Timestamp("OLD_IXXLUTS", Data.Ixxluts );

    if not Keep_Timestamp then
      Data.Ixxluts := Now;
    end if;
      Stm_Update_With_Check.Set("MARKETNAME", Data.Marketname);
      Stm_Update_With_Check.Set_Timestamp("STARTTS", Data.Startts);
      Stm_Update_With_Check.Set("EVENTID", Data.Eventid);
      Stm_Update_With_Check.Set("MARKETTYPE", Data.Markettype);
      Stm_Update_With_Check.Set("STATUS", Data.Status);
      Stm_Update_With_Check.Set("BETDELAY", Data.Betdelay);
      Stm_Update_With_Check.Set("NUMWINNERS", Data.Numwinners);
      Stm_Update_With_Check.Set("NUMRUNNERS", Data.Numrunners);
      Stm_Update_With_Check.Set("NUMACTIVERUNNERS", Data.Numactiverunners);
      Stm_Update_With_Check.Set("TOTALMATCHED", Data.Totalmatched);
      Stm_Update_With_Check.Set("TOTALAVAILABLE", Data.Totalavailable);
    if not Keep_Timestamp then
      null; --for tables without Ixxlupd
      Data.Ixxlupd := Process.Name(1..15);
    end if;
      Stm_Update_With_Check.Set("IXXLUPD", Data.Ixxlupd);
      Stm_Update_With_Check.Set_Timestamp("IXXLUTS", Data.Ixxluts);
    Stm_Update_With_Check.Execute;
  end Update_Withcheck;
--------------------------------------------
   -- stop Print_Def_Functions_Body.Primary_Procs_Body


  -- non unique index
  procedure Read_One_Eventid(
                           Data       : in out Table_Amarkets.Data_Type;
                           Order      : in     Boolean := False;
                           End_Of_Set : in out Boolean) is
    List : Amarkets_List_Pack2.List;
  begin
    Data.Read_Eventid(List, Order, 1);
    if List.Is_Empty then
      End_Of_Set := True;
    else
      End_Of_Set := False;
      Data := List.First_Element;
    end if;
    List.Clear;
  end Read_One_Eventid;
  --------------------------------------------

  -- non unique index
  function Count_Eventid(Data : Table_Amarkets.Data_Type) return Integer_4 is
    use Sql;
    Count       : Integer_4 := 0;
    End_Of_Set  : Boolean := False;
    Start_Trans : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;

    Stm_Select_Count_I2_Eventid.Prepare("select count('a') from AMARKETS " &
                "where EVENTID =:EVENTID " &
            "");
    Stm_Select_Count_I2_Eventid.Set("EVENTID", Data.Eventid);

    Stm_Select_Count_I2_Eventid.Open_Cursor;
    Stm_Select_Count_I2_Eventid.Fetch(End_Of_Set);
    if not End_Of_Set then
      Stm_Select_Count_I2_Eventid.Get(1, Count);
    end if;
    Stm_Select_Count_I2_Eventid.Close_Cursor;
    if Start_Trans then Transaction.Commit; end if;
    return Count;
  end Count_Eventid;
  --------------------------------------------

  -- non unique index
  procedure Delete_Eventid(Data  : in     Table_Amarkets.Data_Type) is
  begin

    Stm_Delete_I2_Eventid.Prepare("delete from AMARKETS " &
                "where EVENTID =:EVENTID " &
            "");
    Stm_Delete_I2_Eventid.Set("EVENTID", Data.Eventid);

    Stm_Delete_I2_Eventid.Execute;
  end Delete_Eventid;

  --------------------------------------------

  -- non unique index
  function Is_Existing_I2(Eventid : in String) return Boolean is
    Data       : Table_Amarkets.Data_Type;
    Exists     : Boolean := False;
    List       : Amarkets_List_Pack2.List;
  begin
    Data.Eventid := Eventid;
    Read_Eventid(Data, List, False, 1);
    Exists := not List.Is_Empty;
    List.Clear;
    return Exists;
  end Is_Existing_I2;
  --------------------------------------------




  -- non unique index
  procedure Read_One_Markettype(
                           Data       : in out Table_Amarkets.Data_Type;
                           Order      : in     Boolean := False;
                           End_Of_Set : in out Boolean) is
    List : Amarkets_List_Pack2.List;
  begin
    Data.Read_Markettype(List, Order, 1);
    if List.Is_Empty then
      End_Of_Set := True;
    else
      End_Of_Set := False;
      Data := List.First_Element;
    end if;
    List.Clear;
  end Read_One_Markettype;
  --------------------------------------------

  -- non unique index
  function Count_Markettype(Data : Table_Amarkets.Data_Type) return Integer_4 is
    use Sql;
    Count       : Integer_4 := 0;
    End_Of_Set  : Boolean := False;
    Start_Trans : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;

    Stm_Select_Count_I3_Markettype.Prepare("select count('a') from AMARKETS " &
                "where MARKETTYPE =:MARKETTYPE " &
            "");
    Stm_Select_Count_I3_Markettype.Set("MARKETTYPE", Data.Markettype);

    Stm_Select_Count_I3_Markettype.Open_Cursor;
    Stm_Select_Count_I3_Markettype.Fetch(End_Of_Set);
    if not End_Of_Set then
      Stm_Select_Count_I3_Markettype.Get(1, Count);
    end if;
    Stm_Select_Count_I3_Markettype.Close_Cursor;
    if Start_Trans then Transaction.Commit; end if;
    return Count;
  end Count_Markettype;
  --------------------------------------------

  -- non unique index
  procedure Delete_Markettype(Data  : in     Table_Amarkets.Data_Type) is
  begin

    Stm_Delete_I3_Markettype.Prepare("delete from AMARKETS " &
                "where MARKETTYPE =:MARKETTYPE " &
            "");
    Stm_Delete_I3_Markettype.Set("MARKETTYPE", Data.Markettype);

    Stm_Delete_I3_Markettype.Execute;
  end Delete_Markettype;

  --------------------------------------------

  -- non unique index
  function Is_Existing_I3(Markettype : in String) return Boolean is
    Data       : Table_Amarkets.Data_Type;
    Exists     : Boolean := False;
    List       : Amarkets_List_Pack2.List;
  begin
    Data.Markettype := Markettype;
    Read_Markettype(Data, List, False, 1);
    Exists := not List.Is_Empty;
    List.Clear;
    return Exists;
  end Is_Existing_I3;
  --------------------------------------------




  -- non unique index
  procedure Read_One_Status(
                           Data       : in out Table_Amarkets.Data_Type;
                           Order      : in     Boolean := False;
                           End_Of_Set : in out Boolean) is
    List : Amarkets_List_Pack2.List;
  begin
    Data.Read_Status(List, Order, 1);
    if List.Is_Empty then
      End_Of_Set := True;
    else
      End_Of_Set := False;
      Data := List.First_Element;
    end if;
    List.Clear;
  end Read_One_Status;
  --------------------------------------------

  -- non unique index
  function Count_Status(Data : Table_Amarkets.Data_Type) return Integer_4 is
    use Sql;
    Count       : Integer_4 := 0;
    End_Of_Set  : Boolean := False;
    Start_Trans : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;

    Stm_Select_Count_I4_Status.Prepare("select count('a') from AMARKETS " &
                "where STATUS =:STATUS " &
            "");
    Stm_Select_Count_I4_Status.Set("STATUS", Data.Status);

    Stm_Select_Count_I4_Status.Open_Cursor;
    Stm_Select_Count_I4_Status.Fetch(End_Of_Set);
    if not End_Of_Set then
      Stm_Select_Count_I4_Status.Get(1, Count);
    end if;
    Stm_Select_Count_I4_Status.Close_Cursor;
    if Start_Trans then Transaction.Commit; end if;
    return Count;
  end Count_Status;
  --------------------------------------------

  -- non unique index
  procedure Delete_Status(Data  : in     Table_Amarkets.Data_Type) is
  begin

    Stm_Delete_I4_Status.Prepare("delete from AMARKETS " &
                "where STATUS =:STATUS " &
            "");
    Stm_Delete_I4_Status.Set("STATUS", Data.Status);

    Stm_Delete_I4_Status.Execute;
  end Delete_Status;

  --------------------------------------------

  -- non unique index
  function Is_Existing_I4(Status : in String) return Boolean is
    Data       : Table_Amarkets.Data_Type;
    Exists     : Boolean := False;
    List       : Amarkets_List_Pack2.List;
  begin
    Data.Status := Status;
    Read_Status(Data, List, False, 1);
    Exists := not List.Is_Empty;
    List.Clear;
    return Exists;
  end Is_Existing_I4;
  --------------------------------------------




  -- non unique index
  procedure Read_One_Numwinners(
                           Data       : in out Table_Amarkets.Data_Type;
                           Order      : in     Boolean := False;
                           End_Of_Set : in out Boolean) is
    List : Amarkets_List_Pack2.List;
  begin
    Data.Read_Numwinners(List, Order, 1);
    if List.Is_Empty then
      End_Of_Set := True;
    else
      End_Of_Set := False;
      Data := List.First_Element;
    end if;
    List.Clear;
  end Read_One_Numwinners;
  --------------------------------------------

  -- non unique index
  function Count_Numwinners(Data : Table_Amarkets.Data_Type) return Integer_4 is
    use Sql;
    Count       : Integer_4 := 0;
    End_Of_Set  : Boolean := False;
    Start_Trans : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;

    Stm_Select_Count_I5_Numwinners.Prepare("select count('a') from AMARKETS " &
                "where NUMWINNERS =:NUMWINNERS " &
            "");
    Stm_Select_Count_I5_Numwinners.Set("NUMWINNERS", Data.Numwinners);

    Stm_Select_Count_I5_Numwinners.Open_Cursor;
    Stm_Select_Count_I5_Numwinners.Fetch(End_Of_Set);
    if not End_Of_Set then
      Stm_Select_Count_I5_Numwinners.Get(1, Count);
    end if;
    Stm_Select_Count_I5_Numwinners.Close_Cursor;
    if Start_Trans then Transaction.Commit; end if;
    return Count;
  end Count_Numwinners;
  --------------------------------------------

  -- non unique index
  procedure Delete_Numwinners(Data  : in     Table_Amarkets.Data_Type) is
  begin

    Stm_Delete_I5_Numwinners.Prepare("delete from AMARKETS " &
                "where NUMWINNERS =:NUMWINNERS " &
            "");
    Stm_Delete_I5_Numwinners.Set("NUMWINNERS", Data.Numwinners);

    Stm_Delete_I5_Numwinners.Execute;
  end Delete_Numwinners;

  --------------------------------------------

  -- non unique index
  function Is_Existing_I5(Numwinners : in Integer_4) return Boolean is
    Data       : Table_Amarkets.Data_Type;
    Exists     : Boolean := False;
    List       : Amarkets_List_Pack2.List;
  begin
    Data.Numwinners := Numwinners;
    Read_Numwinners(Data, List, False, 1);
    Exists := not List.Is_Empty;
    List.Clear;
    return Exists;
  end Is_Existing_I5;
  --------------------------------------------




  -- non unique index
  procedure Read_One_Ixxluts(
                           Data       : in out Table_Amarkets.Data_Type;
                           Order      : in     Boolean := False;
                           End_Of_Set : in out Boolean) is
    List : Amarkets_List_Pack2.List;
  begin
    Data.Read_Ixxluts(List, Order, 1);
    if List.Is_Empty then
      End_Of_Set := True;
    else
      End_Of_Set := False;
      Data := List.First_Element;
    end if;
    List.Clear;
  end Read_One_Ixxluts;
  --------------------------------------------

  -- non unique index
  function Count_Ixxluts(Data : Table_Amarkets.Data_Type) return Integer_4 is
    use Sql;
    Count       : Integer_4 := 0;
    End_Of_Set  : Boolean := False;
    Start_Trans : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;

    Stm_Select_Count_I6_Ixxluts.Prepare("select count('a') from AMARKETS " &
                "where IXXLUTS =:IXXLUTS " &
            "");
    Stm_Select_Count_I6_Ixxluts.Set_Timestamp("IXXLUTS", Data.Ixxluts);

    Stm_Select_Count_I6_Ixxluts.Open_Cursor;
    Stm_Select_Count_I6_Ixxluts.Fetch(End_Of_Set);
    if not End_Of_Set then
      Stm_Select_Count_I6_Ixxluts.Get(1, Count);
    end if;
    Stm_Select_Count_I6_Ixxluts.Close_Cursor;
    if Start_Trans then Transaction.Commit; end if;
    return Count;
  end Count_Ixxluts;
  --------------------------------------------

  -- non unique index
  procedure Delete_Ixxluts(Data  : in     Table_Amarkets.Data_Type) is
  begin

    Stm_Delete_I6_Ixxluts.Prepare("delete from AMARKETS " &
                "where IXXLUTS =:IXXLUTS " &
            "");
    Stm_Delete_I6_Ixxluts.Set_Timestamp("IXXLUTS", Data.Ixxluts);

    Stm_Delete_I6_Ixxluts.Execute;
  end Delete_Ixxluts;

  --------------------------------------------

  -- non unique index
  function Is_Existing_I6(Ixxluts : in Time_Type) return Boolean is
    Data       : Table_Amarkets.Data_Type;
    Exists     : Boolean := False;
    List       : Amarkets_List_Pack2.List;
  begin
    Data.Ixxluts := Ixxluts;
    Read_Ixxluts(Data, List, False, 1);
    Exists := not List.Is_Empty;
    List.Clear;
    return Exists;
  end Is_Existing_I6;
  --------------------------------------------





  -- Procedures for all DBMS


  function To_String(Data : in Table_Amarkets.Data_Type) return String is
  begin
    return
          "Marketid = " & Utils.Trim(Data.Marketid) & " " &
          "Marketname = " & Utils.Trim(Data.Marketname) & " " &
          "Startts = " & Calendar2.String_Date_And_Time(Data.Startts, Milliseconds => True ) & " " &
          "Eventid = " & Utils.Trim(Data.Eventid) & " " &
          "Markettype = " & Utils.Trim(Data.Markettype) & " " &
          "Status = " & Utils.Trim(Data.Status) & " " &
          "Betdelay = " & Utils.Trim(Data.Betdelay'Img) & " " &
          "Numwinners = " & Utils.Trim(Data.Numwinners'Img) & " " &
          "Numrunners = " & Utils.Trim(Data.Numrunners'Img) & " " &
          "Numactiverunners = " & Utils.Trim(Data.Numactiverunners'Img) & " " &
          "Totalmatched = " & Utils.F8_Image(Data.Totalmatched) & " " &
          "Totalavailable = " & Utils.F8_Image(Data.Totalavailable) & " " &
          "Ixxlupd = " & Utils.Trim(Data.Ixxlupd) & " " &
          "Ixxluts = " & Calendar2.String_Date_And_Time(Data.Ixxluts, Milliseconds => True ) & " " &
          "";
  end To_String;

  function To_JSON(Data : in Table_Amarkets.Data_Type) return JSON_Value is
    Json_Data : JSON_Value := Create_Object;
  begin
    Json_Data.Set_Field(Field_Name => "marketid", Field => Utils.Trim(Data.Marketid));
    Json_Data.Set_Field(Field_Name => "marketname", Field => Utils.Trim(Data.Marketname));
    Json_Data.Set_Field(Field_Name => "startts", Field => Data.Startts.To_String);
    Json_Data.Set_Field(Field_Name => "eventid", Field => Utils.Trim(Data.Eventid));
    Json_Data.Set_Field(Field_Name => "markettype", Field => Utils.Trim(Data.Markettype));
    Json_Data.Set_Field(Field_Name => "status", Field => Utils.Trim(Data.Status));
    Json_Data.Set_Field(Field_Name => "betdelay", Field => Long_Integer(Data.Betdelay));
    Json_Data.Set_Field(Field_Name => "numwinners", Field => Long_Integer(Data.Numwinners));
    Json_Data.Set_Field(Field_Name => "numrunners", Field => Long_Integer(Data.Numrunners));
    Json_Data.Set_Field(Field_Name => "numactiverunners", Field => Long_Integer(Data.Numactiverunners));
    Json_Data.Set_Field(Field_Name => "totalmatched", Field => Float(Data.Totalmatched));
    Json_Data.Set_Field(Field_Name => "totalavailable", Field => Float(Data.Totalavailable));
    Json_Data.Set_Field(Field_Name => "ixxlupd", Field => Utils.Trim(Data.Ixxlupd));
    Json_Data.Set_Field(Field_Name => "ixxluts", Field => Data.Ixxluts.To_String);
    return Json_Data;
  end To_JSON;

  function From_JSON(JSON_Data : in JSON_Value) return Table_Amarkets.Data_Type is
    use Ada.Strings;
    Data : Table_Amarkets.Data_Type;
  begin
    if JSON_Data.Has_Field("marketid") then
      Move( Source => JSON_Data.Get("marketid"), Target => Data.Marketid , Drop => Right);
    end if;

    if JSON_Data.Has_Field("marketname") then
      Move( Source => JSON_Data.Get("marketname"), Target => Data.Marketname , Drop => Right);
    end if;

    if JSON_Data.Has_Field("startts") then
      declare
        Tmp : String := JSON_Data.Get("startts");
      begin  -- "marketStartTime":"2013-06-22T17:39:00.000Z"
        Data.Startts := Calendar2.To_Time_Type(Tmp(1..10), Tmp(12..23));
      end;
    end if;

    if JSON_Data.Has_Field("eventid") then
      Move( Source => JSON_Data.Get("eventid"), Target => Data.Eventid , Drop => Right);
    end if;

    if JSON_Data.Has_Field("markettype") then
      Move( Source => JSON_Data.Get("markettype"), Target => Data.Markettype , Drop => Right);
    end if;

    if JSON_Data.Has_Field("status") then
      Move( Source => JSON_Data.Get("status"), Target => Data.Status , Drop => Right);
    end if;

    if JSON_Data.Has_Field("betdelay") then
      declare
        Tmp : Long_Integer := 0;
      begin
        Tmp := JSON_Data.Get("betdelay");
        Data.Betdelay := Integer_4(Tmp);
      end;
    end if;

    if JSON_Data.Has_Field("numwinners") then
      declare
        Tmp : Long_Integer := 0;
      begin
        Tmp := JSON_Data.Get("numwinners");
        Data.Numwinners := Integer_4(Tmp);
      end;
    end if;

    if JSON_Data.Has_Field("numrunners") then
      declare
        Tmp : Long_Integer := 0;
      begin
        Tmp := JSON_Data.Get("numrunners");
        Data.Numrunners := Integer_4(Tmp);
      end;
    end if;

    if JSON_Data.Has_Field("numactiverunners") then
      declare
        Tmp : Long_Integer := 0;
      begin
        Tmp := JSON_Data.Get("numactiverunners");
        Data.Numactiverunners := Integer_4(Tmp);
      end;
    end if;

    if JSON_Data.Has_Field("totalmatched") then
      declare
        Tmp : Float := 0.0;
      begin
        Tmp := JSON_Data.Get("totalmatched");
        Data.Totalmatched := Fixed_Type(Tmp);
      end;
    end if;

    if JSON_Data.Has_Field("totalavailable") then
      declare
        Tmp : Float := 0.0;
      begin
        Tmp := JSON_Data.Get("totalavailable");
        Data.Totalavailable := Fixed_Type(Tmp);
      end;
    end if;

    if JSON_Data.Has_Field("ixxlupd") then
      Move( Source => JSON_Data.Get("ixxlupd"), Target => Data.Ixxlupd , Drop => Right);
    end if;

    if JSON_Data.Has_Field("ixxluts") then
      declare
        Tmp : String := JSON_Data.Get("ixxluts");
      begin  -- "marketStartTime":"2013-06-22T17:39:00.000Z"
        Data.Ixxluts := Calendar2.To_Time_Type(Tmp(1..10), Tmp(12..23));
      end;
    end if;

    return Data;
  end From_JSON;

  function To_Xml(Data      : in Table_Amarkets.Data_Type;
                  Ret_Start : in Boolean;
                  Ret_Data  : in Boolean;
                  Ret_End   : in Boolean) return String is
    Ls      : constant String := "";
    S_Start : constant String := "<AMARKETS_ROW>" & Ls;
    S_End   : constant String := "</AMARKETS_ROW>" & Ls;
    S1 : constant String :=
          "<MARKETID>" & Utils.Trim(Data.Marketid) & "</MARKETID>" & Ls;
    S2 : constant String :=
          "<MARKETNAME>" & Utils.Trim(Data.Marketname) & "</MARKETNAME>" & Ls;
    S3 : constant String :=
          "<STARTTS>" & Calendar2.String_Date_And_Time(Data.Startts, Milliseconds => True) & "</STARTTS>" & Ls;
    S4 : constant String :=
          "<EVENTID>" & Utils.Trim(Data.Eventid) & "</EVENTID>" & Ls;
    S5 : constant String :=
          "<MARKETTYPE>" & Utils.Trim(Data.Markettype) & "</MARKETTYPE>" & Ls;
    S6 : constant String :=
          "<STATUS>" & Utils.Trim(Data.Status) & "</STATUS>" & Ls;
    S7 : constant String :=
          "<BETDELAY>" & Utils.Trim(Data.Betdelay'Img) & "</BETDELAY>" & Ls;
    S8 : constant String :=
          "<NUMWINNERS>" & Utils.Trim(Data.Numwinners'Img) & "</NUMWINNERS>" & Ls;
    S9 : constant String :=
          "<NUMRUNNERS>" & Utils.Trim(Data.Numrunners'Img) & "</NUMRUNNERS>" & Ls;
    S10 : constant String :=
          "<NUMACTIVERUNNERS>" & Utils.Trim(Data.Numactiverunners'Img) & "</NUMACTIVERUNNERS>" & Ls;
    S11 : constant String :=
          "<TOTALMATCHED>" & Utils.F8_Image(Data.Totalmatched) & "</TOTALMATCHED>" & Ls;
    S12 : constant String :=
          "<TOTALAVAILABLE>" & Utils.F8_Image(Data.Totalavailable) & "</TOTALAVAILABLE>" & Ls;
    S13 : constant String :=
          "<IXXLUPD>" & Utils.Trim(Data.Ixxlupd) & "</IXXLUPD>" & Ls;
    S14 : constant String :=
          "<IXXLUTS>" & Calendar2.String_Date_And_Time(Data.Ixxluts, Milliseconds => True) & "</IXXLUTS>" & Ls;
    --------------------------------
    function Get_String(S : in String; Ret : in Boolean) return String is
    begin
      if Ret then return S; else return ""; end if;
    end Get_String;
    --------------------------------
  begin
    return Get_String(S_Start, Ret_Start) & 
           Get_String(
                       S1 &  S2 &  S3 &  S4 &  S5 &  S6 &  S7 &  S8 &  S9 &  S10 &  S11 &  S12 &  S13 &  S14 , Ret_Data) &
           Get_String(S_End, Ret_End) & Ascii.LF;
  end To_Xml;
    --------------------------------

  --------------------------------------------
  type Amarkets_Reader is new Sax.Readers.Reader with record
    Current_Tag    : Unbounded_String := Null_Unbounded_String;
    Accumulated    : Unbounded_String := Null_Unbounded_String;
    OK             : Boolean := True;
    Found_Set      : Boolean := True;
    Amarkets_List     : Table_Amarkets.Amarkets_List_Pack2.List;
    Amarkets_Data     : Table_Amarkets.Data_Type := Empty_Data;
  end record;

  overriding procedure Start_Element(Handler       : in out Amarkets_Reader;
                                     Namespace_URI : Unicode.CES.Byte_Sequence := "";
                                     Local_Name    : Unicode.CES.Byte_Sequence := "";
                                     Qname         : Unicode.CES.Byte_Sequence := "";
                                     Atts          : Sax.Attributes.Attributes'Class);

  overriding procedure End_Element(Handler         : in out Amarkets_Reader;
                                   Namespace_URI   : Unicode.CES.Byte_Sequence := "";
                                   Local_Name      : Unicode.CES.Byte_Sequence := "";
                                   Qname           : Unicode.CES.Byte_Sequence := "");

  overriding procedure Characters(Handler          : in out Amarkets_Reader;
                                  Ch               : Unicode.CES.Byte_Sequence := "");

  --------------------------------------------
  overriding procedure Start_Element(Handler       : in out Amarkets_Reader;
                          Namespace_URI : Unicode.CES.Byte_Sequence := "";
                          Local_Name    : Unicode.CES.Byte_Sequence := "";
                          Qname         : Unicode.CES.Byte_Sequence := "";
                          Atts          : Sax.Attributes.Attributes'Class) is
    pragma Warnings(Off,Namespace_URI);
    pragma Warnings(Off,Qname);
    pragma Warnings(Off,Atts);
    The_Tag : constant String := Local_Name;
  begin
    Handler.Current_Tag := To_Unbounded_String(The_Tag);
    Handler.Accumulated := Null_Unbounded_String;
    if The_Tag = Table_Amarkets_Set_Name then
      Handler.Found_Set := True;
    end if;
  exception
    when Ada.Strings.Length_Error => Handler.OK := False;
    when Constraint_Error         => Handler.OK := False;
  end Start_Element;
  --------------------------------------------

  --------------------------------------------
  overriding procedure End_Element(Handler       : in out Amarkets_Reader;
                        Namespace_URI : Unicode.CES.Byte_Sequence := "";
                        Local_Name    : Unicode.CES.Byte_Sequence := "";
                        Qname         : Unicode.CES.Byte_Sequence := "") is
    pragma Warnings(Off,Namespace_URI);
    pragma Warnings(Off,Qname);
    The_Tag : constant String := Local_Name;
  begin
    if The_Tag = Table_Amarkets_Set_Name then
      Handler.Found_Set := False;
    elsif The_Tag = Table_Amarkets_Row_Name then
      if Handler.Found_Set then
        Handler.Amarkets_List.Append(Handler.Amarkets_Data);
        Handler.Amarkets_Data := Empty_Data;
      end if;
    end if;
  exception
    when Ada.Strings.Length_Error => Handler.OK := False;
  end End_Element;
  --------------------------------------------

  --------------------------------------------
  overriding procedure Characters(Handler          : in out Amarkets_Reader;
                       Ch               : Unicode.CES.Byte_Sequence := "") is
    function To_Iso_Latin_15(Str : Unicode.CES.Byte_Sequence) return String is
      use Unicode.Encodings;
    begin
      return  Convert(Str, Get_By_Name("utf-8"), Get_By_Name("iso-8859-15"));
    end To_Iso_Latin_15;
    The_Tag   : constant String := To_String(Handler.Current_Tag);
    The_Value : constant String := To_Iso_Latin_15(Ch);
    procedure Fix_String (Value    : String;
                          Variable : in out String) is
    begin
      Append(Handler.Accumulated, Value);
      Ada.Strings.Fixed.Move(To_String(Handler.Accumulated), Variable);
    end Fix_String;
  begin
    if Handler.Found_Set then
      if The_Tag = Marketid_Name then
       Fix_String(The_Value, Handler.Amarkets_Data.Marketid);
      elsif The_Tag = Marketname_Name then
       Fix_String(The_Value, Handler.Amarkets_Data.Marketname);
      elsif The_Tag = Startts_Name then
       Handler.Amarkets_Data.Startts := Calendar2.To_Time_Type(The_Value(1..11), The_Value(13..24));
      elsif The_Tag = Eventid_Name then
       Fix_String(The_Value, Handler.Amarkets_Data.Eventid);
      elsif The_Tag = Markettype_Name then
       Fix_String(The_Value, Handler.Amarkets_Data.Markettype);
      elsif The_Tag = Status_Name then
       Fix_String(The_Value, Handler.Amarkets_Data.Status);
      elsif The_Tag = Betdelay_Name then
       Handler.Amarkets_Data.Betdelay := Integer_4'value(The_Value);
      elsif The_Tag = Numwinners_Name then
       Handler.Amarkets_Data.Numwinners := Integer_4'value(The_Value);
      elsif The_Tag = Numrunners_Name then
       Handler.Amarkets_Data.Numrunners := Integer_4'value(The_Value);
      elsif The_Tag = Numactiverunners_Name then
       Handler.Amarkets_Data.Numactiverunners := Integer_4'value(The_Value);
      elsif The_Tag = Totalmatched_Name then
       Handler.Amarkets_Data.Totalmatched := Fixed_Type'value(The_Value);
      elsif The_Tag = Totalavailable_Name then
       Handler.Amarkets_Data.Totalavailable := Fixed_Type'value(The_Value);
      elsif The_Tag = Ixxlupd_Name then
       Fix_String(The_Value, Handler.Amarkets_Data.Ixxlupd);
      elsif The_Tag = Ixxluts_Name then
       Handler.Amarkets_Data.Ixxluts := Calendar2.To_Time_Type(The_Value(1..11), The_Value(13..24));
      end if;
    end if;
  exception
    when Ada.Strings.Length_Error => Handler.OK := False;
  end Characters;

  --------------------------------------------


  function To_Map (Data : Table_Amarkets.Data_Type'class) return Table_Amarkets.Amarkets_Map_Pack_String.Map is
    Tmp_Map :  Table_Amarkets.Amarkets_Map_Pack_String.Map;
    Key : Key_Type := (others => ' ');
    Tmp_U_B_String : Unbounded_String := Null_Unbounded_String;
    Tmp_String     : String(1..1);
    pragma Warnings(Off, Tmp_String); -- used only if we have Character fields (ie String(1..1)
  begin
    Move("MARKETID", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Marketid);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("MARKETNAME", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Marketname);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("STARTTS", Key);
    Tmp_U_B_String := To_Unbounded_String(String_Date_And_Time(Data.Startts));
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("EVENTID", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Eventid);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("MARKETTYPE", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Markettype);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("STATUS", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Status);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("BETDELAY", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Betdelay'Img);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("NUMWINNERS", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Numwinners'Img);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("NUMRUNNERS", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Numrunners'Img);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("NUMACTIVERUNNERS", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Numactiverunners'Img);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("TOTALMATCHED", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Totalmatched'Img);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("TOTALAVAILABLE", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Totalavailable'Img);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("IXXLUPD", Key);
    Tmp_U_B_String := To_Unbounded_String(Data.Ixxlupd);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Move("IXXLUTS", Key);
    Tmp_U_B_String := To_Unbounded_String(String_Date_And_Time(Data.Ixxluts));
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    return Tmp_Map;
  end To_Map;
 ---------------------------


  function To_Map (Data : Table_Amarkets.Data_Type'class) return Table_Amarkets.Amarkets_Map_Pack_Column_Type.Map is
    Tmp_Map :  Table_Amarkets.Amarkets_Map_Pack_Column_Type.Map;
    Key : Column_Type;
    Tmp_U_B_String : Unbounded_String := Null_Unbounded_String;
    Tmp_String     : String(1..1);
    pragma Warnings(Off, Tmp_String); -- used only if we have Character fields (ie String(1..1)
  begin
    Key := Marketid;
    Tmp_U_B_String := To_Unbounded_String(Data.Marketid);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Marketname;
    Tmp_U_B_String := To_Unbounded_String(Data.Marketname);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Startts;
    Tmp_U_B_String := To_Unbounded_String(String_Date_And_Time(Data.Startts));
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Eventid;
    Tmp_U_B_String := To_Unbounded_String(Data.Eventid);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Markettype;
    Tmp_U_B_String := To_Unbounded_String(Data.Markettype);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Status;
    Tmp_U_B_String := To_Unbounded_String(Data.Status);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Betdelay;
    Tmp_U_B_String := To_Unbounded_String(Data.Betdelay'Img);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Numwinners;
    Tmp_U_B_String := To_Unbounded_String(Data.Numwinners'Img);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Numrunners;
    Tmp_U_B_String := To_Unbounded_String(Data.Numrunners'Img);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Numactiverunners;
    Tmp_U_B_String := To_Unbounded_String(Data.Numactiverunners'Img);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Totalmatched;
    Tmp_U_B_String := To_Unbounded_String(Data.Totalmatched'Img);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Totalavailable;
    Tmp_U_B_String := To_Unbounded_String(Data.Totalavailable'Img);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Ixxlupd;
    Tmp_U_B_String := To_Unbounded_String(Data.Ixxlupd);
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    Key := Ixxluts;
    Tmp_U_B_String := To_Unbounded_String(String_Date_And_Time(Data.Ixxluts));
    Tmp_Map.Insert(Key, Tmp_U_B_String);

    return Tmp_Map;
  end To_Map;
 ---------------------------


  procedure Read_Eventid(
                           Data  : in out Table_Amarkets.Data_Type'class;
                           List  : in out Amarkets_List_Pack2.List;
                           Order : in     Boolean := False;
                           Max   : in     Integer_4 := Integer_4'Last) is
    use Sql;
    Start_Trans : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;
    if Order then
    Stm_Select_I2_Eventid_O.Prepare("select * from AMARKETS " &
                "where EVENTID =:EVENTID " &
            "order by " & 
            "MARKETID");
    Stm_Select_I2_Eventid_O.Set("EVENTID", Data.Eventid);
      Read_List(Stm_Select_I2_Eventid_O, List, Max);
    else
    Stm_Select_I2_Eventid.Prepare("select * from AMARKETS " &
                "where EVENTID =:EVENTID " &
            "");
    Stm_Select_I2_Eventid.Set("EVENTID", Data.Eventid);
      Read_List(Stm_Select_I2_Eventid, List, Max);
    end if;
    if Start_Trans then Transaction.Commit; end if;      
  end Read_Eventid;
-----------------------------------------------



  procedure Read_Markettype(
                           Data  : in out Table_Amarkets.Data_Type'class;
                           List  : in out Amarkets_List_Pack2.List;
                           Order : in     Boolean := False;
                           Max   : in     Integer_4 := Integer_4'Last) is
    use Sql;
    Start_Trans : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;
    if Order then
    Stm_Select_I3_Markettype_O.Prepare("select * from AMARKETS " &
                "where MARKETTYPE =:MARKETTYPE " &
            "order by " & 
            "MARKETID");
    Stm_Select_I3_Markettype_O.Set("MARKETTYPE", Data.Markettype);
      Read_List(Stm_Select_I3_Markettype_O, List, Max);
    else
    Stm_Select_I3_Markettype.Prepare("select * from AMARKETS " &
                "where MARKETTYPE =:MARKETTYPE " &
            "");
    Stm_Select_I3_Markettype.Set("MARKETTYPE", Data.Markettype);
      Read_List(Stm_Select_I3_Markettype, List, Max);
    end if;
    if Start_Trans then Transaction.Commit; end if;      
  end Read_Markettype;
-----------------------------------------------



  procedure Read_Status(
                           Data  : in out Table_Amarkets.Data_Type'class;
                           List  : in out Amarkets_List_Pack2.List;
                           Order : in     Boolean := False;
                           Max   : in     Integer_4 := Integer_4'Last) is
    use Sql;
    Start_Trans : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;
    if Order then
    Stm_Select_I4_Status_O.Prepare("select * from AMARKETS " &
                "where STATUS =:STATUS " &
            "order by " & 
            "MARKETID");
    Stm_Select_I4_Status_O.Set("STATUS", Data.Status);
      Read_List(Stm_Select_I4_Status_O, List, Max);
    else
    Stm_Select_I4_Status.Prepare("select * from AMARKETS " &
                "where STATUS =:STATUS " &
            "");
    Stm_Select_I4_Status.Set("STATUS", Data.Status);
      Read_List(Stm_Select_I4_Status, List, Max);
    end if;
    if Start_Trans then Transaction.Commit; end if;      
  end Read_Status;
-----------------------------------------------



  procedure Read_Numwinners(
                           Data  : in out Table_Amarkets.Data_Type'class;
                           List  : in out Amarkets_List_Pack2.List;
                           Order : in     Boolean := False;
                           Max   : in     Integer_4 := Integer_4'Last) is
    use Sql;
    Start_Trans : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;
    if Order then
    Stm_Select_I5_Numwinners_O.Prepare("select * from AMARKETS " &
                "where NUMWINNERS =:NUMWINNERS " &
            "order by " & 
            "MARKETID");
    Stm_Select_I5_Numwinners_O.Set("NUMWINNERS", Data.Numwinners);
      Read_List(Stm_Select_I5_Numwinners_O, List, Max);
    else
    Stm_Select_I5_Numwinners.Prepare("select * from AMARKETS " &
                "where NUMWINNERS =:NUMWINNERS " &
            "");
    Stm_Select_I5_Numwinners.Set("NUMWINNERS", Data.Numwinners);
      Read_List(Stm_Select_I5_Numwinners, List, Max);
    end if;
    if Start_Trans then Transaction.Commit; end if;      
  end Read_Numwinners;
-----------------------------------------------



  procedure Read_Ixxluts(
                           Data  : in out Table_Amarkets.Data_Type'class;
                           List  : in out Amarkets_List_Pack2.List;
                           Order : in     Boolean := False;
                           Max   : in     Integer_4 := Integer_4'Last) is
    use Sql;
    Start_Trans : constant Boolean := Sql.Transaction_Status = Sql.None;
    Transaction : Sql.Transaction_Type;
  begin
    if Start_Trans then Transaction.Start; end if;
    if Order then
    Stm_Select_I6_Ixxluts_O.Prepare("select * from AMARKETS " &
                "where IXXLUTS =:IXXLUTS " &
            "order by " & 
            "MARKETID");
    Stm_Select_I6_Ixxluts_O.Set_Timestamp("IXXLUTS", Data.Ixxluts);
      Read_List(Stm_Select_I6_Ixxluts_O, List, Max);
    else
    Stm_Select_I6_Ixxluts.Prepare("select * from AMARKETS " &
                "where IXXLUTS =:IXXLUTS " &
            "");
    Stm_Select_I6_Ixxluts.Set_Timestamp("IXXLUTS", Data.Ixxluts);
      Read_List(Stm_Select_I6_Ixxluts, List, Max);
    end if;
    if Start_Trans then Transaction.Commit; end if;      
  end Read_Ixxluts;
-----------------------------------------------



  procedure From_Xml(Xml_Filename : in Unbounded_String;
                     A_List       : in out Amarkets_List_Pack2.List) is
    My_Reader   : Amarkets_Reader;
    Input       : File_Input;
  begin
    My_Reader.Amarkets_List := A_List;
    My_Reader.Current_Tag := Null_Unbounded_String;
    Open(To_String(Xml_Filename), Input);
    My_Reader.Set_Feature(Validation_Feature,False);
    My_Reader.Parse(Input);
    Input.Close;
    if not My_Reader.OK then
       My_Reader.Amarkets_List.Clear;
    end if;
    A_List := My_Reader.Amarkets_List;
  end From_Xml;

end Table_Amarkets;
