#!/bin/bash


#git log -1 | grep ^commit | cut -d " " -f 2


TARGET_FILE=svn.info
TARGET_ADA_SPEC=$1

#svn info > $TARGET_FILE


LAST_REVISION_ON_DISK=1
LAST_REVISION_ON_FILE=0


#check to see if we have a better one
#[ -r $TARGET_FILE ] && LAST_REVISION_ON_DISK=$(cat $TARGET_FILE | grep Revision | cut -d':' -f2)

#with Sattmate_Types; use Sattmate_Types;
# package Bot_Svn_Info is
#  Revision : constant Integer_4 := $LAST_REVISION_ON_DISK
#  ; -- intentionally on this line!
# end Bot_Svn_info;
#

#check to see what we have in the Ada spec
#[ -r $TARGET_ADA_SPEC ] && LAST_REVISION_ON_FILE=$(cat $TARGET_ADA_SPEC | grep Revision | cut -d'=' -f2)

LAST_REVISION_ON_DISK=9999
echo " $LAST_REVISION_ON_DISK / $LAST_REVISION_ON_FILE  "

LAST_GIT_COMMIT=$(git log -1 | grep ^commit | cut -d " " -f 2)


#if [ $LAST_REVISION_ON_DISK -gt $LAST_REVISION_ON_FILE ] ; then
  echo ""                                                           > $TARGET_ADA_SPEC
  echo ""                                                          >> $TARGET_ADA_SPEC
  echo "-- Autogenerated by $0 "                                   >> $TARGET_ADA_SPEC
#  echo "with Types; use Types;"                                    >> $TARGET_ADA_SPEC
  echo "package Bot_Svn_Info is "                                  >> $TARGET_ADA_SPEC
#  echo "  Revision : constant Integer_4 := $LAST_REVISION_ON_DISK" >> $TARGET_ADA_SPEC
  echo "  Revision : constant String := \"$LAST_GIT_COMMIT\""          >> $TARGET_ADA_SPEC
  echo "  ; -- intentionally on this line!"                        >> $TARGET_ADA_SPEC
  echo "end Bot_Svn_Info;"                                         >> $TARGET_ADA_SPEC
  echo ""                                                          >> $TARGET_ADA_SPEC
#fi



